### ISSUE TITLE
Allow tenants to be defined similar to connected_endpoints

### ISSUE THREAD

**Issue by melkypie** [aristanetworks/ansible-avd#1021]
**Issue Type**

- [ ] Template enhancement
- [X] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Currently all tenants are defined under a single tenants variable which makes splitting up tenants into multiple files impossible due to ansible not allowing duplicate vars. 

**Describe the solution you'd like**

This could be solved similar to how connected_endpoints is done, by allowing us to define list of tenants under a tenant variable and then define them as a top level variable.

**Describe alternatives you've considered**

Don't think there are any other than actually making it.

**Additional context**

**Comment by ClausHolbechArista** [comment]
Good idea. We should pick this up as part of 3.0, since it will potentially give data-model changes. If you wish to work on it, please wait until we have merged the pending PRs for 3.0. Otherwise I can take a stab at this.
