### ISSUE TITLE
Add option to avoid configuring vni for vlan in eos_designs

### ISSUE THREAD

**Issue by inetman28** [aristanetworks/ansible-avd#1022]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Arista AVD export type-2 and type-3 routes to EVPN fabric but this action is not needed by default. Only TYPE-5 must be advertised by default. 

**Describe the solution you'd like**

For example, I created SVI 104 in VRF INFRA on switch DC1-ESW1 and DC1-ESW2 (they are located in the same MLAG domain). 
After that, AVD created below config:
```
interface Vxlan1
   vxlan vlan 104 vni 10104
!
router bgp 65399
   vlan 104
      rd 11.11.110.5:10104
      route-target both 10104:10104
      redistribute learned
   !
```

Above configuration stretch VLAN 104 through EVPN Fabric. This behavior advertise EVPN MAC-IP  and IMET (type-2 and type-3) routes to EVPN.

```
DC1-ESW1#show bgp evpn route-type mac-ip vni 10104
BGP routing table information for VRF default
Router identifier 11.11.110.5, local AS number 65399
Route status codes: s - suppressed, * - valid, > - active, E - ECMP head, e - ECMP
                    S - Stale, c - Contributing to ECMP, b - backup
                    % - Pending BGP convergence
Origin codes: i - IGP, e - EGP, ? - incomplete
AS Path Attributes: Or-ID - Originator ID, C-LST - Cluster List, LL Nexthop - Link Local Nexthop

          Network                Next Hop              Metric  LocPref Weight  Path
 * >     RD: 11.11.110.5:10104 mac-ip 001b.1700.0a01
                                 -                     -       -       0       i
 * >     RD: 11.11.110.5:10104 mac-ip 001b.1700.0a01 192.168.4.11
                                 -                     -       -       0       i
 * >     RD: 11.11.110.5:10104 mac-ip 001b.1700.0a01 192.168.4.12
                                 -                     -       -       0       i
 * >     RD: 11.11.110.5:10104 mac-ip 001c.7300.dc01
                                 -                     -       -       0       i
```

I think these actions are not needed by default. For example, if you disable that behavior, then each MLAG domain will have unique VLAN range 1-4094.

One suggestion to avoid this is create one more key:value to avoid this, for example: ExportedToEvpn: False

**Describe alternatives you've considered**

Create SVI inside host_vars with structured_configuration_prefix.

**Comment by ClausHolbechArista** [comment]
In general I expect us to keep the current default behavior, since that will cover most customer scenarios. But I think it makes a lot of sense to add a knob per SVI to override this behavior. We will change a lot of the related logic in AVD3.0, so let us look at this one after the pending PRs for 3.0 has merged.

**Comment by inetman28** [comment]
yes, you are right. The default behavior to advertise type2 and type3 routes is good. But it should has option to avoid advertising. it is my opinion.
