### ISSUE TITLE
Support for NSSA in Router OSPF Configuration

### ISSUE THREAD

**Issue by ernestoherrerab** [aristanetworks/ansible-avd#1061]
**Issue Type**

- [ ] Template enhancement
- [X ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**
Sort of, we are migrating to EVPN/VXLAN and some of our existing OSPF areas are NSSAs.
In order to migrate them easily, NSSA support would be great to have.

There is no structured data in the router ospf configuration on the cli config gen for NSSAs.

**Describe the solution you'd like**

It would be great to have the support for: 
- nssa nssa-only
-  nssa no summary
-  nssa default information originate 
- nssa lsa7 filter

**Describe alternatives you've considered**

add the following structured data as below (for example):

router_ospf:
      process_id:
        '1':
            nssa: (if nssa key exists, enable nssa e.g. area x nssa)
                nssa_only: <true | false>
                nssa_no_summary: '<true | false>
                default_information_originate: <true | false>

**Comment by ankudinov** [comment]
@ernestoherrerab Please add more details on `nssa lsa7 filter`. AVD supports summary-address currently. Please add more details about use case if that is not sufficient. I'd suggest opening a dedicated issue for that.

**Comment by ernestoherrerab** [comment]
@ankudinov That nssa lsa7 filter can be ignored. And only look at please: 
nssa nssa-only
nssa no summary
default_information_originate

Thank you for looking into it
