### ISSUE TITLE
l2vlans in eos designs, tags are required

### ISSUE THREAD

**Issue by ernestoherrerab** [aristanetworks/ansible-avd#1087]
## Issue Type

- [ ] Bug Report
- [ ] EOS Configuration rendering error
- [ X] Documentation Issue Report

## Summary

I have noticed that on the network services in designs role, the l2vlans does not mention that tags are REQUIRED

    l2vlans:
      < 1-4096 >:
        vni_override: < 1-16777215 >
        name: < description >
        tags: [ < tag_1 >, < tag_2 > ]
'
Would be good to add as a note.

## Component Name

https://avd.sh/en/latest/roles/eos_designs/doc/l3ls-evpn/network-services.html

## Steps to reproduce

    l2vlans:
      < 1-4096 >:
        vni_override: < 1-16777215 >
        name: < description >
        tags: [ < tag_1 >, < tag_2 > ] REQUIRED

### Expected results

---

### Actual results

```shell
ss

**Comment by ClausHolbechArista** [comment]
Make it optional (default to `['all']`)
