### ISSUE TITLE
bgp_listen_range_prefix inside VRF

### ISSUE THREAD

**Issue by inetman28** [aristanetworks/ansible-avd#1088]
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [x] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Arista AVD doesn't have key to configure bgp_listen_range_prefix inside VRF. 

**Describe the solution you'd like**

I would like to have feature to estab dynamic bgp neighbors inside VRF

**Describe alternatives you've considered**

only create outside playbook/role to do this

**Comment by ccsnw** [comment]
@ClausHolbechArista I could add the updated listen_ranges model to vrfs in order to fix this. Ok with you?

**Comment by ClausHolbechArista** [comment]
That would be great. Thanks
