### ISSUE TITLE
native_vlan missing on port_channel_interfaces documentation

### ISSUE THREAD

**Issue by ernestoherrerab** [aristanetworks/ansible-avd#1092]
## Issue Type

- [ ] Bug Report
- [ ] EOS Configuration rendering error
- [x] Documentation Issue Report

## Summary

native_vlan not included in cli config gen for port_channel_interfaces

## Component Name
eos_cli_config_gen
          port_channel_interfaces

## Steps to reproduce

```yaml

```

### Expected results

```shell
$
```

### Actual results

```shell

```

**Comment by ClausHolbechArista** [comment]
Fixed in #1038
