### ISSUE TITLE
Feat(eos_designs): Native VLAN Change

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#1096]
**Issue Type**

- [X] Template enhancement
- [X] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

https://eos.arista.com/arista-eos-hardening-guide/ recommends native vlan changed and vlan 1 disabled. It is something that is not a big deal in regards of mitigation or implementation.  Unfortunately AVD eos_designs does not provide a knob for disabling VLAN 1 and setting a different native VLAN on a trunk.

**Describe the solution you'd like**

Provide a "knob" for disabling VLAN 1 and setting a different native VLAN on a trunk.

**Describe alternatives you've considered**

Using customized structured config or updated the dictionary of the structured config post generation.

**Additional context**

**Comment by ClausHolbechArista** [comment]
Global knob to disable vlan 1 (and maybe other vlans) . Another global knob to set `default_native_vlan`.

**Comment by ClausHolbechArista** [comment]
@ryanmerolle It took a while :) But I have implemented something that is related to this: #2522 . Let me know if it resolves this ask.

**Comment by ryanmerolle** [comment]
@ClausHolbechArista looks great. I’m closing this out
