### ISSUE TITLE
add spanning tree bpduguard disable functionality

### ISSUE THREAD

**Issue by ifoughal** [aristanetworks/ansible-avd#1105]
**Issue Type**

- [x] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Currently, the ethernet template has the functionality `spanning_tree_bpduguard:  < true | false >` but in reality, it only supports the falue true which enables the spanning_tree_bpduguard, but disabling it doesn't work.

the template enhancement needed to add support for the `spanning tree bpduguard disable` would then be as the following described below.

**Describe the solution you'd like**

lines to add:

`{%         if ethernet_interfaces[ethernet_interface].spanning_tree_bpduguard is arista.avd.defined(true) %}`
`   spanning-tree bpduguard enable`
`{%         elif ethernet_interfaces[ethernet_interface].spanning_tree_bpduguard is arista.avd.defined(false) %}`
`   spanning-tree bpduguard disable`
`{%         endif %}`

**Describe alternatives you've considered**

None found.

**Additional context**

None.

**Comment by carlbuchmann** [comment]
@idrisFoughali thanks for submitting this issue, and I agree with the proposed functionality!
Are you planning to submit a PR for this?

**Comment by ifoughal** [comment]
@carlbuchmann I wasn't planning on submitting a pull request, but will do if that's needed.
