### ISSUE TITLE
Use BGP dynamic peerings

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#111]
I see that we have a lot of neighbours generated in the topology on the Spines.
It will be very useful if we could use bgp listen-range with peer-filter for ASN and IP. 
This will contribute a lot in lowering the number of lines of the config generated.

**Comment by onurgashi** [comment]
peer-filter LEAF-AS-RANGE
   10 match as-range 65101-65132 result accept

I see this configured, but we don't seem to use it.

**Comment by ankudinov** [comment]
Using listen-range is suboptimal for automated network. It's preferred to keep all data explicit and use it for provisioning.
Listen-range on the other hand hides some data to simplify configuration from the human perspective.
Closing.
