### ISSUE TITLE
Make EVPN fabric documentation optional

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#1110]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

When rendering a L3LS fabric with 40+ leafs generating the Markdown documentation will take a long time.

**Describe the solution you'd like**

It would be very convenient to be able to disable the documentation generation using a tag to save build time on e.g. a CI system which is not interested in the documentation and should only roll out the fabric config.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by lermilov** [comment]
I will take it

**Comment by titom73** [comment]
It seems we already have some options available for that:

- PR #1024 implementing a knob in `eos_cli_config_gen`
- PR #1053 playing wiht ansible tag

**Comment by carlbuchmann** [comment]
@c-po -> to skip documentation, you can execute the playbook like this:

```shell
ansible-playbook playbooks/dc1-fabric-deploy.yml --tags build,provision --skip-tags documentation -i inventory.yml
```

Please confirm the addresses your issue!

**Comment by c-po** [comment]
@carlbuchmann thank you, this was exactly why I was looking for!
