### ISSUE TITLE
No need to redistribute dc IP blocks to BGP

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#113]
It might be a good idea to remove the route-map line that redistributes directly connected interfaces in underlay to BGP. This is not needed, and there is no use case of carrying them around.

route-map RM-CONN-2-BGP permit 20
   match ip address prefix-list PL-P2P-UNDERLAY

**Comment by titom73** [comment]
Please check PR #119 for suggested fix.

**Comment by ankudinov** [comment]
Looks good.

**Comment by carlbuchmann** [comment]
resolved PR #119
