### ISSUE TITLE
Improve Upgrade tools role documentation

### ISSUE THREAD

**Issue by xaviramon** [aristanetworks/ansible-avd#1140]
**Issue Type**

- [ ] Template enhancement
- [ ] Role enhancement
- [x] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Extend documentation for upgrade_tools role, including a workflow.

**Describe the solution you'd like**

For consistency and easiness of use, extend role documentation.

**Describe alternatives you've considered**

None

**Additional context**

**Comment by ClausHolbechArista** [comment]
The upgrade_tools role has been replaced with `tasks_from: upgrade` on the regular `eos_designs` and `eos_cli_config_gen` roles. Documentation has been updated and enhanced.
