### ISSUE TITLE
security acls, policer & vrf leaking

### ISSUE THREAD

**Issue by dannypetrov** [aristanetworks/ansible-avd#115]
Hello,

thanks for all your efforts putting all this together. It makes building fabrics so easy.. 

I have been going through what's currently supported by this collection, but I was wondering if you guys have any plans to add some of the following functionalities:

- VRF leaking (for shared VRF (services) across tenants) 
- Security ACLs for edge ports?  (for compliance with security regulations, considering the multi-tenancy) 
- Simple policer (nothing too fancy re QoS, just a policer to set some bandwidth to class default)

If not, could you advise what'll be the best way to achieve this functionality? 
- Using external (CVP created) configlets is an option, but It kinda defats the `singe source of truth` concept. 
- Modifying `avd` collection to port/retrofit this functionality (which solves the problem with the single source of truth from the above, but raises some other concerns with code maintenance :-)) 

I have added the security acl functionality (more than happy to contribute it here if this is okay) to the relevant sections/roles and templates, but I am wondering if you’d rather do this “officially”?  

I hope the above makes sense, thanks in advance for your time and apologies if I have somehow abused this to address irrelevant stuff.

**Comment by carlbuchmann** [comment]
@dannypetrov - Thank you for the positive feedback glad you like it! Our goal is definitely to increase coverage of features to handle various use cases over time. And, yes, we encourage contributions from the community, so feel free to submit a PR with your recommended changes to extend the framework - we will review and merge! 
Contribution guide is located here: https://github.com/aristanetworks/ansible-avd/blob/master/contributing.md
