### ISSUE TITLE
Module inventory_to_container has incorrect function parameter

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#116]
inventory_to-container module uses an incorrect parameter to call `get_device` function for a [specific scenario](https://github.com/aristanetworks/ansible-avd/blob/3ec68bfadaa4d121f894b6930f5a73058a9317c1/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py#L275)

No execution error has been reported, but should be fixed to protect unexpected situation.

```python
// get_device definition
def get_devices(dict_inventory, search_container=None, devices=None)

// get_device call:
# Extract sub-group information
for k2, v2 in v1.items():
    get_devices(
        dict_inventory=v2,
        search_container=search_container,
        devcices=devices
    )

```

**Comment by carlbuchmann** [comment]
closing issue fixed in PR #122
