### ISSUE TITLE
Trailing zeroes removed on 4-byte BGP ASN in asdot notation

### ISSUE THREAD

**Issue by emilotep** [aristanetworks/ansible-avd#1160]
### Issue Summary

When defining the BGP ASN for any node using a 4-byte ASN in asdot notation, the yaml logic interprets the value as a float and removes trailing zeroes. So 65000.100 becomes 65000.1. This happens even when forcing the value to be a string like so: 

'''
spine:
  platform: vEOS-LAB
  defaults:
    # EOS CLI rendered directly on the root level of the final EOS configuration
    loopback_ipv4_pool: 100.64.11.0/24
    bgp_as: "65000.100"
'''

The debug-vars file has the correct value if you set it as a string like above, but the rendered structured_configuration for the device has wrong value (float with trailing zeroes removed) regardless. 

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
In DC1_FABRIC.yml:

spine:
  platform: vEOS-LAB
  defaults:
    # EOS CLI rendered directly on the root level of the final EOS configuration
    loopback_ipv4_pool: 100.64.11.0/24
    bgp_as: "65000.100"
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by perimore** [comment]
This seems to have cropped up again now that we're using eos_designs_facts.py. 

https://github.com/aristanetworks/ansible-avd/blob/607517728ee3e2113663daffb28a76d76486b8a9/ansible_collections/arista/avd/plugins/plugin_utils/eos_designs_facts.py#L1090

`return str(get(self._hostvars, "bgp_as"))`

Can we add a check or for the cast to a string as-is?

**Comment by ClausHolbechArista** [comment]
This is not happening in this code. It is most likely the input data that is not a string. So in YAML `123.100` means `float with value 123.1`. So it is lost before even entering our code.
You need to enclose the ASN in quotes in the YAML file.

**Comment by perimore** [comment]
Sure, we should probably note that in the docs tbh. Or can we fix this in code?

**Comment by ClausHolbechArista** [comment]
This cannot be solved in code. It is part of YAML to behave like this. It will be caught by our schemas when we get everything covered.

**Comment by perimore** [comment]
perfect, thanks!
