### ISSUE TITLE
Feat(eos_designs): Allow for Management interface description customization

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#1174]
### Enhancement summary

Currently the logic only allows for `oob_management` as the Management interface description.  I think this should be customizeable in eos_designs.

### Which component of AVD is impacted

eos_designs

### Use case example

This makes total sense if you want to document on the port description what the Management port is even connected to or just want to set the description to something other than `oob_management`.

### Describe the solution you would like

Allow the logic in eos_designs

### Describe alternatives you have considered

Overwrite eos_designs generated logic after eos_designs runs but before eos_cli_config_gen runs.

Unfortunately, that would mean this interface descriptions would not match the markdown docs generated by eos_designs

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by titom73** [comment]
Hello @ryanmerolle 

Have you seen PR #1156 ? If management is not yet covered by this PR, we can see to add Management interface in this change.
