### ISSUE TITLE
ATD install.sh typo

### ISSUE THREAD

**Issue by MrWhoThis** [aristanetworks/ansible-avd#1228]
### Issue Summary

45    echo "Installtion done."

### Which component(s) of AVD impacted

others

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Thank you for catching this and submitting this issue.
The installation script is maintained as part of another repo, but I have created a PR for the fix here:
https://github.com/arista-netdevops-community/avd-install/pull/10

**Comment by ClausHolbechArista** [comment]
fix merged
