### ISSUE TITLE
Suppor for OSPF redistribution in a VRF

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#1233]
### Enhancement summary

Hi,

Looking for support to redistribute OSPF routes into BGP within a VRF. EOS config would look like (with an optional route-map):

```
   vrf VRF-INET2-USVHI3W6
      rd 52.7.132.31:10009
      route-target import evpn 10009:10009
      route-target export evpn 10009:10009
      router-id 52.7.132.31
      redistribute connected
      redistribute ospf match internal
      redistribute ospf match external
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Border leaves learning routes from downstream routers that need to be injected into the EVPN domain.

### Describe the solution you would like

Add support for ospf redistribution in eos_cli_config_gen role.

### Describe alternatives you have considered

Workaround for now is using this which works fine, but would prefer not to use "raw cli commands":

```
custom_structured_configuration_router_bgp:
  vrfs:
    VRF-INET1-USVHI3W6:
      eos_cli:
         redistribute ospf match internal

         redistribute ospf match external
```

I also considered structured config in eos_designs configuration, but it does not allow to specify specific nodes (only border leaves need redistribution).

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by inetman28** [comment]
good feature request. 
Also It was greate if you would introduce redistribute route map inside vrf.

**Comment by tgodaA** [comment]
Hi David, this feature is already implemented. Look for redistribute_routes under vrf: https://avd.sh/en/releases-v3.x.x/roles/eos_cli_config_gen/index.html#router-bgp-configuration

Yaml snippet to recreate your example:
**Note**: Indentation will be different. This should be with in vrfs.

```yaml
redistribute_routes:
  connected:
  ospf match internal:
  ospf:
    route_map: RM-CONN-2-BGP
```

Other way to redistribute routes if route_map is not used:
```yaml
redistribute_routes:
  - connected
  - ospf match internal
  - ospf match external
```

**Comment by tgodaA** [comment]
Please close this issue if everything works.

**Comment by dgonzalez-arista** [comment]
Hi Tony,

Thanks that worked fine. It does not seem documented anywhere though:
https://avd.sh/en/releases-v3.x.x/roles/eos_cli_config_gen/index.html#router-bgp-configuration

```
      redistribute_routes:
        < route_type >:
          route_map: < route_map_name >
        < route_type >:
          route_map: < route_map_name >
```

Is there any other place where all the route_types supported and options for redistribution are documented? Could not find anything around "ospf match internal/external" etc?
