### ISSUE TITLE
Feat(eos_designs): Add router general router-id ipv4 knob

### ISSUE THREAD

**Issue by lermilov** [aristanetworks/ansible-avd#1245]
### Enhancement summary

Starting EOS 4.22.1F (https://eos.arista.com/eos-4-22-1f/general-router-id/) we support to set global router-id which can inherited to all BGP VRFs. Currently, AVD add router-id knob per VRF, which is suboptimal comparing to single global router-id config.

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen

### Use case example

Less config within VRF, best practice from EOS perspective

### Describe the solution you would like

Add eos-designs variable to enable using router general router-id ipv4 knob

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by lermilov** [comment]
Please assign it to me

**Comment by ClausHolbechArista** [comment]
Implement a fabric variable `use_router_general_for_router_id: < true | false | default -> false >`
