### ISSUE TITLE
Node group with a specific filter and no "vlan/svi/VRFs" data

### ISSUE THREAD

**Issue by krikoon73** [aristanetworks/ansible-avd#125]
**Issue Type**
- Template enhancement

**Is your feature request related to a problem? Please describe.**
The idea is to have a node group with a specific filter and no data associated (ex. vlan/svis/VRF). This for use case of :
- having "compute" leaf with full automated vlans/svi/VRFs provisioning
- having "border" leaf with specific configuration managed manually
Today the AVD configuration is requiring having "TENANT" data for every filters configured in the FABRIC description.

**Describe the solution you'd like**
"TENANT" data could have no data for a specific filter or a keyword like "none" for a specific filter

**Describe alternatives you've considered**
Currently, the idea is to provision a "fake" SVIs

**Additional context**

**Comment by carlbuchmann** [comment]
@krikoon73, I agree with the suggestion and using the "none" keyword when no automated vlans/svi/VRFs need to be created automatically. We will target this enhancement for v1.1.x release.

**Comment by titom73** [comment]
Hi @krikoon73 

A fix is available with PR#126 and it is ready for testing. Current implementation allows group_vars to set a __tag__ even if no VXLANs resources are defined under your tenant_services file.

Please confirm if it works as expected.

**Comment by krikoon73** [comment]
Tested - It's Ok.
Thank you.

**Comment by titom73** [comment]
Merged into `releases/v1.0.x`
