### ISSUE TITLE
Overlapping IP Addresses under loopbacks for vtep diagnostic

### ISSUE THREAD

**Issue by inetman28** [aristanetworks/ansible-avd#1252]
### Issue Summary

Hi, I found out that IP addresses under loopbacks which are using for vtep diagnostic are overlapping between each PODs. 
I have 5stage topology with two pods and addresses in pod 1 started from 192.168.255.3/32, and same truth for second pod, there are IP addresses are started from same address - 192.168.255.3/32

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
1. add to inventory
    DC1_TENANTS_NETWORKS:
      children:
        DC1_BORDER_LEAFS:
        DC1_POD1_LEAFS:
        DC1_POD2_LEAFS:

2. create DC1_TENANTS_NETWORKS file and put below strings:
  TENANTS_A:
    mac_vrf_vni_base: 10000
    enable_mlag_ibgp_peering_vrfs: true
    vrfs:
      VRF-RED:
        vrf_vni: 116
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 192.168.255.0/24

3. end up run your playbook and you will see overlapping in each pod
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by carlbuchmann** [comment]
@inetman28 thanks for reporting this issue, we will look into this issue next week.

**Comment by ClausHolbechArista** [comment]
Implement `vtep_diagnostic_loopback_ip_offset: <integer | default -> 0 >` per POD and use that as basis for setting IP.

**Comment by ClausHolbechArista** [comment]
A workaround for this would be inline jinja like `loopback_ip_range: "{{ { 'POD1':'172.16.1.0/24', 'POD2':'172.16.2.0/24' }[pod_name] }}"`
