### ISSUE TITLE
Missing " cvp_instance_ips" from roles documentation "dhcp_provisioner"

### ISSUE THREAD

**Issue by prajwalarista** [aristanetworks/ansible-avd#1256]
The role documentation for the role "dhcp_provisioner" doesn't provide any information for the  registration parameter for ZTP. 
The variable cvp_instance_ip(s) should be mentioned in the group_vars directory for the role to work. Kindly add that information there.
thanks

**Comment by ClausHolbechArista** [comment]
Fixed in #1431
