### ISSUE TITLE
ISIS as an underlay

### ISSUE THREAD

**Issue by krikoon73** [aristanetworks/ansible-avd#127]
**Issue Type**

- Template creation/enhancement

**Is your feature request related to a problem? Please describe.**
Today, it is not possible to configure ISIS as an underlay for deploying an EVPN Fabric. 

**Describe the solution you'd like**
The idea is to offer in the Fabric template a way to declare ISIS as an underlay - Minimum is :
```
router isis UNDERLAY
   net {{ RANGE }}
   is-hostname {{ hostname }}
   is-type {{ level || default "level-2" }}
   !
   redistribute connected route-map {{ loopback_RM }}
   address-family ipv4 unicast
      maximum-paths {{ number_spines | default 2}}
```

**Describe alternatives you've considered**
N/A.

**Additional context**
This enhancement should consider the use of iBGP as an overlay => another `issue:Feature request`

**Comment by titom73** [comment]
Merged in devel branch
