### ISSUE TITLE
Documentation task will fail if spanning_tree_mode is not set in the group_vars

### ISSUE THREAD

**Issue by prajwalarista** [aristanetworks/ansible-avd#1290]
### Enhancement summary

On using the role "eos_cli_config_gen", if the spanning_tree_mode is not set in the group_vars, the documentation task throws an error and fails the documentation.
Need to resolve this, it should not fail the documentation.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

I missed out the "spanning_tree_mode" in my group_vars. This caused an error in documentation and failed the same task of documentation. 

### Describe the solution you would like

Would be better if this is skipped, so as to not cause any failure in documentation. 

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Done in PR #1230
