### ISSUE TITLE
eos_cli_config_gen - refactor `evpn_ethernet_segment`

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#1297]
### Issue Summary

refactor `eos_cli_config_gen` data model for `port_channel_interfaces` to enclose esi, rt, redundancy in `evpn_ethernet_segment` to match CLI model closer.

Old model:
```shell
{%     if port_channel_interfaces[port_channel_interface].esi is arista.avd.defined %}
   evpn ethernet-segment
      identifier {{ port_channel_interfaces[port_channel_interface].esi }}
{%         if port_channel_interfaces[port_channel_interface].rt is arista.avd.defined %}
      route-target import {{ port_channel_interfaces[port_channel_interface].rt }}
{%         endif %}
{%     endif %}
```

**Comment by gmuloc** [comment]
@carlbuchmann looking at this reopned issue I think it was fixed by @emilarista  as part of the A/A work: documentation: https://avd.sh/en/stable/roles/eos_cli_config_gen/index.html#port-channel-interfaces. PR fixing it https://github.com/aristanetworks/ansible-avd/pull/1780
