### ISSUE TITLE
eos_designs - `mlag xx` is rendered on port-channels to servers even when switches do not run mlag.

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#1318]
### Issue Summary

Molecule output for switches without mlag still show mlag ids and descriptions on the port-channels.

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Example from molecule: https://github.com/aristanetworks/ansible-avd/blob/c9c6d28f64a0f6f21c7b07deb5633f153959bd13/ansible_collections/arista/avd/molecule/evpn_underlay_ebgp_overlay_ebgp/intended/configs/DC1-LEAF2B.cfg#L143
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by carlbuchmann** [comment]
The following logic would need to be updated to also check if `switch.mlag is arista.avd.defined(true)`
https://github.com/aristanetworks/ansible-avd/blob/03d3271ca1b78c54d0d752a3b9037e6f9c6fdfb5/ansible_collections/arista/avd/roles/eos_designs/templates/connected_endpoints/port-channel-interfaces.j2#L64
