### ISSUE TITLE
Support for EVPN single-active multihoming

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#1330]
### Enhancement summary

This feature is pretty recent: 4.26.0F:
https://eos.arista.com/eos-4-26-0f/evpn-single-active-multihoming-preference-based-df-election/

Requesting support to configure EVPN A/S in ethernet or port-channel interfaces, including DF preference:
```
interface Ethernet5
   switchport mode trunk
   !
   evpn ethernet-segment
      identifier 0000:0000:0011:1100:0000
      redundancy single-active
      designated-forwarder election algorithm preference 200
      route-target import 00:00:00:00:11:11
```

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen

### Use case example

Deploy some leaves with EVPN A/S, so only one of the PEs is actively forwarding traffic.

### Describe the solution you would like

Describe ESIs in SERVER files with EVPN multihoming redundancy single-active and select a DF preference.

### Describe alternatives you have considered

Currently i can achieve this in the SERVER file via raw cli commands:
```
---  
routers:
    swCE1_CE2:
      rack: RackA
      adapters:
        - endpoint_ports: [et1, et1]
          switch_ports: [Ethernet5, Ethernet5]
          switches: [ DC-1-BL-2, DC-2-BL-2]
          vlans: "10,20,30,40"
          profile: TRUNK_1G
          raw_eos_cli:
              switchport mode trunk
             
              evpn ethernet-segment

              redundancy single-active

              designated-forwarder election algorithm preference 100

              identifier 0000:0000:0011:1100:0000

              route-target import 00:00:00:00:11:11
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by UchihaItachiSama** [comment]
Similar issue #1163 where we are discussing the support for single-active MH with DF election for `eos_cli_config_gen` 

we would need a separate PR for updates to `eos_designs` as well.

we can discuss and work on the respective PRs for   `eos_cli_config_gen` and `eos_designs`

**Comment by ClausHolbechArista** [comment]
The eos_cli_config_gen part is resolved in #1437

**Comment by ClausHolbechArista** [comment]
@dgonzalez85 do you agree that we can close this issue?

**Comment by dgonzalez-arista** [comment]
Hi @ClausHolbechArista sorry i missed this. Indeed we can close this. I was dicussing with @gmuloc about creating a separate issue to support this in the eos_designs role, but maybe thats already WIP? 

thanks
