### ISSUE TITLE
mlag & non mlag reload-delay

### ISSUE THREAD

**Issue by glennsb** [aristanetworks/ansible-avd#137]
Curious about the seemingly disconnect of the mlag delay & non mlag delay timers

The published [design guide PDF] (https://downloads.arista.com/DesignGuides/EVPN_Deployment_Guide.pdf) in the "Adjust MLAG Reload-Delay Timers (MLAG Only)" section has values where `reload-delay mlag` < `reload-delay non-mlag`

Yet code in the repository below 

https://github.com/aristanetworks/ansible-avd/blob/92defecc9d0ae860c99aed683b273479b339c4b2/ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/mlag/leaf-mlag-configuration.j2#L14

& the notes in the ticket #52 about it

both have it the other way with `reload-delay mlag` > `reload-delay non-mlag`

So which is "right", the PDF or the repository code?

**Comment by carlbuchmann** [comment]
@glennsb, thank you for noticing this discrepancy! I will double-check but believe you are correct and the design guide is accurate.

**Comment by carlbuchmann** [comment]
@glennsb - PR #141 implements the new default values and we refactored the template/data model to allow tuning them based on specifics of the environment. 

If you have any further questions, please feel free to reach out to ansible@arista.com.
