### ISSUE TITLE
"In band" Management

### ISSUE THREAD

**Issue by ninnux** [aristanetworks/ansible-avd#1384]
### Enhancement summary

AVD configure the network to be managed out of band only.
We would like to manage our net using "in band" model. "In band" means that CVP use loopback interfaces instead of Management interface.
Every node will have a loopback on a dedicated vrf (eg. MANAGEMENT vrf) and we need to associate Management1 interface in the same vrf.
AVD requires mandatory "mgmt_gateway" variable definition and the result is a default static route in MANAGEMENT vrf.
We already have the default route in MANAGEMENT vrf and this can cause a problem to our global MANAGEMENT routing.

### Which component of AVD is impacted

eos_designs

### Use case example

- Every node have a loopback on a MANAGEMENT vrf
- That MANAGEMENT VRF have an its own dynamic routes announced by BGP
- CVP and Arista devices sent their messages through that MANAGEMENT VRF
- in case of disaster, Arista devices will be managed by console servers

### Describe the solution you would like

The first way we think about is to remove the mandatory of mgmt_gateway from "templates/base/management-interfaces.j2"
We noted into termplate file that AVD use management_interface.type: oob maybe there is a clean way to add "in band" interface.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
This is a good use case, and I hope we can solve it by just using some extra variables already in AVD.

Take a look at `mgmt_destination_networks`. If you add your more specific networks here, it will take precedence over the default route for the management interface

From the template `base/static-routes.j2`:
```jinja
static_routes:
{% if mgmt_destination_networks is arista.avd.defined and mgmt_destination_networks | length > 0 %}
{%     for mgmt_destination_network in mgmt_destination_networks %}
  - vrf: {{ mgmt_interface_vrf }}
    destination_address_prefix: {{ mgmt_destination_network }}
    gateway: {{ mgmt_gateway }}
{%     endfor %}
{% else %}
  - vrf: {{ mgmt_interface_vrf }}
    destination_address_prefix: 0.0.0.0/0
    gateway: {{ mgmt_gateway }}
{% endif %}
```

As I read your issue, this will do exactly what you are after.
Please test and update here.
Thanks.
Claus
