### ISSUE TITLE
BGP redistribute connected/static include leaked unsupported

### ISSUE THREAD

**Issue by ninnux** [aristanetworks/ansible-avd#1385]
### Issue Summary

When you use route leaking into Arista a needed command for BGP configuration is:

"redistribute connected include leaked" or
"redistribute static include leaked"

that permit to export leaked routes to other nodes by BGP.

AVD seems do not support that configuration (for example under "router bgp XXXX"."vrf YYYY").
On AVD documentation we simply find:
```
      redistribute_routes:
        < route_type >:
          route_map: < route_map_name >
        < route_type >:
          route_map: < route_map_name >
```

we walk around that AVD issue adding a manual configured CVP configlet

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ccsnw** [comment]
@ninnux you should be able to use:

```
      redistribute_routes:
        "static include leaked":
          route_map: < route_map_name >
       "connected include leaked":
          route_map: < route_map_name >
```

because the source-protocol is not validated. This should already solve your issue?
