### ISSUE TITLE
Add support for no qos trust in qos profiles

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#1387]
### Enhancement summary

Currently there is no option in the docs to set this:
```
qos profile test
   no qos trust
```

https://avd.sh/en/latest/roles/eos_cli_config_gen/index.html#qos-profiles

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Set no qos trust on ports using a qos profile.

### Describe the solution you would like

Enable this config in eos_cli_config_gen role.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by tgodaA** [comment]
I came up with these 2 data models:

```
qos:
  trust: < cos | dscp | no >
```

or another data model:

```
qos:
  trust: < cos | dscp | false >
```

Same data model can be applied to Ethernet interfaces and Port-channel interfaces.
