### ISSUE TITLE
Add Jinja2 filters to convert type when required

### ISSUE THREAD

**Issue by ankudinov** [aristanetworks/ansible-avd#140]
**Issue Type**
- Template enhancement

**Is your feature request related to a problem? Please describe.**
In some case AVD YAML files may have `<key>: "<int-value>"` instead of `<key>:<int-value>`
That can cause template parsing problems.

**Describe the solution you'd like**
Add filters to Jinja2 templates where possible.
For example, change `as: {{ spine.bgp_as }}` to `as: {{ spine.bgp_as | int }}`

**Comment by carlbuchmann** [comment]
resolved by #181
