### ISSUE TITLE
[Security] Workflow continuous_integration.yml is using vulnerable action pre-commit/action

### ISSUE THREAD

**Issue by igibek** [aristanetworks/ansible-avd#1413]
The workflow continuous_integration.yml is referencing action pre-commit/action using references v2.0.2. However this reference is missing the commit [80db042ff08cdddbbbfb6f89c06a6bfc4dddf0b7](https://github.com/pre-commit/action/commits/80db042ff08cdddbbbfb6f89c06a6bfc4dddf0b7) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by mtache** [comment]
This has been also addressed in [this issue](https://github.com/aristanetworks/ansible-cvp/issues/432). In summary, the release should contains the commit if we trust the maintainer. However, moving away from this action is the way to go.

**Comment by ClausHolbechArista** [comment]
Fixed by #1430
