### ISSUE TITLE
Add support for lldp tlv transmit ztp vlan under interface ethernet

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#1444]
### Enhancement summary

EOS supports since 4.27.1.1F to announce a vlan id via lldp for inband ztp in campus lan.
https://eos.arista.com/eos-4-27-1f/campus-ztp-through-vlan-advertised-from-spine-aggregation-switch/

AVD support for ```lldp tlv transmit ztp vlan <id>``` under ethernet interfaces is currently missing.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

CLI config is necessary to perform inband ZTP in campus access "stack" envorinments

### Describe the solution you would like

# Switched Interfaces
```
ethernet_interfaces:  
  <Ethernet_interface_2 >:  
    lldp:  
      ztp_vlan: < ztp vlan number >
 ```  

```
{%         if ethernet_interfaces[ethernet_interface].lldp.ztp_vlan is arista.avd.defined %}
    lldp tlv transmit ztp vlan {{ ethernet_interfaces[ethernet_interface].lldp.ztp_vlan }}
{%         endif %}
```

should generate:
```
interface Ethernet<nr>
   lldp tlv transmit ztp vlan <ztp vlan number>
```

### Describe alternatives you have considered

current alternative is to use ```eos_cli``` unter ```interface ethernet```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
@kmueller68 will you take on implementing this?

**Comment by kmueller68** [comment]
@ClausHolbechArista I am sorry, but I am currently not familiar with the procedure to contribute. Would need to figure things out, how to....

**Comment by kmueller68** [comment]
@ClausHolbechArista I will give it a try

**Comment by tgodaA** [comment]
@kmueller68 You can ping me if you need any help. Probably we can have some sessions to discuss and get start with the development.

**Comment by kmueller68** [comment]
@tgodaA @ClausHolbechArista 

Arista introduced Campus ZTP through VLAN advertised from Spine/Aggregation Switch with 4.27.1F
https://eos.arista.com/eos-4-27-1f/campus-ztp-through-vlan-advertised-from-spine-aggregation-switch/

It is not enough to just add ```lldp tlv transmit ztp vlan <id>``` to the config but some cli commands more.

This would end up with the following configuration
L2 MLAG setup spline - access
```
interface Port-Channel6
   description access_switch
   switchport trunk allowed vlan 100-500,1810
   switchport mode trunk
   switchport
   port-channel lacp fallback individual
   port-channel lacp fallback timeout 5
   mlag 6
!
interface Ethernet6
   description access_switch
   no shutdown
   switchport trunk allowed vlan 1810
   switchport mode trunk
   switchport
   lldp tlv transmit ztp vlan 1810
   channel-group 6 mode active
```

Based on the current eos_cli_config_gen template for "ethernet-interfaces.j2" most cli commands will be skipped as soon as ```channel-group``` is found within an ethernet yaml config.
This currently prevents that things like ```switchport```, ```switchport mode trunk```, ```switchport trunk allowed vlan``` are rendered into the cli config.

This would mean that I have to get around this to render the intended config.
```
ethernet_interfaces:  
  <Ethernet_interface_2 >:  
    lldp:  
      ztp_vlan: < ztp vlan number >
```
```
{%     if ethernet_interfaces[ethernet_interface].lldp.ztp_vlan is arista.avd.defined %}
   lldp tlv transmit ztp vlan {{ ethernet_interfaces[ethernet_interface].lldp.ztp_vlan }}
   switchport
   switchport mode trunk
   switchport trunk allowed vlan {{ ethernet_interfaces[ethernet_interface].lldp.ztp_vlan }}
{%     endif %}    
```
Would this be an acceptable way for you?

**Comment by ClausHolbechArista** [comment]
No this way it would have too much logic in `eos_cli_config_gen`.
We recently added support for `fallback individual` and circumvented the issue you explain.
If you check the latest devel under `ethernet_interfaces.j2`
```jinja
{%         if port_channel_interfaces['Port-Channel' ~ ethernet_interfaces[ethernet_interface].channel_group.id].lacp_fallback_mode is arista.avd.defined("individual") %}
{%             set print_ethernet = true %}
{%         endif %}
```
So I believe this would address your issue.

**Comment by kmueller68** [comment]
@ClausHolbechArista that is exactly I missed and I wondered about
