### ISSUE TITLE
Add support for ip igmp snooping querier per vlan

### ISSUE THREAD

**Issue by rainmanatee** [aristanetworks/ansible-avd#1502]
### Enhancement summary

For L2 EVPN multicast to function, it's required to enable ip igmp snooping querier on the vlan, along with a querier address, e.g. 

ip igmp snooping vlan 100 querier
ip igmp snooping vlan 100 querier address 10.10.10.10

Looking to add this support to eos_cli_config_gen and eos_designs.

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen

### Use case example

Since the ip igmp snooping querier functionality is defined outside of the vlan config, structure can be added similarly to the enable/disable capability which exists today;

ip_igmp_snooping:
  vlans:
    3501:
      querier:
        address: 10.10.10.10

Since the number of vlans can be high with the same requirement, this can be added to l2vlan config under tenant networks

      l2vlans:
        3501:
          name: Deadnet_3501
          tags: [ compute_leaf ]
          ip_igmp_snooping_querier:
            address: 10.0.0.1

Both can be accomplished with minor changes to the ip-igmp-snooping.j2 templates in both the eos_cli_config_gen and eos_designs modules. 

### Describe the solution you would like

As above would like the ability to configure ip igmp snooping querier and ip igmp snooping querier address via eos_cli_config_gen and eos_designs.  Sample j2 template for eos_cli_config_gen:

{# eos - IP IGMP Snooping #}
{% if ip_igmp_snooping.globally_enabled is arista.avd.defined(false) %}
!
no ip igmp snooping
{% elif ip_igmp_snooping.vlans is arista.avd.defined %}
!
{%     for vlan in ip_igmp_snooping.vlans | arista.avd.natural_sort %}
{%         if ip_igmp_snooping.vlans[vlan].enabled is arista.avd.defined(false) %}
no ip igmp snooping vlan {{ vlan }}
{# Begin changes to add querier #}
{%         endif %}
{%         if ip_igmp_snooping.vlans[vlan].querier is arista.avd.defined %}
ip igmp snooping vlan {{ vlan }} querier
{%         endif %}
{%         if ip_igmp_snooping.vlans[vlan].querier.address is arista.avd.defined %}
ip igmp snooping vlan {{ vlan }} querier address {{ ip_igmp_snooping.vlans[vlan].querier.address }}
{# End changes to add querier #}
{%         endif %}
{%     endfor %}
{% endif %}

And sample j2 template for eos_designs:

<snip>
{# ---------------------------- #}
{# L2VLANs services             #}
{# ---------------------------- #}
{%         for l2vlan in tenant.l2vlans %}
{%             if l2vlan.igmp_snooping_enabled is arista.avd.defined %}
    {{ l2vlan.id | int }}:
      enabled: {{ l2vlan.igmp_snooping_enabled }}
{%             endif %}
{# Begin Changes to add igmp snooping querier #}
{%             if l2vlan.ip_igmp_snooping_querier is arista.avd.defined %}
    {{ l2vlan.id | int }}:
      querier: 
{%               if l2vlan.ip_igmp_snooping_querier.address is arista.avd.defined %}
        address: {{ l2vlan.ip_igmp_snooping_querier.address }}
{%               endif %}
{%             endif %}
{# End changes to add igmp snooping querier #}
{%         endfor %}
{%     endfor %}
{% endif %}

### Describe alternatives you have considered

Have looked into using raw_eos_cli, however, this is a lot of raw CLI in a network with a large number of vlans.  Additionally, the l2vlans under tenants already supports ip_igmp_snooping_enabled to toggle support for igmp snooping per vlan defined in the tenants.  Adding support for querier and querier address in the tenants would seem natural.

### Additional context

This configuration is required for L2 EVPN multicast to work.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Solved in #1464 a few days ago.
