### ISSUE TITLE
Feat(eos_cli_config_gen): Add support for Management Defaults Secret Hash

### ISSUE THREAD

**Issue by xaviramon** [aristanetworks/ansible-avd#1508]
### Enhancement summary

Allow configuration of management defaults

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Allow selection of configuration to store passwords

### Describe the solution you would like

Define the data model and implement EOS templating

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Can you add some more details on this?

**Comment by xaviramon** [comment]
This option changes how passwords are stored in the device.
```
switch(config)#management defaults
switch(config-mgmt-defaults)#secret hash ?
  md5     MD5
  sha512  SHA-512
  ```
