### ISSUE TITLE
Optimize eos_config_deploy_cvp

### ISSUE THREAD

**Issue by noredistribution** [aristanetworks/ansible-avd#1544]
### Enhancement summary

create a v2 role for eos_config_deploy_cvp_v2 that runs tasks in parallel using `delegate_to` functionality instead of running things in series locally

### Which component of AVD is impacted

others

### Use case example

today it takes quite long to create/add/update configlets because it's done in series using the local machine,
at high scale this can cause 15+ minute playbook runtime or more

### Describe the solution you would like

Claus proposed using `delegate_to: cv_server` which looks promising

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
We have optimized a lot in arista.cvp collection which speeds up the overall deployment time. We will close this issue.
