### ISSUE TITLE
Feat(eos_cli_config_gen): Add interface documentation for PIM knobs

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#1562]
### Enhancement summary

Interface-level PIM and associated knobs are not covered in the generated markdown device documentation in eos_cli_config_gen.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

N/A

### Describe the solution you would like

N/A

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
@ClausHolbechArista just had a look at `eos_cli_config_gen` README and I can find the following documentation:
* ethernet interfaces: https://github.com/gmuloc/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md?plain=1#L974
* port-channels: https://github.com/gmuloc/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md?plain=1#L1421
* Vlan interface: https://github.com/gmuloc/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md?plain=1#L1498

to me it looks like we could close this issue but maybe you had noticed anything else?

**Comment by ClausHolbechArista** [comment]
The point of this issue is the generated markdown documentation. We could add a multicast section and have general multicast settings and interface specific settings under that.

**Comment by gmuloc** [comment]
Ah i see - I read it as update the read me but this is really update the documentation templates - my bad!

**Comment by ClausHolbechArista** [comment]
> Ah i see - I read it as update the read me but this is really update the documentation templates - my bad!

Not at all, the description was vague. I have updated it a bit, to make it less ambiguous.
