### ISSUE TITLE
Verify if all devices and ports defined in vars are present

### ISSUE THREAD

**Issue by ankudinov** [aristanetworks/ansible-avd#158]
**Issue Type**
- Role enhancement

**Is your feature request related to a problem? Please describe.**
Taking server group vars as an example here. adapters > switches will accept any name in the list.
`switches: ['DC1-LEAF1A', 'DC1-LEAF1B']` or `switches: ['DC1_LEAF1A', 'DC1_LEAF1B']` will be accepted without any error even if switches do not exist. That can cause problems, especially when servers provisioned manually.

**Describe the solution you'd like**
I'd propose creating an additional role that will compare defined vars with existing inventory and report error when there is a mismatch.
Initial focus should be on switch inventory and ports.

**Comment by ksator** [comment]
I like it, a lot. A role that kind of validate some of the inputs.
