### ISSUE TITLE
Remove BGP rendering on irrelevant nodes

### ISSUE THREAD

**Issue by emilarista** [aristanetworks/ansible-avd#1593]
There was a hack implemented in the mpls design PR to keep rendering BGP for irrelevant nodes such as spines in the isis-ibgp molecule example in order to make the merge non-breaking. This hack should be removed for 4.0. 

File: eos_designs/templates/facts/switch/switch.j2

```
{# Hack to make mpls PR non-breaking, adds empty bgp to igp topology spines #}
{%     elif switch_underlay_routing_protocol in ['isis', 'ospf'] and switch_evpn_role == 'none' and bgp_as is arista.avd.defined %}
  bgp_as: "{{ bgp_as }}"
{%     endif %}
```

**Comment by ClausHolbechArista** [comment]
@emilarista
