### ISSUE TITLE
Fix(eos_cli_config_gen): sflow destination ip order

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#1604]
### Issue Summary

I am really not sure what sort of sort EOS uses to sort the sflow destinations, but it does not match eos_cli_config_gen

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
sflow:
    destinations:
        127.0.0.1: {}
        192.22.100.20: {}
        192.22.225.191: {}
        192.25.212.70: {}
    run: true
    source_interface: Loopback0
```

Expected Output:
```eos
!
sflow destination 192.22.100.20
sflow destination 192.22.225.191
sflow destination 127.0.0.1
sflow destination 192.25.212.70
sflow source-interface Loopback0
sflow run
!
```

Actual Output:
```eos
!
sflow destination 127.0.0.1
sflow destination 192.22.100.20
sflow destination 192.22.225.191
sflow destination 192.25.212.70
sflow source-interface Loopback0
sflow run
!
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ryanmerolle** [comment]
I am not really sure how EOS sorts this output, maybe someone from Arista can advise.

**Comment by UchihaItachiSama** [comment]
Hey Ryan,

Latest EOS release trains use the sorted() function for sorting the sflow destination. In some EOS releases you might see random order in the CLI that's due to an [issue](https://www.arista.com/en/support/software-bug-portal/bugdetail?bug_id=612810) which has been fixed.

```yaml
#show version | inc Software
Software image version: 4.27.1.1F

switch(config)#sflow destination 192.22.100.20
switchconfig)#sflow destination 192.22.225.191
switch(config)#sflow destination 127.0.0.1
switch(config)#sflow destination 192.25.212.70

#show running-config section sflow
sflow destination 127.0.0.1
sflow destination 192.22.100.20
sflow destination 192.22.225.191
sflow destination 192.25.212.70

```
