### ISSUE TITLE
Add support for MSDP peer mesh groups (including non-default VRF)

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#1615]
### Enhancement summary

Add `router_msdp` knob to `eos_cli_config_gen` to support MSDP configurations for default and non-default VRFs in EOS devices.
As a minimal example, I need to cover the following config:

```yaml
router msdp
   vrf VRF1
      peer 1.2.3.4
         local-interface Loopback1
         mesh-group MSDP-VRF1
!
```

A more complete data model should follow The configuration guide: https://www.arista.com/en/um-eos/eos-multicast-source-discovery-protocol-msdp#xx1151283

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Need to configure MSDP mesh groups on a VRF

### Describe the solution you would like

See summary for the minimum required CLI. Ideally the data model should cover a more complete configuration based on the official MSDP configuration guide. 

### Describe alternatives you have considered

Using custom template to cover the requirement

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gusmb** [comment]
@ClausHolbechArista is it possible to reopen this issue? As part of the DCI deployment I need 9 render MSDP config, simple in my case based on the example given.

**Comment by ClausHolbechArista** [comment]
I need something similar (without VRF though) for a project, but it will be a while. Let me know if you will take this on, or if we should see if we can find a volunteer :)

**Comment by gusmb** [comment]
I could invest some time to implement the basics to cover the initial needs, but can't commit much time  till EOY. if we start to expose an MSDP Datamodel it would need to be extended to cover as much CLI as possible or at least most of the typical config scenarios. An additional volunteer would be nice :)

**Comment by emilarista** [comment]
I'm picking this one up. Aiming to implement complete coverage of the msdp configuration.
