### ISSUE TITLE
Fix(eos_designs): VLAN for iBGP peering in overlay VRFs is created when evpn_services_l2_only:true 

### ISSUE THREAD

**Issue by UchihaItachiSama** [aristanetworks/ansible-avd#1646]
### Issue Summary

When using `evpn_services_l2_only:true` for l2only l3leaf nodes, no VRF and SVI's are created as expected.

However, l2vlan for iBGP peering is also getting created.

```yaml
!
vlan 3009
   name MLAG_iBGP_Tenant_A_OP_Zone
   trunk group LEAF_PEER_L3
!
```

We should also be checking for `network_services_l3:false` under [`vlans.j2`](https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_designs/templates/network_services/vlans.j2) 

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Set `evpn_services_l2_only:true` for l2only l3leaf nodes.
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
@UchihaItachiSama we have a release coming up on Friday. It would be nice to get this fix included, so let me know if you need a hand to get this done before.

**Comment by UchihaItachiSama** [comment]
Hey Claus, sure would be happy to get some extra help on this one. I'll get started on this tomorrow morning.
