### ISSUE TITLE
Node key type was expected but not set 

### ISSUE THREAD

**Issue by Jayceehayden** [aristanetworks/ansible-avd#1684]
I am trying to create a new node and I keep getting a error saying they node key <key>.type was expected but not sit need to know what is causing this error. The node type is a border leaf, we have l3leafs connected to our endpoints which uplinks to spine and spines uplink to border leaves need guidance

**Comment by gmuloc** [comment]
Hello - thanks for reaching out. 

When using the `eos_designs` role, each device (host) needs to be assigned a `type` and this is missing in your case. This is documented here: https://avd.sh/en/stable/roles/eos_designs/doc/fabric-topology.html#node-type-variables. 

An example of assigning types to groups of nodes in the inventory: https://github.com/arista-netdevops-community/atd-avd/blob/master/atd-inventory/inventory.yml#L28

Another example, assigning types in the group_vars: https://github.com/arista-netdevops-community/avd-cEOS-Lab/blob/main/labs/evpn/avd_asym_irb/group_vars/DC1_SPINES.yaml / https://github.com/arista-netdevops-community/avd-cEOS-Lab/blob/main/labs/evpn/avd_asym_irb/group_vars/DC1_LEAFS.yaml

To be able to help you further it would be necessary to get a bit more context regarding your current setup - inventory file and group_vars
