### ISSUE TITLE
evpn_ethernet_segment configuration for esi and rt for port-channels

### ISSUE THREAD

**Issue by philippebureau** [aristanetworks/ansible-avd#1702]
### Issue Summary

evpn segment esi and rt configuration are at the port-channel root configuration indentation and not under evpn_ethernet_segment where it should be.

![image](https://user-images.githubusercontent.com/8918617/162518307-d110998a-c58e-4cd7-b49c-ef891480a8a1.png)

https://www.avd.sh/en/latest/roles/eos_cli_config_gen/index.html#port-channel-interfaces

The configuration is generated properly for EOS but the structure of the configuration does not make sense

For ethernet interface configuration, the configuration structure is correct
![image](https://user-images.githubusercontent.com/8918617/162518674-3c191ca9-9a14-42d9-8b36-38441bcb1b23.png)

Also both structure should use the same syntax.  it is currently  esi & rt for port-channels and identifier & route_target for ethernet

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Agreed. The `esi` and `rt` vars are historic, and was added before the `evpn_ethernet_segment` keys was there. We cannot do breaking changes to the data-models outside of major releases, so we can not remove the old keys before AVD 4.0.
I would not consider this a bug, but an enhancement to the datamodel, to make it simpler to consume.
For now we can add new keys under `evpn_ethernet_segment`, and default back to the old keys, to avoid breaking changes. Then we can deprecate the old keys in 4.0.

**Comment by philippebureau** [comment]
Makes total sense.  Thanks
