### ISSUE TITLE
Add support for the configuration of mlag primary-priority

### ISSUE THREAD

**Issue by morinpa** [aristanetworks/ansible-avd#1727]
### Enhancement summary

Add the capability of configuring the primary-priority on MLAG members. 
something like this: 

switch 1:
```
mlag configuration
   ...
   primary-priority 1
   ...
```

switch 2: 
```
mlag configuration
   ...
   primary-priority 9
   ...
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

We require the capability to hardcode which switch will be primary in the MLAG pair. 

### Describe the solution you would like

The solution should permit to configure this for an mlag pair and be able to do it fabric wide. 
something like this, maybe: 

```
mlag_configuration:
  primary_priority:
    primary: 1
    secondary: 9
```

by checking if the switch.mlag_role is arista.avd.defined('primary') you can then assign
primary-priority to be the value of mlag_configuration.primary_priority.primary else, assign
primary-priority to be the value of mlag_configuration.primary_priority.secondary

This might need to be further discussed. 

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
This configuration is hidden in EOS and discouraged from the developers according to my sources. We have considered this for AVD before, and decided not to implement it.
It would not be considered "best practice" to use this, and that is really what AVD is all about. We have `raw_eos_cli` in `eos_designs` to allow custom configuration to be implemented. We also support `custom_templates` to allow for customer specific jinja templates.
@carlbuchmann will reach out to you directly.

**Comment by carlbuchmann** [comment]
@morinpa, I will reach out to you and discuss further. Since we will not be implementing this, closing this issue.
