### ISSUE TITLE
Remove multiple L1 markdown headers in the eos_cli_config_gen device documentation templates

### ISSUE THREAD

**Issue by mkurjanski** [aristanetworks/ansible-avd#1748]
### Issue Summary

Hi, currently the device documentation templates contain multiple L1 (#) markdown headers. 

/arista/avd/roles/eos_cli_config_gen/templates)/eos-device-documentation.j2

We're trying to use mkdocs for publishing this documentation. The mkdocs assume there is only a single L1 markdown header allowed. The suggested fix would be to increase the header level by one in the templates. Replace all # with ##, replace ## with ### etc.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
To avoid changing this for all deployments, we could add a hidden tag in the documentation, to force mkdocs to ignore the two first entries at L1 ?

**Comment by gusmb** [comment]
In my project I also use one repo to generate configs and documentation for multiple sites and fabrics. I am using mkdocs to consolidate the generated documents and build the aggregated docs nicely in one interface. mkdocs with material theme automatically generates navigation lings with TOC on the right panel, however this feature is failing when the document has multiple top-level headers.

Would expect to see the headers as follows:

```
# Title
## Table of Contents
## Section1
### Sub-Section1
### Sub-Section2

## Section2
```

As a note, the rendering seemed correct on this demo for fabric:

https://github.com/arista-netdevops-community/ansible-avd-cloudvision-demo/blob/master/inventory/documentation/DC1_FABRIC/DC1_FABRIC.md?plain=1

But not for devices:

https://github.com/arista-netdevops-community/ansible-avd-cloudvision-demo/blob/master/inventory/documentation/devices/DC1-L2LEAF1A.md?plain=1

**Comment by gusmb** [comment]
Are there any plans to fix the headings to use only one global L1 header like suggested above?

**Comment by ClausHolbechArista** [comment]
Yes this on our (long) list of TODOs for AVD 4.0
