### ISSUE TITLE
Feat(eos_cli_config_gen): Add sflow to interfaces

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#1757]
### Enhancement summary

Allow setting sflow config on interfaces

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

EOS allows setting some sflow config on interfaces.  This is missing from the current model

### Describe the solution you would like

TBD

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by UchihaItachiSama** [comment]
so following interface (Ethernet and port-channel) level Sflow configurations are available.
```shell
sflow enable
sflow egress enable
```

possible model
```shell
ethernet_interfaces:
    <Ethernet_interface_1 >:
        sflow:
            enabled: <true | false>
            egress:
                enabled: <true | false>
```

**Comment by ClausHolbechArista** [comment]
on my test platform (VEOS 4.27.2F) I have:
```
sflow enable
sflow egress unmodified enable
```

**Comment by UchihaItachiSama** [comment]
looks like there are two different command sets based on the platform

https://www.arista.com/en/support/toi/eos-4-24-2f/14579-support-for-software-egress-sflow --> `sflow egress enable`

https://www.arista.com/en/support/toi/eos-4-25-1f/14637-egress-sflow --> `sflow egress unmodified enable`

**Comment by UchihaItachiSama** [comment]
so do we update the data model as:

```shell
ethernet_interfaces:
  <Ethernet_interface_1 >:
    sflow:
      enabled: < true | false >
      egress:
        unmodified: < true | false >
        enabled: < true | false >
```
