### ISSUE TITLE
Prevent maintaining same Jinja2 templates twice

### ISSUE THREAD

**Issue by mpergament** [aristanetworks/ansible-avd#179]
**Issue Type**

- Template enhancement

As of now templates are duplicated (with minor changes) in https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates

Would it not be better to have single j2 templates where additional documentation statements are rendered based on specific flag. As of now any change needs to be implemented twice (under eos and documentation).

**Comment by carlbuchmann** [comment]
@mpergament I feel like combining them would make them more cluttered. And in general, these templates are quite different. eos templates generate the eos configuration, and the documentation templates create table(s) to represent the configuration. The logic is not the same.

Take for example route-bgp template, IMHO combining them would make it larger and harder to maintain.
eos: https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/router-bgp.j2

documentation: https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/router-bgp.j2


@aphillipps, any thoughts as you have been a major contributor to the eos_cli_config_gen role?

**Comment by mpergament** [comment]
Hi Carl, i understand they have a different roles but doc template is 100% dependent on config template. I guess what will happen with the time that config template will be updated but doc one will be not. They will deviate with the time causing confusion. So perhaps we can find a smart way to have root jinja2 template only once (and not twice). Just my 2c.

**Comment by aphillipps** [comment]
Michael,

I understand what you are saying about keeping the documentation in sync
with the configuration templates. But I think that it is the role of the
AVD maintainers to make sure everything stays consistent and synchronized.
Merging the 2 templates in one will make these templates too long and thus
more difficult to read, troubleshoot and update. Today, when there is an
error in the templates, you know right away if it is in the documentation
or the configuration when you execute the playbook which comes really handy
for troubleshooting. The fewer lines, the faster you spot the issue.
Moreover some customers customize our templates and some could choose to
only customize the documentation part to reflect the company policy and the
structure they want for their documentation.
I think that keeping them seperate brings more benefits and it makes them
more versatile even though that means that we must pay attention to
synchronizing them.
