### ISSUE TITLE
Update version to v3 in eos_config_deploy_cvp role

### ISSUE THREAD

**Issue by sugetha24** [aristanetworks/ansible-avd#1796]
### Enhancement summary

`cv_collection` version needs to be updated to `v3` in main.yml in `eos_config_deploy_cvp/defaults/main.yml` 

### Which component of AVD is impacted

eos_config_deploy_cvp

### Use case example

please detail your use case

### Describe the solution you would like

change line 
`cv_collection: v1` to 
`cv_collection: v3` 
in `https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_config_deploy_cvp/defaults/main.yml`

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
We need to ensure (test) that all features of eos_config_deploy_cvp works 1:1 with that change.
