### ISSUE TITLE
Ability to use different ip address for ibgp peering in non default vrf 

### ISSUE THREAD

**Issue by vyelpale** [aristanetworks/ansible-avd#1797]
### Enhancement summary

AVD today defaults to using mlag_peer_l3_ipv4_pool to create the bgp peering. 
In the vxlan EVPN environment, ibgp peering created over the SVI in a non default vrf requires the ability to use different ip address across different vrfs. 

### Which component of AVD is impacted

eos_designs

### Use case example

VXLAN evpn deployment which is acting as aggregation for the different routes for running the overlay SDWAN solution. 
Although reusing the ip addressing across different vrfs should work, customer prefers to use different ip addressing for the ibgp peering vlans.

### Describe the solution you would like

1. SVI creation with custom ip pool
2. iBGP Peering configured using the ip address in the /31 subnet assigned to the SVI created in step 1
3. IBGP peer activation in address family IPv4 for that non default vrf where ibgp peering is created
4. Ability to assign it to different peer group (by default ibgp peer is getting assigned to peer group MLAG-IPv4-UNDERLAY-PEER)

### Describe alternatives you have considered

Nothing found yet.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by vyelpale** [comment]
Currently the SVI creation for non default vrf to use different ip address is being done using custom_structured_configuration_vlan_interfaces

**Comment by ClausHolbechArista** [comment]
Could be addressed with a new `mlag_ibgp_peering_ipv4_pool` under `tenants.<>.vrfs.<>` to be consistent with the var naming in that context.
