### ISSUE TITLE
Feat(eos_cli_config_gen): add support for BGP asdot/asplain notation

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#1832]
### Enhancement summary

AVD renders the BGP ASN today in the format input by the user.
If the ASN 65000.65000 is used, AVD renders: 
```
router bgp 65000.65000
```

This differs from eos.
```
router bgp 65000.65000

sho run sec bgp
router bgp 4259905000
```

To have the outputs consistent, we need to configure:
```
router bgp 65000.65000
bgp as notation asdot 
```

```
router bgp 65000.65000
   bgp asn notation asdot
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

context may be provided by the asdot values selected, such as a site or use code, which is lost in the asplain representation.

### Describe the solution you would like

Implement a new key:

`bgp_asn_notation: < asplain | asdot | default -> asplain >`

Implement an asdot and asplain filter.

apply the appropriate filter to the asn based on the value of the new key.

render the `bgp asn notation asdot` line if so configured. 

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Good catch! And after implementing this in `eos_cli_config_gen` we should also auto-detect this in `eos_designs` under `templates/base/router_bgp`.

**Comment by pvinci-arista** [comment]
This should better be implemented as a new property of eos_design_facts, do you agree?

**Comment by ClausHolbechArista** [comment]
It depends a bit. I see two options:
1. Implement the new `eos_designs` key `bgp_asn_notation` which will convert the input ASN into the configured format, and set the "structured_config" with the converted ASN and the `eos_cli_config_gen` key `bgp_asn_notation` as required.

2. Read the given `bgp_as` and in "structured_config" set the `eos_cli_config_gen` key `bgp_asn_notation` accordingly.

I was thinking option 2, but re-reading your issue, it seems like you are thinking option 1.
If we convert the fact, we need to also take into account, that this ASN fact is used on remote peers as well. So how should they print out `remote_as` ?

**Comment by rich9474** [comment]
I would very much like to be able to set the `bgp as notation asdot` across my fabric.  I find it a much more intuitive way to display the ASN, and also enables me to set the first two bytes as the Site AS, and the second 2 Bytes as the rack AS.  Is there any way to set it presently, or would it require a change?

**Comment by nathanmusser** [comment]
> * Implement the new `eos_designs` key `bgp_asn_notation` which will convert the input ASN into the configured format, and set the "structured_config" with the converted ASN and the `eos_cli_config_gen` key `bgp_asn_notation` as required.
> * Read the given `bgp_as` and in "structured_config" set the `eos_cli_config_gen` key `bgp_asn_notation` accordingly.

A 3rd option that's a hybrid of the two above would be to implement a key `bgp_asn_notation` with 3 possible values. `asdot` and `asplain` would simply control the presence of `bgp asn notation <format>` in the config. With no logic to auto-convert ASNs into the specified notation. A 3rd value of `auto` (which could be the default value) would parse the switches own AS number and use it to determine the notation. 

I have a working branch with the `bgp_asn_notation` key working for the values of `asdot` and `asplain`. I'm working on reading through the style and contribution guides to clean it up for a PR. And I don't mind adding the `auto` option logic or changing how it's done. I am hesitant to get into too much logic trying to parse or convert ASNs beyond the switches own AS number in the config though. There is too much potential for there to be mixed notation making it hard to be consistent.

**Comment by ClausHolbechArista** [comment]
Hi Nathan

Thank you for working on this. Can I assign this issue to you?

Feel free to submit the PR as draft as-is, so we have something to discuss from. We can help you get it to the finish line, since we are aware our contribution guide is not up to date.

Maybe you are already aware, but if our PR is for `eos_cli_config_gen` we will _not_ do any `auto` option or any logic at all. `eos_cli_config_gen` should just be "translating" from the "structured config" into EOS CLI with no abstraction or logic.

Any logic like auto converting or even auto identifying the ASN should be done in `eos_designs`. To avoid the change being "breaking" for existing deployments, I think we need to keep the default setting "unset" (`None`), where we won't do anything.

Loooking forward to seeing your contribution!

BR
Claus

**Comment by nathanmusser** [comment]
Thanks for the comments Claus. I'll push a draft PR this afternoon and we can go from there. I'm sure it'll need some work to bring it inline with the codebase methodology. Feel free to assign this to me as well.

**Comment by colinmacgiolla** [comment]
For the initial implementation, I'm thinking asdot or asplain, and worry about auto assignment later
