### ISSUE TITLE
Feat(eos_cli_config_gen): Add support for disabling ipv4 unicast as the default mode for BGP

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#1839]
### Enhancement summary

Add support for ipv4_unicast_default key under bgp.

```
bgp:
  ipv4_unicast_default: < true | false | default -> true >
```

to control rendering:

```
router bgp 1
   no bgp default ipv4-unicast
!
end
``` 

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

please detail your use case

### Describe the solution you would like

Render the cli from a distinct key in the model.

### Describe alternatives you have considered

This is currently supported with the the addition of a cli line under the bgp_defaults key.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by tgodaA** [comment]
This can be achieved with `bgp_defaults`

<img width="321" alt="image" src="https://user-images.githubusercontent.com/88734745/207665706-feadf53b-4235-4b65-982a-3e2d9e9921d8.png">

Add the command directly under this hood. Meanwhile I will add the feature.

**Comment by pvinci-arista** [comment]
Thanks!

Yes! I do that today to render the config, and it works great!  The reason a key is valuable is that I don't have to walk the list to understand the intent of the configuration when trying to validate the configs.

**Comment by gmuloc** [comment]
Note that implementing this would need to add some modification in some of the BGP overlay  logic where we explicitly disable some peer-groups in ipv4 address family which will be useless with this turned on.

**Comment by tgodaA** [comment]
Closing this request because this is achieved through `bgp_defaults` key.

**Comment by ClausHolbechArista** [comment]
Will be addressed by https://github.com/aristanetworks/ansible-avd/pull/2799
