### ISSUE TITLE
Feat(eos_designs): support for 7300X platform

### ISSUE THREAD

**Issue by markcheverton** [aristanetworks/ansible-avd#1860]
### Enhancement summary

Please add Platform 7300X3 to the EOS_Designs - default platform_settings: 

We are using these devices as Spines therefore require the management_interface: Management0 defined however don't require MLAG reload timers.

### Which component of AVD is impacted

eos_designs

### Use case example

Using 7308X3 as Spine in AVD

### Describe the solution you would like

```
platform_settings:
  - platforms: [ '7300X3' ]
    management_interface: Management0
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by tgodaA** [comment]
Currently AVD supports custom platform settings. So you can set them in the group vars. Example reference:
https://avd.sh/en/devel/roles/eos_designs/doc/platform-settings.html
