### ISSUE TITLE
Fix: AVD version print in all roles

### ISSUE THREAD

**Issue by tgodaA** [aristanetworks/ansible-avd#1874]
### Issue Summary

Currently the AVD version is printed properly but in some virtual environments this errors out as the ansible-galaxy doesn't load the collection_path properly, even if the collection_path is defined in the ansible.cfg file.

Don't know why this happens in few virtual environments.

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Relevant log output

```shell
msg: 'An unhandled exception occurred while templating ''{{ versions[collection_path][ansible_collection_name].version | default(''Unknown'') }}''. Error was a <class ''ansible.errors.AnsibleError''>, original message: An unhandled exception occurred while templating ''{{ lookup(''pipe'', ''ansible-galaxy collection list --format yaml '' ~ ansible_collection_name) | from_yaml }}''. Error was a <class ''ansible.errors.AnsibleError''>, original message: An unhandled exception occurred while running the lookup plugin ''pipe''. Error was a <class ''ansible.errors.AnsibleError''>, original message: lookup_plugin.pipe(ansible-galaxy collection list --format yaml arista.avd) returned 5. lookup_plugin.pipe(ansible-galaxy collection list --format yaml arista.avd) returned 5'
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
Hey @tgodaA regarding this issue - have you identified the root cause behind ansible-galaxy not finding the collection in virtual envs?

**Comment by ClausHolbechArista** [comment]
I think we need to root cause the problem, instead of just working around it, since the work around defeats the core purpose of the version printout. If ansible tools cannot pick up the correct path, that is exactly the issue we wish to catch.
