### ISSUE TITLE
Add ability to add structured_config under router_bgp.vlans.<vlan> from Tenant Networks SVIs/L2VLANs data model

### ISSUE THREAD

**Issue by lermilov** [aristanetworks/ansible-avd#1889]
### Enhancement summary

Add bgp.structured_config for Tenant Networks SVIs/L2VLANs same as it is supported for IP VRFs.

Supported now:
  < tenant_a >:
    vrfs:
      < tenant_a_vrf_1 >:
        bgp:
          # EOS CLI rendered directly on the Router BGP, VRF definition in the final EOS configuration
          raw_eos_cli: |
            < multiline eos cli >
          # Custom structured config added under router_bgp.vrfs.<vrf> for eos_cli_config_gen
          structured_config: < dictionary >

Request to support:
  < tenant_a >:
    vrfs:
      < tenant_a_vrf_1 >:
        svis:
           <svi>:
               bgp:
                  # EOS CLI rendered directly on the Router BGP, VLAN definition in the final EOS configuration
                  raw_eos_cli: |
                    < multiline eos cli >
                  # Custom structured config added under router_bgp.vlans.<vlan> for eos_cli_config_gen
                  structured_config: < dictionary >

### Which component of AVD is impacted

eos_designs

### Use case example

Configure Asymmetric EVPN MAC-VRF with "with no redistribute host-route from Tenant Networks data model.
  < tenant_a >:
    vrfs:
      < tenant_a_vrf_1 >:
        svis:
           <svi>:
               bgp:
                  # EOS CLI rendered directly on the Router BGP, VLAN definition in the final EOS configuration
                  raw_eos_cli: |
                    < multiline eos cli >
                  # Custom structured config added under router_bgp.vlans.<vlan> for eos_cli_config_gen
                  structured_config: < dictionary >

### Describe the solution you would like

  < tenant_a >:
    vrfs:
      < tenant_a_vrf_1 >:
        svis:
           <svi>:
               bgp:
                  # EOS CLI rendered directly on the Router BGP, VLAN definition in the final EOS configuration
                  raw_eos_cli: |
                    < multiline eos cli >
                  # Custom structured config added under router_bgp.vlans.<vlan> for eos_cli_config_gen
                  structured_config: < dictionary >

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by tgodaA** [comment]
Completed in  #1947
