### ISSUE TITLE
router_ospf.j2 generates incorrect interface configuration

### ISSUE THREAD

**Issue by markcrobinson** [aristanetworks/ansible-avd#1892]
### Issue Summary

Using the ospf and l3_interfaces for multiple switches in the same site to generate OSPF configuration results in the wrong interfaces being assigned to router_ospf on the switches.

This is caused by the incorrect use of arista.avd.natural_sort in [router-ospf.j2#L21](https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_designs/templates/network_services/router-ospf.j2#L21)

As per the docs, the three lists interfaces, ip_addresses and nodes must be populated in consistent order. The above only sorts nodes, which results in incorrect indexing of the interfaces list when generating the router_ospf YaML. Removing the sort fixes the issue

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Input YaML:

        ospf:
          enabled: true
          nodes:
          - LEAF3A
          - LEAF3B
        l3_interfaces:
        - interfaces:
          - Ethernet4
          - Ethernet6
          - Ethernet5
          ip_addresses:
          - 9.9.9.1/30
          - 9.9.9.5/30
          - 9.9.9.13/30
          nodes:
          - LEAF3A
          - LEAF3B
          - LEAF3A
          ospf:
            enabled: true
            point_to_point: true
            area: 0

Resulting structured_config for LEAF3A:
router_ospf:
  process_ids:
    1:
      vrf: Tenant_A_OP_Zone
      ...
      no_passive_interfaces:
      - Ethernet4
      - Ethernet6
      redistribute:
      ...

Resulting structured_config for LEAF3B:
router_ospf:
  process_ids:
    1:
      vrf: Tenant_A_OP_Zone
      ...
      no_passive_interfaces:
      - Ethernet5
      redistribute:
      ...
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Thank you for reporting and identifying the root cause. We will work on a fix asap.

**Comment by markcrobinson** [comment]
This is the fix that works for me:

diff --git a/router-ospf.j2.bak b/router-ospf.j2
index 351e17b..638a50b 100644
--- a/router-ospf.j2.bak
+++ b/router-ospf.j2
@@ -18,7 +18,7 @@ router_ospf:
 {%                 set ospf_router_id = vrf.ospf.router_id | arista.avd.default(switch.router_id) %}
 {%                 for l3_interface in vrf.l3_interfaces | arista.avd.natural_sort %}
 {%                     if inventory_hostname in l3_interface.nodes | arista.avd.default([inventory_hostname]) and l3_interface.interfaces is arista.avd.defined and l3_interface.ospf.enabled is arista.avd.defined(true) %}
-{%                         for node in l3_interface.nodes | arista.avd.natural_sort %}
+{%                         for node in l3_interface.nodes %}
 {%                             if node == inventory_hostname %}
 {%                                 do vrf_ospf_interfaces.append(l3_interface.interfaces[loop.index0]) %}
 {%                             endif %}
