### ISSUE TITLE
Add switchport default to eos_cli_config_gen

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#196]
**Issue Type**
- Template enhancement

**Is your feature request related to a problem? Please describe.**
Cannot set the `switchport default mode routed` command on an eos device which is useful for edge peering to third parties.

**Describe the solution you'd like**
Add a new template for switchport default.  Data model & template should probably allow for other features to be added as needed like the various `switchport default mode phone commands`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by carlbuchmann** [comment]
Reviewing this request, and insuring this can easily work in config replace model

**Comment by titom73** [comment]
Fixed by PR #558
