### ISSUE TITLE
Document updates to development guide

### ISSUE THREAD

**Issue by JulioPDX** [aristanetworks/ansible-avd#1965]
### Issue Summary

Add updates (Flake8) to additional pre commits. 

### Which component(s) of AVD impacted

others

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
N/A
```

### Relevant log output

```shell
N/A
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Please also remove the duplicate/overlapping contribution doc
- `ansible_collections/arista/avd/docs/contributing.md`
- `ansible_collections/arista/avd/docs/contribution/`

**Comment by JulioPDX** [comment]
WIP, going to submit a PR for this issue shortly
