### ISSUE TITLE
Default VRF needs to be added to name-server config in eos_cli_config_gen 

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#199]
## Issue Type
- EOS Configuration error

## Summary

Currently, if a name-server host is set in eos_cli_config_gen, and the vrf associated is default, the config generated removes the vrf name from the generated config.  At least with EOS 4.22.6M this is not the standard behavior.  It will take the command, but EOS will automatically convert to list the vrf in the command.

## Role or Module Name

eos_cli_config_gen 

## OS / Environment

__EOS Version__

4.22.6M

__Cloudvision version__

2020.1.1

__OS running Ansible__

2.9.11

## Steps to reproduce

```yaml
name_server:
  source:
    vrf: default
  nodes:
    - 192.168.0.1
```

### Expected results

```shell
ip name-server vrf default 192.168.0.1
```

### Actual results

```shell
ip name-server 192.168.0.1
```

**Comment by aphillipps** [comment]
Thanks for the information. The fix will be implemented in v1.1.0 release.
