### ISSUE TITLE
Feat(eos_designs): Add support for Terminattr token/cert based auth

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#2025]
### Enhancement summary

Today we support only key-based auth for Terminattr towards on-prem.
For CVaaS we support token.

Since this will be breaking we cannot change the default behavior in 3.x, but we should definitely use token by default from AVD 4.x. For now we will need to have a knob.

### Which component of AVD is impacted

eos_designs

### Use case example

Newer releases of CVP will only support token.

### Describe the solution you would like

N/A

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by carlbuchmann** [comment]
Raised by @adietrich-ussignal
