### ISSUE TITLE
Connected Endpoint Documentation

### ISSUE THREAD

**Issue by markcheverton** [aristanetworks/ansible-avd#2043]
### Enhancement summary

Connected endpoints are defined under keys - "servers", "firewalls", "routers", "load_balancers" and "storage_arrays" - request .md files are created under fabric documentation folder per endpoint key to document where these devices are connected to fabric along with configuration (port description, speed, vlan's, trunk/access etc..)

### Which component of AVD is impacted

eos_designs

### Use case example

Documentation of fabric

### Describe the solution you would like

Connected endpoints are defined under keys - "servers", "firewalls", "routers", "load_balancers" and "storage_arrays" - request .md files are created under fabric documentation folder per endpoint key to document where these devices are connected to fabric along with configuration (port description, speed, vlan's, trunk/access etc..)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by carlbuchmann** [comment]
@markcheverton - Thanks for submitting this issue, this is a great idea and an area we want to enhance moving forward! Are you interested in helping with the development? If yes, we are happy to get on a zoom call and show you the process. We also have a private slack channel we can use to communicate.

**Comment by markcheverton** [comment]
Apologies for delay in responding - I am more than happy to discuss this further with you on what we see on our implementation, what we'd like to see and work with you to develop this. 
I can schedule a zoom call with yourself and our Arista System Engineer (Sean Flack) to discuss further?

**Comment by carlbuchmann** [comment]
@markcheverton, no worries, that would be great! Let’s schedule a call for the week of October 24th with @perimore and @gmuloc.
Note that this work will only be able to begin once we have completed refactoring of eos_designs to python, which is currently underway - but it would be useful to discuss design with you and brainstorm the approach we would like to take!

**Comment by markcheverton** [comment]
@carlbuchmann, w/c October 24th works well for me.  @gmuloc is working with HSBC as part of PS therefore is familiar with our setup and what we're trying to achieve with AVD so that's great to include him.  
Look forward to speaking to you in order discuss further.
