### ISSUE TITLE
ipv6_address_virtual_secondaries is defined in eos_designs role but not in eos_cli_config_gen

### ISSUE THREAD

**Issue by melkypie** [aristanetworks/ansible-avd#2087]
### Issue Summary

#1760 Added support for ipv6_address_virtual_secondaries in eos_designs but did not take into account that it was not defined in `eos_cli_config_gen`. This bug can be seen in `eos_designs_unit_tests` molecule very well where the knob is defined but the generated eos config does not have the command defined:  
https://github.com/aristanetworks/ansible-avd/blob/1869274cbcdd98e1f2689aea771a1da17703412c/ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/DC1_TENANTS_NETWORKS/Tenant_D.yml#L8-L17
https://github.com/aristanetworks/ansible-avd/blob/970908095a544986fe8a1c1d91017ab8e116e63b/ansible_collections/arista/avd/molecule/eos_designs_unit_tests/intended/structured_configs/DC1-LEAF2A.yml#L825-L836
https://github.com/aristanetworks/ansible-avd/blob/1869274cbcdd98e1f2689aea771a1da17703412c/ansible_collections/arista/avd/molecule/eos_designs_unit_tests/intended/configs/DC1-LEAF2A.cfg#L477-L482

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
We have checked in a few lab devices, and it seems like we implemented this by mistake in `eos_designs`, since it is not even supported in EOS. So the "fix" here will be to remove the keys from `eos_designs`. I also caught an issue with `ipv6_virtual_router_addresses`, where the values can only be without mask.

**Comment by ClausHolbechArista** [comment]
Checked again, and EOS accepts multiple `ipv6 address virtual` commands without the `secondary` keyword, so we will fix this.
