### ISSUE TITLE
Logging buffered default level

### ISSUE THREAD

**Issue by doxuanquang** [aristanetworks/ansible-avd#2169]
### eos_cli_config_gen is generating configuration differently from actual device's running config
eos_cli_config_gen ignores "logging buffered <size>" command if level is not defined, like in below structured config:
```
logging:
  buffered:
    size: 64000
```
In fact, when we enter "logging buffered <size>" to eos cli, default level of "debugging" is implied and the device understands

On the other hand, if we specify level as "debugging", like below structured config, eos_cli_config_gen generate full commands "logging buffered \<size\> debugging", whilst actual device running config only shows "logging buffered \<size\>" and the default level is implied:
```
logging:
  buffered:
    size: 64000
    level: debugging
```

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Generate platform config with below structured config using eos_cli_config_gen
logging:
  buffered:
    size: 64000

or 
logging:
  buffered:
    size: 64000
    level: debugging
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Hi, just to be clear, we do not intend to generate a configuration that matches the running config 100%. We prefer to be declarative instead of relying on implicit EOS behavior.
We will discuss this and get back on how we will proceed.
