### ISSUE TITLE
ntp authentication_keys not applied with the right type

### ISSUE THREAD

**Issue by BouchardClaude** [aristanetworks/ansible-avd#2211]
### Issue Summary

When using config_gen for ntp authentification, the type 7 key provided in the yml is applied as a plaintext key in the generated config. It look like the template is misisng the "7" type in the generated text.
**
![image](https://user-images.githubusercontent.com/22671885/197252539-c04c0bc4-a3df-47c6-a248-ea3f9c850d22.png)
**

will trigger the ntp [template](https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/ntp.j2):  
but the jinja template is missing the type 7 setting, making the key viewed as a plaintext key instead of a type 7 by the switch.

![image](https://user-images.githubusercontent.com/22671885/197253099-38ea5fc0-286f-46c6-9972-8a6c9966d207.png)

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible AWX

### Steps to reproduce

```shell
In config_gen, configure NTP with authentification. make sure to set the key parameter and the authenticate to true.

Generate the config

You can obesrve that the configlet generated put the key as a plaintext key instead of a type 7, making the ntp not working properly
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by carlbuchmann** [comment]
@BouchardClaude - thanks for raising this issue, I will investigate with @philippebureau

**Comment by philippebureau** [comment]
working on this in https://github.com/aristanetworks/ansible-avd/pull/2258
