### ISSUE TITLE
Sflow polling-interval in eos_cli_config_gen

### ISSUE THREAD

**Issue by doxuanquang** [aristanetworks/ansible-avd#2226]
### Enhancement summary

"polling-interval <sescond>" is not yet supported by eos_cli_config_gen

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

We want to be able to generate this configuration line: "sflow polling-interval 10"

### Describe the solution you would like

A simple "polling-interval: <second>" key-value pair to be added to sflow section

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Fixed by #2249
