### ISSUE TITLE
Bug: Schemas(management_security. ssl_profiles[x].tls_versions) can be a float type as well

### ISSUE THREAD

**Issue by tgodaA** [aristanetworks/ansible-avd#2237]
### Issue Summary

management_security. ssl_profiles[x].tls_versions can be either str or float. Although the provided input is correct the schema was raising warnings because float type was missed in the supported types.

Also, the description should have info that the values can be float or a string (space separated values)

<img width="209" alt="image" src="https://user-images.githubusercontent.com/88734745/198710714-58f8a6ba-0c75-4b80-8ee0-bff268d94103.png">

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
management_security:
  ssl_profiles:
    - name: test_profile
      tls_versions: 1.2


The above data-model is a valid one, which is similar to the below.

```yaml
management_security:
  ssl_profiles:
    - name: test_profile
      tls_versions: "1.2"
```
```


### Relevant log output

_No response_

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Currently the schema does not support auto conversion from float to string. The schema says clearly that this is `List of allowed TLS versions as string`.
So to support your ask, we need to add type conversion of `float` to `str`.

**Comment by ClausHolbechArista** [comment]
Draft PR: https://github.com/aristanetworks/ansible-avd/pull/2244

Is this enough to make it clear or do we really need the float conversion?

**Comment by tgodaA** [comment]
So, the customer will see the warnings when it is float. And the value is a string with space separated values. So when we give just one value, it is considered a float (because of yaml), unless if there are quotes.

**Comment by gmuloc** [comment]
Adding to this we could add a `pattern` for the string in the schema while revisiting this to check that it is a space separated list of "float like" strings

**Comment by ClausHolbechArista** [comment]
@gmuloc I will hold back on the pattern, since we need to enhance that feature in the schemas first. But I added examples in #2247 to make it more clear. I also added automatic type-conversion from `float` to `str`.
