### ISSUE TITLE
Disable username admin

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#2254]
### Enhancement summary

It is common to disable the admin username. In my case I create and use other default admin accounts.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Need to render the following command:

`no username admin `

### Describe the solution you would like

A way to do this in the users data model:

```yaml
local_users:
  < user_1 >:
    disabled: true
``` 

### Describe alternatives you have considered

I currently use the eos_cli key to do it and it gets rendered at the end of the config. For some reason CVP doesn't like it in some cases.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Hi Gustavo
You caught me at the right moment, so I have implemented this feature in #2256. I have added molecule test to demonstrate the behavior, but if you could test it out as well and review the PR, I would appreciate it.
Thanks
Claus
