### ISSUE TITLE
Add custom comments at the top of the rendered configuration

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#2271]
### Enhancement summary

Opening issue to discuss the option to include custom comments at the top of the generated config. Example:

```
!RANCID-CONTENT-TYPE: arista
!
! Config version: x.x.x
!
daemon attr
...
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

It is common to use the rendered config from `eos_cli_config_gen` as tje design configlet in CVP. Sometimes we want to include comments that add information about the configlet such as a generated version or a change ticket, which helps Ops to trace back to the source of the change. This comment section can also be used to force CVP to create a task and reapply a configlet (with no deltas) if we need to do that.

### Describe the solution you would like

a new `header_comments` knob or similar that would allow to add comments at the beginning of the rendered config.

Example:

```yaml
header_comments:
  - "Config version: XXX"
  - "Change ticket: XXXXX"
  - |
    some extra long text
   in multiple lines
```

Would render:

```
!RANCID-CONTENT-TYPE: arista
!
! Config version: XXX
! Change ticket: XXXXX
! some extra long text
! in multiple lines
!
daemon attr
...
```

### Describe alternatives you have considered

Render this information with `eos_cli` or with a custom template, however it gets rendered at the end, not too intuitive if you have to scroll all the way down to see that info

### Additional context

Although comments don't get pushed to the devices, comments in designed configlets for different config section can give some good context about some parts of the config, for those who look at the configlets in CVP.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Would it be useful to use the EOS command `comment` so the comments will be part of the running config?

**Comment by gusmb** [comment]
> Would it be useful to use the EOS command `comment` so the comments will be part of the running config?

That would be also useful for most of the configuration sections where this is supported. However `comment` command cannot be used to add a general comment at the top if I'm not mistaken
