### ISSUE TITLE
Improve description format and options

### ISSUE THREAD

**Issue by paullavelle** [aristanetworks/ansible-avd#2321]
### Enhancement summary

As of AVD v3.7.0 we have inconsistent and non-configurable description formats. For example:

```
[root@localhost configs]# cat p1-l1.cfg | grep description
   description MLAG_PEER_p1-l2_Po4
   description P2P_LINK_TO_P1-S1_Ethernet5
   description P2P_LINK_TO_P1-S2_Ethernet5
   description MLAG_PEER_p1-l2_Ethernet4
   description EVPN_Overlay_Peering
   description VTEP_VXLAN_Tunnel_Source
   description VRF10_VTEP_DIAGNOSTICS
   description VRF11_VTEP_DIAGNOSTICS
   description oob_management
   description VRF10_VLAN11
   description VRF10_VLAN12
   description VRF11_VLAN21
   description VRF11_VLAN22
   description MLAG_PEER_L3_iBGP: vrf VRF10
   description MLAG_PEER_L3_iBGP: vrf VRF11
   description MLAG_PEER_L3_PEERING
   description MLAG_PEER
   description p1-l1_VTEP
   neighbor MLAG-IPv4-UNDERLAY-PEER description p1-l2
   neighbor 10.2.0.1 description p1-l2
   neighbor 172.16.101.1 description p1-s1
   neighbor 172.16.101.2 description p1-s2
   neighbor 172.16.103.0 description p1-s1_Ethernet5
   neighbor 172.16.103.2 description p1-s2_Ethernet5
```

This feature enhancement is to allow users to set their own description formats.

The AVD defaults should also be consistent (e.g. all upper case with underscores), for example:

```
point_to_point_interface_description:		P2P_LINK_TO_{{ link.peer | upper }}_{{ link.peer_interface }}
evpn_loopback_interface_description:		EVPN_PEERING_SOURCE
vtep_loopback_interface_description:		VXLAN_SOURCE
oob_management_interface_description:		OOB_MANAGEMENT
bgp_neighbor_description:			{{ neighbor | upper }}
```

### Which component of AVD is impacted

eos_designs

### Use case example

Applies to all eos_designs templates.

### Describe the solution you would like

User-configurable description formats with consistent defaults (e.g. all upper case with underscores).

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by carlbuchmann** [comment]
@paullavelle thank you for submitting this issue.

There are two parts to this:
1. Make all names/descriptions configurable (not breaking)
2. Align defaults (breaking)

We can takle 1 in AVD 4.1+ and 2 in AVD 5.0
