### ISSUE TITLE
SSL: SSLV3_ALERT_HANDSHAKE_FAILURE]

### ISSUE THREAD

**Issue by theotherguy2175** [aristanetworks/ansible-avd#2337]
### Issue Summary

When running the deploy.yml from one of the example AVD projects I get the error from the title above. 

This could be something on my client. But I was able to get this to be bypassed once by changing the ansible_httpapi_use_ssl to false but AVD overwrites the switches config to not use http (which I would also prefer).

But is this something with my WSL client not able to use the self-assigned cert / SSLv3?

### How do you run AVD ?

Ansible CLI with AVD Runner

### Relevant log output

```shell
fatal: [SPINE1]: FAILED! => {"changed": false, "module_stderr": "Could not connect to https://10.0.60.11:443/command-api: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"}
fatal: [LEAF1]: FAILED! => {"changed": false, "module_stderr": "Could not connect to https://10.0.60.12:443/command-api: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"}
fatal: [SPINE2]: FAILED! => {"changed": false, "module_stderr": "Could not connect to https://10.0.60.13:443/command-api: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"}
fatal: [LEAF2]: FAILED! => {"changed": false, "module_stderr": "Could not connect to https://10.0.60.14:443/command-api: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"}
fatal: [LEAF3]: FAILED! => {"changed": false, "module_stderr": "Could not connect to https://10.0.60.15:443/command-api: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"}
fatal: [LEAF4]: FAILED! => {"changed": false, "module_stderr": "Could not connect to https://10.0.60.16:443/command-api: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"}
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
This issue is caused by Python 3.10 defaulting to newer TLS Ciphers than the ones supported by default in EOS. 
We will try to work around this, by still allowing to connect with the older ciphers, but this involves changes on multiple levels - AVD, arista.eos collection mantained by RedHat, Ansible itself.

Possible workarounds:
1. Add stronger ciphers to EOS
2. Downgrade Python to 3.9

Since you are testing on WSL, could you try to downgrade Python to 3.9 and rerun?

**Comment by theotherguy2175** [comment]
Sure I can try to downgrade to 3.9. So is this something that I can do on my end to fix on EOS? Or is this a feature update that will have to happen on Arista's end?

**Comment by ClausHolbechArista** [comment]
The default ciphers will be updated in a future version of EOS. I don't know which version.
To be able to work around this in the meantime, I have submitted a [PR for `ansible.netcommon`](https://github.com/ansible-collections/ansible.netcommon/pull/494) so we can control the ciphers being used.
You can also configure stronger ciphers on EOS by adding ciphers to a custom "ssl profile". See [documentation](https://www.arista.com/en/um-eos/eos-control-plane-security#xx1017549) for details.

**Comment by theotherguy2175** [comment]
Installing a previous version of Python proved more difficult than expected. And I did set the cipher to 4096 bits which helped. But AVD would overwrite that with the default configuration. 

So for now I just used HTTP configuration in AVD, and everything is working great.

**Comment by theotherguy2175** [comment]
I was curious do you know if recent versions of EOS have the right cipher type now?
