### ISSUE TITLE
Add 7020R as platform 

### ISSUE THREAD

**Issue by tweippert** [aristanetworks/ansible-avd#2352]
### Issue Summary

Currently the 7020R models aren't mentioned in the platform specific sections, therefore it is not directly visible that these platforms need some optimization (tcam profile!)

After adding the platform (7280R) to our used DCS-7020TR-48-F the vxlan-routing profile gets correctly setup and the fabric is working (and forwarding traffic correctly).

### Which component(s) of AVD impacted

eos_designs, eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
Hello, thanks for opening this issue, `eos_designs` list of default platforms is not meant to be exhaustive but contains what has been requested by the field so far.  

Note that you always have the option to configure the platforms to suite your needs for your project by creating your own `platform_settings` variable in your AVD project as described here: https://avd.sh/en/latest/roles/eos_designs/doc/platform-settings.html.

I have remarked this issue as an enhancement - feel free to contribute with a PR to add support for this platform!
