### ISSUE TITLE
CVX Client non-default VRF support

### ISSUE THREAD

**Issue by sarunac** [aristanetworks/ansible-avd#2367]
### Enhancement summary

Add support for configuring CVX Client (management cvx) in non-default VRF.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Some of the CVX deployments's management  can get assigned to a non-default VRF as shown below.

media-leaf-1#sh man api http
Enabled:            Yes
HTTPS server:       running, set to use port 443
HTTP server:        shutdown, set to use port 80
Local HTTP server:  shutdown, no authentication, set to use port 8080
Unix Socket server: shutdown, no authentication
VRFs:               MGMT

In these instances , if the switch acts as a cvx client, management cvx needs to be configured under the non-default vrf so it can use the non-default vrf to communicate to cvx server. 

example:

management cvx
   no shutdown
   server host 10.90.224.188
   vrf MGMT

### Describe the solution you would like

This is similar to cvx client configurations. 
https://github.com/aristanetworks/ansible-avd/issues/2075

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
@sarunac Will you implement this, or should I find a volunteer?

**Comment by UchihaItachiSama** [comment]
I can help out on this one if required. Need it for a lab, currently have to use `eos_cli` as workaround

```yaml
#management CVX configuration
eos_cli: |
  management cvx
   no shutdown
   server host 172.100.100.9
   server host 172.100.100.10
   server host 172.100.100.8
   source-interface Management0
   vrf MGMT
   !
```

**Comment by ClausHolbechArista** [comment]
Thanks @UchihaItachiSama I will assign to you.

**Comment by UchihaItachiSama** [comment]
submitted a PR, ready for review!
