### ISSUE TITLE
Support for "arp learning bridged"

### ISSUE THREAD

**Issue by dgonzalez1985** [aristanetworks/ansible-avd#2370]
### Enhancement summary

Hi,

This was introduced in 4.26.1F for the centralized anycast gateway model, details can be found here:

https://www.arista.com/en/support/toi/eos-4-26-1f/14781-evpn-centralized-anycast-gateway

```
router l2-vpn
   arp learning bridged
```

I believe this is not supported today based on the documentation and issues available (please double check):
https://avd.sh/en/latest/roles/eos_cli_config_gen/index.html?h=eos+cli#router-l2-vpn

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Configure L2 VTEPs with this feature to learn arp from bridged traffic and advertise entries in EVPN.

### Describe the solution you would like

Support the following configuration in eos_cli_config_gen:

```
router l2-vpn
   arp learning bridged
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
@dgonzalez1985 will you add this or should I find a volunteer?

**Comment by dgonzalez1985** [comment]
hey Claus, it would be great if you can find someone to help with this. @tgodaA @gmuloc have helped me before in case you guys have cycles.

It would be great if we can set a new project named "ES-PROJECT-04" and tag this issue with it (not urgent). I do not have permissions apologies. It would be useful to track any new features we may need.
