### ISSUE TITLE
Add support for eos_cli key on mgmt-interface.j2

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#2376]
### Enhancement summary

Add support for `eos_cli` key on `mgmt-interface.j2` template to allow us to add additional commands to the management interface depending on the use case

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

In some cases we want to define the management interface as a VLAN interface, and only add certain commands  like ip virtual-router on the aggregation switches. Current template does not support this.

### Describe the solution you would like

Add an extra `eos_cli` key to allow us to customize the management interface configuration as needed

### Describe alternatives you have considered

using the vlan-interfaces.j2 data model instead, however the management IP does not get generated on the device documentation if I do it this way...

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
We are currently "misusing" `management_interfaces` to also specify SVIs for inband management. This will change at some point - not sure we can make it for 4.0, so this is just a heads up. We should try to avoid configuring anything but the physical management interfaces under this key.
That said, we can indeed add `eos_cli` to the template.

**Comment by gusmb** [comment]
What would be the right way to use eos_cli_config_gen, when configuring an SVI as a management interface, so that it gets documented in markdown. Would it be adding new keys for inband management,.or use the existing vlan_interfaces_key? In the latter case, I guess the "type: inband" kV pair would be needed to identify the mgmt svi?

**Comment by ClausHolbechArista** [comment]
The correct way would be to use `vlan_interfaces` since `eos_cli_config_gen` should be transparent to the use of each object. But for documentation, it would put the interface together with all the other SVIs. This is the reason why I ended up misusing the `management_interfaces` for the SVI back when I added inband management to `eos_designs`. So I follow your concern.

We can add a detection for `type: mgmt` to the SVI data model and then show it is a separate table. Or would it be enough to just show the type on the existing table of VLAN interfaces?

**Comment by gusmb** [comment]
I think a separate table on the management section is cleaner, since it is indeed an inband management interface, so browsing through the clan interfaces to find out which one is the management IP is not ideal...

**Comment by gusmb** [comment]
I will open a PR to add eos_cli key support to the management_interfaces data model. I can use that for now and change to the approach we are discussing after the documentation is addressed in future releases

**Comment by ClausHolbechArista** [comment]
Thank you Gustavo. I agree on this approach.
