### ISSUE TITLE
eos_config_deploy_cvp: Missing documentation of apply_mode 

### ISSUE THREAD

**Issue by tgodaA** [aristanetworks/ansible-avd#2380]
<img width="420" alt="image" src="https://user-images.githubusercontent.com/88734745/210849686-04af4eab-1024-4ce2-984a-ffa98a897d32.png">

There is no documentation for the apply_mode: strict/loose in the URL: https://avd.sh/en/devel/roles/eos_config_deploy_cvp/index.html

This is a new feature applicable only for the cv_collection: v3

**Comment by JulioPDX** [comment]
Thank you @tgodaA, I'll get on this!

**Comment by ClausHolbechArista** [comment]
This `apply_mode` option had no function here. It would always be `loose`. So this is an error in the guide. I am adding support for `container_apply_mode` and `device_apply_mode` (among others) in #2561. I will update the example as part of that as well.

**Comment by ClausHolbechArista** [comment]
Addressed by #2718
