### ISSUE TITLE
LLDP configuration is not rendered when ethernet interface lacp fallback mode is static

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#2382]
### Enhancement summary

Modify line 8 of the `ethernet-interfaces.j2` template to also print port-channel member ports data if lacp fallback mode is set to static.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Ethernet interfaces behave in a similar way when lacp fallback mode is static or individual. Currently the template only prints Ethernet config on the channel member ports when lacp fallback mode is individual. I have static mode instead and need to add lldp to data to the member ports,. however the structured config is not generated due to this issue.

### Describe the solution you would like

Change line 8 of the template to not check static vs individual mode:

```jinja
selectattr('lacp_fallback_mode', 'arista.avd.defined') | ...
```

### Describe alternatives you have considered

Using eos_cli on the channel member ports

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
This will have wider consequences and cannot be fixed alone. I think the actual issue here is that lldp is excluded from member ports, so we should move lldp out of the condition.

I don't think the ethernet interface behave the same in static and individual. In `static` it will take the config from the port-channel interface, where in `individual` it will ignore the port-channel config and use that of the ethernet interface.

**Comment by gusmb** [comment]
> This will have wider consequences and cannot be fixed alone. I think the actual issue here is that lldp is excluded from member ports, so we should move lldp out of the condition.
> 
> I don't think the ethernet interface behave the same in static and individual. In `static` it will take the config from the port-channel interface, where in `individual` it will ignore the port-channel config and use that of the ethernet interface.

Yes that would fix this as well and would allow me to use the proper key instead of eos_cli
