### ISSUE TITLE
Doc: add libyaml requirement for development

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#2432]
### Enhancement summary

without libyaml - generated schema won't have the same format as without and CI will fail.

### Which component of AVD is impacted

others

### Use case example

```
ansible --version

ansible [core 2.12.10]
  config file = None
  configured module search path = ['/Users/guillaumemulocher/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /private/tmp/blah/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/guillaumemulocher/.ansible/collections:/usr/share/ansible/collections
  executable location = /private/tmp/blah/bin/ansible
  python version = 3.10.4 (main, Jul 29 2022, 21:08:16) [Clang 13.0.0 (clang-1300.0.29.30)]
  jinja version = 3.1.2
  libyaml = False
```

libyaml False is bad

### Describe the solution you would like

in the doc indicate the requirement

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
PyYAML 6.0 contains bundled libyaml, so we could bump the development requirement to `PyYAML>=6.0`

**Comment by ClausHolbechArista** [comment]
We have custom `yaml_dumper` and `yaml_loader` now, which try/except the Cloader/Cdumper imports. So if we ensure all use of yaml dump/load is using these, we can work in all environments.

**Comment by gmuloc** [comment]
> PyYAML 6.0 contains bundled libyaml, so we could bump the development requirement to `PyYAML>=6.0`

This is now done in pyavd which is used to compile the templates so we can close this issue
https://github.com/aristanetworks/avd/blob/devel/python-avd/pyproject.toml#L42
