### ISSUE TITLE
Validate state failing running devel (4.0.0)

### ISSUE THREAD

**Issue by philippebureau** [aristanetworks/ansible-avd#2459]
### Issue Summary

validate state playbook fails with this message :
> TASK [arista.avd.eos_validate_state : Collection {{ ansible_collection_name }} version {{ version }}{{ ('(git ' ~ git_tag ~ ')') if git_tag }} loaded from {{ collection_path }}] ***
> fatal: [DC1-SPINE1 -> localhost]: FAILED! => 
>   msg: 'An unhandled exception occurred while templating ''{{ lookup(''pipe'', ''git -C '' ~ collection_path ~ '' describe --tags --always 2>/dev/null'') }}''. Error was a <class ''ansible.errors.AnsibleError''>, original message: An unhandled exception occurred while running the lookup plugin ''pipe''. Error was a <class ''ansible.errors.AnsibleError''>, original message: lookup_plugin.pipe(git -C /home/phil/Documents/GitHub/ansible-cvp/ansible_collections describe --tags --always 2>/dev/null) returned 128. lookup_plugin.pipe(git -C /home/phil/Documents/GitHub/ansible-cvp/ansible_collections describe --tags --always 2>/dev/null) returned 128'

### Which component(s) of AVD impacted

eos_validate_state

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
update to avd devel, run fabric validate
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Which ansible-core version are you running?

**Comment by philippebureau** [comment]
comparing eos_designs and eos_validate_state, I see eos_design has additional code in git_tag

![image](https://user-images.githubusercontent.com/8918617/214119094-7fd6c727-5f2b-4b88-81db-c71cb76fa876.png)

if I add , errors='ignore'  to  the git_tag  in  validate_state, the task runs succesfully

**Comment by philippebureau** [comment]
> 

ansible-core 2.12.10

**Comment by philippebureau** [comment]
> Which ansible-core version are you running?

ansible-core 2.12.10

**Comment by philippebureau** [comment]
@ClausHolbechArista confirmed this was removed as part of PR 2400 (https://github.com/aristanetworks/ansible-avd/pull/2400/files)

I  will create a new PR to put back the error handling where it was removed.
