### ISSUE TITLE
Feature request - Add support for SN based host lookup in CVP

### ISSUE THREAD

**Issue by kwargian** [aristanetworks/ansible-avd#2472]
### Enhancement summary

Under the hood, eos_config_deploy_cvp uses modules like [cv_device_v3](https://cvp.avd.sh/en/stable/docs/modules/cv_device_v3.rst) which support a search key option to locate devices in CVP inventory by hostname, FQDN, or serial number (default is hostname). There is no way today to tell eos_config_deploy_cvp to lookup devices by serial number instead of hostname, so this feature request would be to

1. Add a knob to eos_config_deploy_cvp to change search key
2. Add a serial number key to either hosts in inventory (similar to the is_deployed key) or eos_design to be used for this lookup 

### Which component of AVD is impacted

eos_designs, eos_config_deploy_cvp

### Use case example

Customer wants to rename devices in fabric and has already deployed them in production - changing hostnames in Ansible inventory and re-running AVD pipeline will result in it not matching devices in CVP, because Ansible will now have the new hostnames for nodes, and CVP will have the old ones; lookup by hostname fails. To make this work today, hostnames have to be changed on the devices either by CLI or Ansible playbook (either to eAPI directly or via ansible-cvp) so that CVP picks up the new hostnames, and then the AVD pipeline can be ran.

Implementing this change allows for a pure-AVD way to update device hostnames

### Describe the solution you would like

1. Add a knob to eos_config_deploy_cvp to pass-through a search-key selection to cv_device_v3 and similar modules in ansible-cvp.
2. Add a field to map a serial number to a device in Ansible inventory - multiple locations where this could work.

### Describe alternatives you have considered

See non-AVD playbook workflow described in use case above.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Point 1 will be solved by #2561. We still need to add and handle the serial number while building the vars in AVD.
