### ISSUE TITLE
Unable to not use virtual-router mac-address

### ISSUE THREAD

**Issue by chetryan** [aristanetworks/ansible-avd#2473]
### Issue Summary

At the moment, the `virtual_router_mac_address` needs to be defined on L3 Leafs, even if the leafs do not use MLAG and VxLANs.

```
    # Virtual router mac address for anycast gateway | Required.
    virtual_router_mac_address: < mac address >
```

The impact is that for the cases where this command is not required, `custom_structured_configuration` needs to be used override this behaviour.

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI with AVD Runner

### Steps to reproduce

```shell
Trying to run eos_designs against a fabric with L3 Leafs with: 
- Missing the `virtual_router_mac_address` field
- or having `virtual_router_mac_address` be empty or set to None

will result in an error.
```

### Relevant log output

Tested on both AVD 3.7.0 and 3.8.0. 

Example output when `virtual_router_mac_address` is not defined with AVD 3.8.0 : 

```shell
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible_collections.arista.avd.plugins.plugin_utils.errors.errors.AristaAvdMissingVariableError: virtual_router_mac_address
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
`virtual router mac address` is also required for VARP, which can have use cases even without vxlan or mlag.
So I don't see this as a bug, but maybe a feature request to allow _not_ setting this.

Did it accept missing this in 3.7.0?
