### ISSUE TITLE
Doc(eos_cli_config_gen): switchport_default phone trunk option tagged not available on cli

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#2478]
### Issue Summary

the doc for ```switchport default phone trunk``` provides two options ```tagged | untagged```

```
switchport_default:
  phone:
    trunk: < tagged | untagged >
```

but the EOS cli just offers option ```untagged```.

```
switch(config)#switchport default phone trunk ?
  untagged  Configure the port to send untagged packets
```

Even the eos template ```ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/switchport-default.j2``` just renders ```untagged```.

```
{% if switchport_default.phone.trunk is arista.avd.defined and switchport_default.phone.trunk == 'untagged' %}
!
switchport default phone trunk untagged
{% endif %}
```

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI with AVD Runner

### Steps to reproduce

```shell
check EOS cli:

switch(config)#switchport default phone trunk ?
  untagged  Configure the port to send untagged packets
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by kmueller68** [comment]
Update on this:
Have received an EOS 4.30 EFT  and developers have extended this global command now with additonal option ```tagged``` and ```phone```:

```
nac-710p(config)#switchport default phone trunk ?
  tagged    Configure the port to send tagged packets
  untagged  Configure the port to send untagged packets

nac-710p(config)#switchport default phone trunk tagged ?
  phone  Tagged packets on phone VLAN
  <cr>

nac-710p(config)#switchport default phone trunk untagged ?
  phone  Untagged packets on phone VLAN
  <cr>
```

**Comment by ClausHolbechArista** [comment]
So if you use a new EOS, the current implementation is valid right? The cli seems a bit weird that you have "switch default **phone** trunk tagged **phone**". Let's not implement that until we see the final version :)

**Comment by kmueller68** [comment]
Current implementation (j2) is valid,
but current doc offers option tagged, which is not available at CLI for global command.

4.29.1F offers 
```switchport default phone trunk untagged```
and 
```
interface ethernet1
  switchport phone trunk untagged (phone)
  switchport phone trunk tagged
```
With 4.30.0F it would be
```
switchport default phone trunk untagged (phone)
switchport default phone trunk tagged (phone)
```
and
```
interface ethernet1
  switchport phone trunk tagged | untagged (phone)
```

I have #2479 open as Feature enhancement, which I would like to contribute as soon as 4.30.0F is GA, since we need it for large campus project.

**Comment by kmueller68** [comment]
EOS-4.30.0.F is GA since a few weeks and now supports the following global switchport default cli:

```
localhost(config)#switchport default ?
  mode   Set the switchport default mode
  phone  Set trunking mode to phone trunk unconditionally

localhost(config)#switchport default phone ?
  access-list  Port access-list configuration
  cos          Configure COS
  qos          Configure QOS
  trunk        Set trunking characteristics of the interface
  vlan         Details on VLAN operation

localhost(config)#switchport default phone trunk ?
  tagged    Configure the port to send tagged packets
  untagged  Configure the port to send untagged packets

localhost(config)#switchport default phone trunk tagged ?
  phone  Tagged packets on phone VLAN
  <cr>

localhost(config)#switchport default phone trunk tagged
localhost(config)#
localhost(config)#switchport default phone trunk untagged ?
  phone  Untagged packets on phone VLAN
  <cr>
```

The docs will be updated automatically when feature request #2479 will be finished.

I will close this issue aftewards.

**Comment by ClausHolbechArista** [comment]
@kmueller68 Has this been implemented so we can close this one? Thanks

**Comment by kmueller68** [comment]
@ClausHolbechArista Yes, the docs matches the cli starting 4.30.0F.
We can close this issue.
