### ISSUE TITLE
Feat(eos_cli_config_gen): add event-handler trigger "on-startup-config"

### ISSUE THREAD

**Issue by bjmeuer** [aristanetworks/ansible-avd#2483]
### Enhancement summary

Today the only supported event-handler trigger is "on-logging". It works to set also "on-startup-config" but warnings are shown in the validation against the schema. 

[WARNING]: b"[sw6]: 'Validation Error: event_handlers[0].trigger': 'on-startup-config' is not one of ['on-logging']"

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Several customers of mine use an event-handler to store the last 10 startup-configs on the switch itself, for the case their central config repo is failing and they need to go back to the last config version on a switch or compare configs on the switch itself.

The trigger to store a copy is when the starup-config is changed. This is the event-handler they use:

```
event-handler CONFIG_VERSIONING
   trigger on-startup-config
   action bash FN=/mnt/flash/startup-config; LFN="`ls -1 $FN.*-* | tail -n 1`"; if [ -z "$LFN" -o -n "`diff -I 'last modified' $FN $LFN`" ]; then cp $FN $FN.`date +%Y%m%d-%H%M%S`; ls -1r $FN.*-* | tail -n +11 | xargs -I % rm %; fi
   delay 0
!
```

### Describe the solution you would like

As the definition and configuration already works it looks like only an update is needed to the documentation where it says only "on-logging" is supported and in the validation files the "on-startup-config" needs to be added.

Files to address the changes:

- Input Variables.md
- eos_cli_config_gen.jsonschema.json
- eos_cli_config_gen.schema.yml
- event_handlers.schema.yml

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by UchihaItachiSama** [comment]
should be a simple change considering if we only plan to add support for `on-logging` and `on-startup-config` we can update the valid_values 

```yaml
        trigger:
          type: str
          description: |
            Configure event trigger condition.
          valid_values: ["on-logging", "on-startup-config"]
```

and the README

unless we plan on adding other triggers which are available via CLI currently, 

```shell
trigger ?
  on-boot            Trigger condition occurs on system boot
  on-config          Trigger the event handler when it is configured
  on-counters        Trigger condition occurs on evaluating statistical counters
  on-intf            trigger condition occurs on specified interface changes
  on-logging         Trigger condition occurs when regex match any log message
  on-maintenance     Trigger condition occurs on maintenance operation
  on-startup-config  trigger condition occurs on startup config changes
  vm-tracer          Trigger condition occurs on VmTracer events
```

but that would require `event-handlers.j2` template changes as well. Would let other's comment about their views.

**Comment by ClausHolbechArista** [comment]
Since each trigger requires different options, I think we should just add the ones we need and add test coverage. @bjmeuer will you add this yourself or should we find a volunteer? Please make sure to add to molecule as well. Thanks.

**Comment by bjmeuer** [comment]
Hi @ClausHolbechArista , I will give it a try to add myself

**Comment by bjmeuer** [comment]
Pull Request has been created: https://github.com/aristanetworks/ansible-avd/pull/2486
