### ISSUE TITLE
Problem with Validator upgrading avd from 3.7.0 to 3.8.1

### ISSUE THREAD

**Issue by ninnux** [aristanetworks/ansible-avd#2484]
### Issue Summary

My AVD code fails on avd schema validator after upgrading arista.avd from 3.7.0 to 3.8.1.

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
upgrading avd by ansible-galaxy from 3.7.0 to 3.8.1
```

### Relevant log output

```shell
task path: /usr/users/ciurleo/.ansible/collections/ansible_collections/arista/avd/roles/eos_cli_config_gen/tasks/main.yml:38
The full traceback is:
Traceback (most recent call last):
  File "/usr/users/ciurleo/.ansible/collections/ansible_collections/arista/avd/plugins/plugin_utils/schema/avdschema.py", line 53, in load_schema
    self._validator = AvdValidator(schema)
TypeError: 'NoneType' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/users/ciurleo/.ansible/collections/ansible_collections/arista/avd/plugins/action/validate_and_template.py", line 66, in run
    self.avd_schema = AvdSchema(schema)
  File "/usr/users/ciurleo/.ansible/collections/ansible_collections/arista/avd/plugins/plugin_utils/schema/avdschema.py", line 40, in __init__
    self.load_schema(schema)
  File "/usr/users/ciurleo/.ansible/collections/ansible_collections/arista/avd/plugins/plugin_utils/schema/avdschema.py", line 57, in load_schema
    raise AristaAvdError("An error occured during creation of the validator") from e
ansible_collections.arista.avd.plugins.plugin_utils.errors.errors.AristaAvdError: An error occured during creation of the validator
fatal: [RM6_LEAF1 -> localhost]: FAILED! => changed=false 
  msg: Invalid Schema supplied to the 'arista.avd.validate_and_template' plugin
The full traceback is:
Traceback (most recent call last):
  File "/usr/users/ciurleo/.ansible/collections/ansible_collections/arista/avd/plugins/plugin_utils/schema/avdschema.py", line 53, in load_schema
    self._validator = AvdValidator(schema)
TypeError: 'NoneType' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/users/ciurleo/.ansible/collections/ansible_collections/arista/avd/plugins/action/validate_and_template.py", line 66, in run
    self.avd_schema = AvdSchema(schema)
  File "/usr/users/ciurleo/.ansible/collections/ansible_collections/arista/avd/plugins/plugin_utils/schema/avdschema.py", line 40, in __init__
    self.load_schema(schema)
  File "/usr/users/ciurleo/.ansible/collections/ansible_collections/arista/avd/plugins/plugin_utils/schema/avdschema.py", line 57, in load_schema
    raise AristaAvdError("An error occured during creation of the validator") from e
ansible_collections.arista.avd.plugins.plugin_utils.errors.errors.AristaAvdError: An error occured during creation of the validator
fatal: [RM6_LEAF2 -> localhost]: FAILED! => changed=false 
  msg: Invalid Schema supplied to the 'arista.avd.validate_and_template' plugin
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Hi Nino, please make sure you have all the latest requirements installed. Specifically in this case, I suspect a too old version of jsonschema. See instructions here: https://avd.sh/en/stable/docs/installation/collection-installation.html#python-requirements-installation

**Comment by ninnux** [comment]
Hi Claus,
I just checked the python requirements like in the documentation.
All requirements are satisfied.
My jsonschema is 4.17.3

In any case this requirements are satisfied:
netaddr>=0.7.19
Jinja2>=2.11.3
treelib>=1.5.5
cvprac>=1.0.7
paramiko>=2.7.1
jsonschema>=4.5.1
requests>=2.25.1
PyYAML>=5.4.1
md-toc>=7.1.0
deepmerge>=1.0.1
cryptography>=38.0.4

But I continue to have the same error on Validator.

**Comment by gmuloc** [comment]
Hello @ninnux - for AvdValidator to be `None`, the check happens here: https://github.com/aristanetworks/ansible-avd/blob/v3.8.1/ansible_collections/arista/avd/plugins/plugin_utils/schema/avdvalidator.py#L171

So in theory this happens only if one of the jsonschema or the deepmerge import fails

Can you please give us the output of the following commands

```
python -c "import jsonschema; import jsonschema._types; import jsonschema._validators; import jsonschema.protocols; import jsonschema.validators; from deepmerge import always_merger"
which python
ansible --version
```
and tell us how you are running AVD?

I have installed similar setup (jsonschema 4.17.3 and deepmerge 1.0.1 and then 1.1.0) but I am unable to repro your issue for now.

Thanks in advance!

**Comment by ClausHolbechArista** [comment]
~ah yes if the deepmerge is missing, this will happen.~ when uninstalling deepmerge I get a clear error that this is the problem. So it is something else.

**Comment by ClausHolbechArista** [comment]
@ninnux I just reproduced the exact same errors as you get, by downgrading to a too old version of the jsonschema library. The outputs requested by @gmuloc can help confirm this as well as clear up what is going on.
Another thing to check is if you have `ansible_python_interpreter` anywhere in your inventory. That can affect some of this as well.

**Comment by ninnux** [comment]
I solved uninstalling and installing jsonschema.
But the strange thing is that I have tried on many machines, and venv installing all packages from scratch...
Thank you for your support
Nino
