### ISSUE TITLE
Unnecessary warning on data for AVD 3.8.1

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#2488]
### Issue Summary

I get the following warning when running the builds:

```
[WARNING]: b"[cfsa-lab2-0201b]: 'Validation Error: maintenance.units[0]':

Required key 'profile' is not set in dict."
```

However the config I get is perfectly valid an accepted on CLI, without setting the units profile.  In eos_cli_config_gen template, this key is also optional and ignored if not specified.

My intended configuration:

```
maintenance
   profile interface MM-PROFILE-INTERFACE-SHUTDOWN default
   !
   profile interface MM-PROFILE-INTERFACE-SHUTDOWN
      shutdown max-delay 300
   !
   unit System
```

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Create structured data with maintenance mode. Define system unit without assigning any profile.
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
Hi @gusmb, thanks for raising this issue 

the warning comes from the schema where profile was defined as a required key: https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml#L115

I have looked at a CLI and indeed a profile is not "required", if no profile is given, the default one is used:
```
Leaf1#show run se maintenance
maintenance
   unit System
   !
   unit TEST1
   !
   unit toto
      profile unit blah

Leaf1#show maintenance units
Unit Name: System
   Origin: Built-in
   Status: Not Under Maintenance
   Unit Profile: Default
   Time Since Last State Change: never
   Bgp Groups:
     AllBgpNeighborVrf-default
   Interface Groups:
     AllEthernetInterface

Unit Name: TEST1
   Origin: User Configured
   Status: Not Under Maintenance
   Unit Profile: Default
   Time Since Last State Change: never

Unit Name: toto
   Origin: User Configured
   Status: Not Under Maintenance
   Unit Profile: blah
   Time Since Last State Change: never
```

I will work on relaxing the schema there
