### ISSUE TITLE
Add Docker file

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#25]
add docker file to enable consistent use and deployment of Ansible Arista Validated Design Collection.

Provide docker file for:

- Ansible 2.8
- Ansible 2.9(devel)

**Comment by kgrozis-arista** [comment]
Hi, Carl,

I’ll work on this tomorrow and plan on having a pull request for review.

Thanks
Kevin

**Comment by carlbuchmann** [comment]
Cool man!

I did a big push tonight and tackled a few of the major issues, check out
the PRs!

Thanks

<http://www.arista.com/>
Software Driven Cloud Networking
<https://www.linkedin.com/company/arista-networks-inc>
<https://www.facebook.com/AristaNW/> <https://twitter.com/aristanetworks>
<https://www.youtube.com/user/AristaNetworks>

*Carl Buchmann | Systems Engineer*

carl.buchmann@arista.com

m: +1.613.222.5936
*www.arista.com* <http://www.arista.com/>

**Comment by kgrozis-arista** [comment]
> add docker file to enable consistent use and deployment of Ansible Arista Validated Design Collection.
> 
> Provide docker file for:
> 
> * Ansible 2.8
> * Ansible 2.9(devel)

@carlbuchmann Single Dockerfile provided.  I made ansible version a variable that can be passed in with docker build.  By default the Dockerfile sets ansible version to 2.8.5.

Do you want me to write a docker-compose file to spin both a container with 2.8 and 2.9 at the same time?
