### ISSUE TITLE
Feat(eos_cli_config_gen): Add support for "as-path remote-as replace out" for BGP neighbors

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#2549]
### Enhancement summary

I need to configure the following under a BGP peer session under a VRF (also applicable at global level):

```
neighbor x.x.x.x as-path remote-as replace out
```

This is currently not supported and I have to handle this configuration via `eos_cli` key

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Replace AS number in as-path  for remote AS peers (in or out)

### Describe the solution you would like

Add data model key to support this functionality. Extend it to support all CLI options under "as-path"

### Describe alternatives you have considered

using `eos_cli` key

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gusmb** [comment]
@ClausHolbechArista how can I re-generate the schema and docs when I make a change? seems like it is no longer in the molecule Makefile, not sure how to run this now.. The following runs the full scenario, while I want to generate the schemas:

```
.PHONY: cli-4.0-schema
cli-4.0-schema: ## Execute molecule scenarios for eos_cli_config_gen 4.0 schema updates.
	cd .. && \
	molecule converge --scenario-name eos_cli_config_gen -- $(ANSIBLE_OPTIONS)
	cd .. && \
	molecule converge --scenario-name eos_cli_config_gen_v4.0 -- $(ANSIBLE_OPTIONS)
```

**Comment by ClausHolbechArista** [comment]
Apologies we are behind on updating the contribution guide here. Please install `pre-commit` and run `pre-commit run schemas --all`

**Comment by gusmb** [comment]
> Apologies we are behind on updating the contribution guide here. Please install `pre-commit` and run `pre-commit run schemas --all`

Got it, thanks

**Comment by gusmb** [comment]
I will work on a PR for this, please assign this issue to myself
