### ISSUE TITLE
Set eos_designs facts fails when leaf switch name is fqdn

### ISSUE THREAD

**Issue by roberthill-omf** [aristanetworks/ansible-avd#2556]
### Issue Summary

When running the build playbook from the L2LS example, the run fails when it gets to the task for setting the EOS design facts if the leaf switch uses it's fqdn for the name. 

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Build out L2LS example from repo
Rename LEAF1 to LEAF1.full.fqdn in inventory.yml and group_vars/DC1_FABRIC.yml
Run build.yml playbook
```

### Relevant log output

```shell
fatal: [SPINE1]: FAILED! => {"changed": false, "msg": "avd_switch_facts.LEAF1.full.fqdn.switch is required but was not found for host 'LEAF2.full.fqdn'"}
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
I believe this was already fixed by https://github.com/aristanetworks/ansible-avd/pull/2502. Which version of AVD are you testing with?

**Comment by roberthill-omf** [comment]
> 

I'm currently testing with v3.8.1

**Comment by carlbuchmann** [comment]
@rwh101485 this PR #2502 was cherry-picked to v3.8.2 -> https://www.avd.sh/en/devel/docs/release-notes/3.x.x.html#release-382
Please test with 3.8.2 and let us know if this resolves your issue.

**Comment by roberthill-omf** [comment]
Upgarded to 3.8.2 and the issue is resolved. Thank you for your help.
