### ISSUE TITLE
Ignore /1 at the end of QSFP interfaces

### ISSUE THREAD

**Issue by roberthill-omf** [aristanetworks/ansible-avd#2558]
### Enhancement summary

When generating a config, port channels that include qsfp interfaces that end in /1 (all interfaces on 7050cx3, interfaces 97-104 on 7050sx3, etc). I think it would be helpful for usability and readability's sake to ignore the /1 at the end of those interfaces when the config is generated. Or at the very least, incorporate a flag that could be tripped to allow it to be ignored if desired.

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen, plugins

### Use case example

If a design includes a port channel that includes the interfaces Ethernet103/1 and Ethernet104/1, AVD will create the port channel with a name of Port-Channel1031. Example:

interface Port-Channel1031
   description MLAG_PEER_LEAF1_Po1031
   no shutdown
   switchport
   switchport trunk allowed vlan 2-4094
   switchport mode trunk
   switchport trunk group MLAG
!
interface Ethernet103/1
   description MLAG_PEER_LEAF1_Ethernet103/1
   no shutdown
   channel-group 1031 mode active
!
interface Ethernet104/1
   description MLAG_PEER_LEAF1_Ethernet104/1
   no shutdown
   channel-group 1031 mode active

### Describe the solution you would like

Ignoring the /1 at the end of the interface name will generate a port channel name that is more readable and recognizable. It's only a small difference but all other engineers and architects I've worked with prefer this naming scheme when creating port channels:

interface Port-Channel103
   description MLAG_PEER_LEAF1_Po1031
   no shutdown
   switchport
   switchport trunk allowed vlan 2-4094
   switchport mode trunk
   switchport trunk group MLAG
!
interface Ethernet103/1
   description MLAG_PEER_LEAF1_Ethernet103/1
   no shutdown
   channel-group 103 mode active
!
interface Ethernet104/1
   description MLAG_PEER_LEAF1_Ethernet104/1
   no shutdown
   channel-group 103 mode active

### Describe alternatives you have considered

Creating custom structured configuration allows me to create the port channels with the specific naming convention, but it doesn't delete the original port channels created by the design task.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
In your example, you might have a breakout on interface 10 into 10/3, 10/4 etc. So those port channel numbers would conflict. The numbering includes all numeric characters to avoid such collisions.
We could create a flag as you suggest, and it would be up to the user to avoid collisions, but it be very hard to work around in case of later conflicts.
