### ISSUE TITLE
Feat(eos_cli_config_gen): Relax schema for empty prefix-lists

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#2596]
### Enhancement summary

Empty prefix lists are accepted in EOS configuration and rendered by `eos_cli_config_gen`, even if no sequence list is provided. I need to configure empty prefix-lists as placeholders sometimes when I expect these to be user-defined at a later point in time, to avoid having undefined references in the configuration. However, the schema validation throws warnings:

```
[WARNING]: b"[fabric-switch]: 'Validation Error: prefix_lists[4]': Required
key 'sequence_numbers' is not set in dict."
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Need to define empty prefix-lists in some cases

### Describe the solution you would like

Relax JSON schema validation to accept prefix-list definitions without sequence list. It is accepted and rendered by the `eos_cli_config_gen` templates.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
I think you need to set `sequence_numbers: []` to do what you want.

**Comment by gusmb** [comment]
Thanks, that worked:)

**Comment by ClausHolbechArista** [comment]
@gusmb do you still need this or is it ok with the empty list? Thanks.

**Comment by gusmb** [comment]
> @gusmb do you still need this or is it ok with the empty list? Thanks.

It worked with the empty list, so I'm good. But it felt a but like a hack... IMO anything that is optional in the CLI and also optional in the J2 templates should not generate any schema warnings.

**Comment by ClausHolbechArista** [comment]
@Shivani-chourasiya please work on this. Also check on EOS if all our other data models with `sequence_numbers` would give any useful config if you leave out the key.
Also please ensure that there is proper protection in the code/templates, so we don't break any code when the key is missing (Just add `arista.avd.default([])` to the for-loops).

**Comment by Shivani-chourasiya** [comment]
> sequence_numbers

Sure!

**Comment by Shivani-chourasiya** [comment]
> 
Sure!
