### ISSUE TITLE
feat(eos_cli_config_gen): add option to maintain POE power during reboot

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#2611]
### Enhancement summary

Add a key to configure poe during a switch reboot.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

please detail your use case

### Describe the solution you would like

I would like to see a new key added:

```
poe_reboot_action: <power-off | maintain >
```
Which renders the stanza:
```
poe
   reboot action maintain
```

### Describe alternatives you have considered

This can be done today with:
```
eos_cli: |
    poe
      reboot action maintain
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Closing in favor of #2663 which cover this as well as interface shutdown action.
