### ISSUE TITLE
extra line feed in monitor-connectivity is brealink running config 

### ISSUE THREAD

**Issue by BouchardClaude** [aristanetworks/ansible-avd#2652]
### Issue Summary

in config_gen , monitor-connectivity.j2 have extra line feed for description variables. putting the description itself not in the same line as the description keyword

```
{%             if host.description is arista.avd.defined %}
      description
      {{ host.description }}
{%             endif %}
```

shoud be 

```
{%             if host.description is arista.avd.defined %}
      description {{ host.description }}
{%             endif %}
```

at line 26,52 and 60  

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible AWX

### Steps to reproduce

```shell
configure monitor connectivity in config gen, the .cfg generated will have the description on 2 line instead of 1
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
Hello @BouchardClaude,

just tested on some EOS device and here is the syntax:

```
Leaf1(config-mc-test)#description ?
  <cr>

Leaf1(config-mc-test)#description?
description

Leaf1(config-mc-test)#description
Enter host description (max 140 characters): example
Leaf1(config-mc-test)#show active
monitor connectivity
   host test
      description
      example
```


Are you seeing something different? Can you please indicate the paltform?

```
Leaf1(config-mc-test)#show ver
Arista vEOS-lab
[...]
Software image version: 4.27.3F
```

**Comment by gmuloc** [comment]
[For information] tested on 4.29 and 4.30 and seeing the same behavior

**Comment by BouchardClaude** [comment]
Hi, sorry for this, I was wrong as my monitor was not working, but not because of this. this behavious is as expected ( but its the first time I see a description on 2 lines!! ). I tought it was the reason but you are right :)

closing the issue
