### ISSUE TITLE
Deprecate cvp_instance_ip in favor of cvp_instance_ips

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#2673]
Maybe in this doc should we encourage to use the `cvp_instance_ips` ?

_Originally posted by @gmuloc in https://github.com/aristanetworks/ansible-avd/pull/2509#discussion_r1152995257_

**Comment by ClausHolbechArista** [comment]
- Update schema for `cvp_instance_ip` with deprecation warning (removal in 5.0.0) and point to new key `cvp_instance_ips`
- Remove use of `cvp_instance_ip` from regular molecule scenarios and add it to `eos_designs_deprecated_vars` scenario
