### ISSUE TITLE
Revisit data model for terminattr_ingestexclude

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#2675]
```
terminattr_ingestexclude: "< ingest excludes | default -> /Sysdb/cell/1/agent,/Sysdb/cell/2/agent >"
```

exclude**S** - should we document how to give multiple ? ( I guess it is comma separated) + the key is kind of inconsistent with smashexclude**S** (probably historic).

_Originally posted by @gmuloc in https://github.com/aristanetworks/ansible-avd/pull/2509#discussion_r1153001885_

**Comment by ClausHolbechArista** [comment]
What we have is consistent with the configuration in CLI: https://arista.my.site.com/AristaCommunity/s/article/terminattr-most-commonly-used-flags-and-sample-configurations

We can off course break it into lists, but these are often just copied or left as default.

**Comment by gmuloc** [comment]
Ack let's close this
