### ISSUE TITLE
Cut globally defined defaults underlay_routing_protocol and overlay_routing_protocol

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#2679]
Suggested change as per discussion with @ClausHolbechArista 
Move the default `underlay_routing_protocol` and `overlay_routing_protocol` under the node_type_key.

Remove the following key from eos_designs/defaults:
- `underlay_routing_protocol`
- `overlay_routing_protocol` 

Remove `BGP` from the valid value in the schema.

_Originally posted by @carlbuchmann in https://github.com/aristanetworks/ansible-avd/pull/2520#discussion_r1153615498_

**Comment by ClausHolbechArista** [comment]
Actually the defaults are already under node_type_key, and the globally defined defaults of `BGP` are just historic leftovers which are not being used.
