### ISSUE TITLE
Invalid eos_designs defaults for ipvpn_gateway domain IDs

### ISSUE THREAD

**Issue by emilarista** [aristanetworks/ansible-avd#2693]
### Issue Summary

The default values in eos_designs for ipvpn_gateway domain IDs are 0:1 and 0:2, which results in invalid EOS config:

```
arista(config)#router bgp 123
arista(config-router-bgp)#address-family vpn-ipv4 
arista(config-router-bgp-af)#domain identifier 0:1
% Invalid input
arista(config-router-bgp-af)#domain identifier 1:1
arista(config-router-bgp-af)#
```

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Thank you for reporting. I think most people set this according to their own preferences. Should we remove the defaults, or do you have a better idea?

**Comment by emilarista** [comment]
> Thank you for reporting. I think most people set this according to their own preferences. Should we remove the defaults, or do you have a better idea?

I think it makes sense to provide some defaults that work. I will make a PR for it.
