### ISSUE TITLE
Add PTP knobs to l3_edge p2p_links

### ISSUE THREAD

**Issue by ryanmorrisatarista** [aristanetworks/ansible-avd#2698]
### Enhancement summary

PTP knobs are available in connected_endpoints:
# PTP Enable | Optional
        ptp:
          enable: < true | false | default -> false | Required >
          # These are the default settings:
          # - The global PTP profile parameters will be applied to all connected endpoints where ptp is manually enabled.
          # - `ptp role master` is set to ensure control over the PTP topology.
          endpoint_role: < follower | bmca | default -> follower >
          profile: < aes67 | smpte2059-2 | aes67-r16-2016 | default -> aes67-r16-2016 >

These would be valuable to have also in l3_edge p2p_links for L3 devices.

### Which component of AVD is impacted

eos_designs

### Use case example

for switches that are entirely L3 endpoints (very common in media) it is useful to be able to take advantage of the ipv4 pool in l3_edge (p2p_links).  However, not all of the ptp parameters now in eos_designs is available.

### Describe the solution you would like

similar to connected_endpoints for ptp assignment.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Instead of endpoint_role we should probably reverse it and just say `role: <str; "bmca" | "master"; default: "bcma">` for l3_edge.
