### ISSUE TITLE
multiple port profiles for connected endpoints

### ISSUE THREAD

**Issue by pibjndata** [aristanetworks/ansible-avd#2706]
### Enhancement summary

Hello,

is there a possibility to add a functionality to combine more than one port_profile for one connected endpoint.

currently according to documentation , there is a possibility to connect only one port_profile:

https://avd.sh/en/stable/roles/eos_designs/doc/connected-endpoints.html?h=port_pro#port-profiles

it would be very useful to combine more profiles for one endpoint

### Which component of AVD is impacted

eos_designs

### Use case example

as per summary

### Describe the solution you would like

as per summary

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
We have inheritance of port-profiles which might help? See `parent_profile`.
Can you give some more background on how you would use these multiple profiles, so we can invenstigate how best to solve it? Thanks.

**Comment by pibjndata** [comment]
yes, parent_profile solved the issue, thank you Claus!

just additional question regarding parent profile. Does it work with inheritance , for example:

port_profiles:
  PARENT_PROFILE_2:
   <more_configuration>
    parent_profile: PARENT_PROFILE_1
  PARENT_PROFILE_1:
    <configuration>
  PP-PROD_1:
    parent_profile: PARENT_PROFILE_1
  PP-PROD_2:
    parent_profile: PARENT_PROFILE_2
/

as a result we could combine port profiles together and reuse them multiple times.

I have tested such combination on test environment but it looks that it does not work, only directly between one profile and one parent profile

**Comment by gmuloc** [comment]
Hello @pibjndata - we support only two levels of inheritance: https://avd.sh/en/devel/roles/eos_designs/doc/connected-endpoints.html#port-profiles 

```
# Port_profiles can refer to another port_profile to inherit settings in up to two levels (adapter->profile->parent_profile).
```

**Comment by pibjndata** [comment]
ok, thanks for confirmation
