### ISSUE TITLE
Feat(eos_designs): Create knobs to statically set loopback ips for every pool

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#2719]
### Enhancement summary

Right now eos_designs takes pools for VTEP and loopback0 - the idea is to have a knob to statically set the IP for example to accomodate brownfield scenarios

### Which component of AVD is impacted

eos_designs

### Use case example

brownfield

### Describe the solution you would like

have a knob to statically set the IP done within ipAddressing model that takes precedence over the pool.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by durd** [comment]
I think we're having issues with this too. When we have a /32 in `loopback_ipv4_pool` under a node (not node_group or default), avd_designs fails with errors like `Unable to get 2 /32 subnets from pool 10.10.10.5/32`. This is in effort to assign loopback IP's.
What's weird is that the error is from `def router_id()` in `avdipaddressing.py`. I get the feeling that there's a bug there, as router_id usually is the same as loopback0. The default offset of `id + pool-offset` doesn't seem right.

**Comment by ClausHolbechArista** [comment]
That is exactly why this issue was created :) Historically the pools assigned .1 to switch ID 1  to keeep all the network engineers happy (so id is used as index in the underlying list of IPs, so 1 is the *second* entry). The only workaround available today is to use custom IP addressing templates / python class.

**Comment by durd** [comment]
Thanks for the explanation! I just realized too that I could have just +1'd the issue :)

**Comment by jmussmann** [comment]
This feature is also helpful if IPAM tools like netbox are used. I started coding on this feature.
