### ISSUE TITLE
Port-channel Interface Documentation Template to be completed

### ISSUE THREAD

**Issue by aphillipps** [aristanetworks/ansible-avd#272]
Complete and organize information in this template according to the associated eos template

**Comment by ksator** [comment]
@aphillipps   
it was broken I fixed it.  
I added native vlan.  
I submitted a draft PR.  
Should I add more columns (thinking about adding some IPv6 details like we did for ethernet interfaces) or should we keep it like this?  
Should we keep one single table or should I split it in 2 tables (L2 and L3)? 
Mnay thanks!
