### ISSUE TITLE
Doc: Fix search scoping on avd.sh

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#2728]
When searching on avd.sh, we get molecule results and other internal documentation i.e 4.0 Readme artifacts.
These should not show up and be removed.

**Comment by JulioPDX** [comment]
@carlbuchmann Please check if this is good now. We have excluded molecule from inclusion for some time now. #2238

**Comment by JulioPDX** [comment]
Fixed in #2238
