### ISSUE TITLE
Management SSH Device Documentation Template to be completed

### ISSUE THREAD

**Issue by aphillipps** [aristanetworks/ansible-avd#274]
Complete and organize information in this template according to the associated eos template

**Comment by ksator** [comment]
documentation/management-ssh.j2  needs to be created in [templates](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates) folder  

[templates/eos-device-documentation.j2](https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos-device-documentation.j2) needs to be updated to include documentation/management-ssh.j2
