### ISSUE TITLE
Duplicate interface name Ethernet99 found while generating ethernet_interfaces for underlay peer

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#2754]
### Issue Summary

My customer campus lan projext was running well with Pre-release v4.0.0-dev10, but with latest devel as of Arpril 21. 2023 I receive the following error message:

''' 
The full traceback is:
Traceback (most recent call last):
  File "/arista/roles/ansible-avd/ansible_collections/arista/avd/plugins/action/yaml_templates_to_facts.py", line 189, in run
    template_result_data = cls_instance.render()
  File "/arista/roles/ansible-avd/ansible_collections/arista/avd/plugins/plugin_utils/avdfacts.py", line 64, in render
    return {key: getattr(self, key) for key in self.keys() if getattr(self, key) is not None}
  File "/arista/roles/ansible-avd/ansible_collections/arista/avd/plugins/plugin_utils/avdfacts.py", line 64, in <dictcomp>
    return {key: getattr(self, key) for key in self.keys() if getattr(self, key) is not None}
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/arista/roles/ansible-avd/ansible_collections/arista/avd/roles/eos_designs/python_modules/underlay/ethernet_interfaces.py", line 131, in ethernet_interfaces
    raise AristaAvdError(
ansible_collections.arista.avd.plugins.plugin_utils.errors.errors.AristaAvdError: Duplicate interface name Ethernet99 found while generating ethernet_interfaces for underlay peer: distri-10-02.LAN.MU, peer_interface: Ethernet5. Description on duplicate interface name: DISTRI-10-01.LAN.MU_Ethernet5
fatal: [access-10-103-01.LAN.MU -> localhost]: FAILED! => {
    "changed": false,
    "msg": "Duplicate interface name Ethernet99 found while generating ethernet_interfaces for underlay peer: distri-10-02.LAN.MU, peer_interface: Ethernet5. Description on duplicate interface name: DISTRI-10-01.LAN.MU_Ethernet5"
}
''' 

I have seen that have recently been a change in tat python file:
Refactor(eos_designs): ethernet_interfaces python module as per eos_cli_config_gen #2627

I have not been able to find the root cause so far.
Could you please support me on this. Thank you

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI with AVD Runner

### Relevant log output

```shell
The full traceback is:
Traceback (most recent call last):
  File "/arista/roles/ansible-avd/ansible_collections/arista/avd/plugins/action/yaml_templates_to_facts.py", line 189, in run
    template_result_data = cls_instance.render()
  File "/arista/roles/ansible-avd/ansible_collections/arista/avd/plugins/plugin_utils/avdfacts.py", line 64, in render
    return {key: getattr(self, key) for key in self.keys() if getattr(self, key) is not None}
  File "/arista/roles/ansible-avd/ansible_collections/arista/avd/plugins/plugin_utils/avdfacts.py", line 64, in <dictcomp>
    return {key: getattr(self, key) for key in self.keys() if getattr(self, key) is not None}
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/arista/roles/ansible-avd/ansible_collections/arista/avd/roles/eos_designs/python_modules/underlay/ethernet_interfaces.py", line 131, in ethernet_interfaces
    raise AristaAvdError(
ansible_collections.arista.avd.plugins.plugin_utils.errors.errors.AristaAvdError: Duplicate interface name Ethernet99 found while generating ethernet_interfaces for underlay peer: distri-10-02.LAN.MU, peer_interface: Ethernet5. Description on duplicate interface name: DISTRI-10-01.LAN.MU_Ethernet5
fatal: [access-10-103-01.LAN.MU -> localhost]: FAILED! => {
    "changed": false,
    "msg": "Duplicate interface name Ethernet99 found while generating ethernet_interfaces for underlay peer: distri-10-02.LAN.MU, peer_interface: Ethernet5. Description on duplicate interface name: DISTRI-10-01.LAN.MU_Ethernet5"
}
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
Hello @kmueller68 - the previous version of the code was making it possible to have multiple time some Ethernet interface being rendered by the various modules which would lead to the latest version of the interface "winning" the race if you want and making it to the final structured_config.

The new guard in place is there to avoid these kinds of "undefined-ish" scenarii.

What this error __should__  mean is that the current set of input variables will lead the underlay module to render twice Ethernet99 with different configurations and only the latest version will win and so probably something is not right. That being said - this is quite new and it is not impossible that something was missed during adding this guard so I think it is worth investigating further.

I guess it may be complex to help further on your issue without seeing the configuration that leads to this interface being configured. Would you mind maybe sharing some info on this thread if possible or getting in touch to take a look at your current inputs?

**Comment by kmueller68** [comment]
Hello @gmuloc thank you for your fast reply.
I could offer you my project to run it local in your environment.
I have already uploaded it to an fileexhcnage... how could I send you the login directly?

**Comment by kmueller68** [comment]
Thank you very much for your support on resolving this error.
