### ISSUE TITLE
Banner without EOF can break eAPI management

### ISSUE THREAD

**Issue by ankudinov** [aristanetworks/ansible-avd#2782]
### Issue Summary

According to the AVD [documentation](https://avd.sh/en/stable/roles/eos_cli_config_gen/index.html?h=banner#banners), EOF is required when configuring banner string.
That looks like a "lazy" implementation, as EOF is only required to break banner in the terminal and is redundant in the YAML file. But the problem is that EOS is accepting the configuration when EOF is not specified, but treating everything after the banner string as part of the banner. eAPI configuration comes after and a simple playbook run to add a banner results in broken management connectivity to the switch. It also breaks any `eos_cli` config as it's appended to the end as well.

I'd suggest one of the following fixes:
- remove EOF requirement in AVD docs and always enforce it in the template (Disadvantage: that can affect existing implementations)
- make EOF optional, check if it's present and add if not

### How do you run AVD ?

None

### Steps to reproduce

```shell
Add the banner without EOF, run the playbook.
```

### Relevant log output

```shell
None
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ankudinov** [comment]
I'm happy to fix that if the proposed solution will be accepted.

**Comment by ClausHolbechArista** [comment]
I vote for detecting and adding if missing. So seamless for any existing deployment, and ease-of-use for new ones.

I think this would be a nice use case for a string format, but our format support is not ready. So for now, you have to implement it in the jinja template.

**Comment by ClausHolbechArista** [comment]
Implement an `if` in the eos_cli_config_gen template that checks if the last line is `\nEOF` (+ optionally closing `\n` and if not it will add it.
