### ISSUE TITLE
Provide deterministic support for defining the same VRF in multiple tenants

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#2812]
### Enhancement summary

In AVD versions < 4.0.0 it was possible to define the same VRF in multiple tenants. Since the output of `eos_designs` where mostly dictionaries, it was a matter of ordering and "chance" on which of those VRF definitions got rendered. In some cases all of them got combined - ex. for `svis` or `static_routes`, while other settings where overridden by the "last" edition of the VRF - ex. for `bgp_peers`.

In AVD 4.0.0 there is a check for duplicate VRFs preventing the same VRF from being defined across multiple tenants. This will block usage of AVD 4.0.0 in certain customer scenarios unless we add this feature.

### Which component of AVD is impacted

eos_designs

### Use case example

Defining a VRF for shared services across multiple "customer" tenants.

### Describe the solution you would like

This issue is a request to provide deterministic support for defining the same VRF across multiple tenants.
- For list items like `svis`, `l3_interfaces`, `bgp_peers` etc we should combine all of them.
  - If the merged lists contain duplicate items, they will be caught and errors will be raised 
    by duplicate checks for each feature.
  - This means it is _not_ supported to define the same entity (`svi`, `l3_interface` etc) 
    across different tenants for the same VRF.
- For regular keys like `vrf_vni` or `description` they should be combined
  - If a key is only set in one of the VRF instances, it will be accepted
  - If a key is defined in multiple VRF instances with the same value, it will be accepted
  - If a key is defined in multiple VRF instances with _different_ values, an error will be raised.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
This reflects our discussion - I am aligned with the suggestion above
