### ISSUE TITLE
Feat(eos_designs): Add bfd for isis in the MPLS design

### ISSUE THREAD

**Issue by chetryan** [aristanetworks/ansible-avd#2824]
### Enhancement summary

For a design type **mpls** , when the underlay is `isis-*`  and bfd is being used, there is no easy way to have the command `isis bfd` on all the relevant interfaces.

### Which component of AVD is impacted

eos_designs

### Use case example

Unsure what to add as an example.

### Describe the solution you would like

Ideally we would have a knob to indicate we want to use bfd, and any interface that has `isis enable` should also have `isis bfd` configured.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
For OSPF we have `underlay_ospf_bfd_enable: < true | false | default -> false >`. It would make sense to just add a `underlay_isis_bfd_enable: < true | false | default -> false >`
