### ISSUE TITLE
Update schemas for dicts missing "keys" and lists missing "items"

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#2871]
Documentation for various keys updated in this PR reveals that the schema are missing `items` or `keys` definitions. This should be fixed.

_Originally posted by @ClausHolbechArista in https://github.com/aristanetworks/ansible-avd/issues/2870#issuecomment-1555189185_

## eos_cli_config_gen

- [x] `aaa_accounting.commands.commands_default: <list>`
- [x] `router_isis.no_passive_interfaces: <list>`

## eos_designs

- [x] `<network_services_keys.name>.vrfs.evpn_l3_multicast.evpn_peg.nodes: <list>`

**Comment by chetryan** [comment]
@ClausHolbechArista  I can't seem to find any reference to `aaa_accounting.commands.commands_default` in the templates of `eos_cli_config_gen` and the description is `Deprecated and removed key form AVD 2.x`  Should we just remove this obsolete key?

**Comment by ClausHolbechArista** [comment]
@chetryan Yes please. Good catch.
