### ISSUE TITLE
Add ID field to auto-generate schema files

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#2934]
example from json schema: https://json-schema.org/draft/2020-12/json-schema-core.html#name-schema-identification-examp

**Comment by ClausHolbechArista** [comment]
Why do we need this? Until we publish versioned schemas directly, the ID will not do much.

**Comment by carlbuchmann** [comment]
> Why do we need this? Until we publish versioned schemas directly, the ID will not do much.

Correct, only important once we publish to the schema store or something similar. This was an ask from @fredhsu, he can comment some more!

**Comment by fredhsu** [comment]
This is only relevant when schemas are getting published and the user wants to confirm what version of the schema they are working with. Is this redundant with how you're planning to publish the schema? What if a schema is downloaded and stored as part of a deployment workflow?

**Comment by ClausHolbechArista** [comment]
Currently our schemas are not consumable outside of AVD itself. Once we decide on how to publish them, we will also set the ID accordingly. Currently the IDs are statically set inside our internal "schema store".

**Comment by ClausHolbechArista** [comment]
The schemas have a simple ID like `$id: eos_designs`.
