### ISSUE TITLE
refactor template naming and organization in eos_l3ls_evpn

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#295]
**Issue Type**
- Template refactoring

**Is your feature request related to a problem? Please describe.**
- as we increase functionality in eos_l3ls_evpn, refactoring naming and organization is necessary to make it easier to update/enhance in future iterations.

**Comment by titom73** [comment]
Required by:

- #128 : iBGP implementation
- #269 : External RS/RR implementation
