### ISSUE TITLE
update documentation/ip-igmp-snooping.j2

### ISSUE THREAD

**Issue by ksator** [aristanetworks/ansible-avd#298]
## Issue Type

- Documentation Report

## Summary

by default, EOS enables IGMP snooping for all VLANs.    

The template [documentation/ip-igmp-snooping.j2](https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/ip-igmp-snooping.j2)  doesnt currently generate any data when there is no input  (i.e when `ip_igmp_snooping` is not defined).   

Example: 

``````
### Internal VLAN Allocation Policy Configuration

```eos
!
vlan internal order ascending range 1006 1199
```

## IP IGMP Snooping


## Logging

No logging settings defined
``````

We should at least output something, like: 
- igmp defaut configuration is applied 
- or a table that shows with all vlans and igmp snooping enabled
- or a table that shows with all vlans and igmp snooping default configuration 

## Role or Module Name

role `eos_cli_config_gen`

**Comment by onurgashi** [comment]
Merged with PR #519
