### ISSUE TITLE
Feat(eos_cli_config_gen): Add support for `dhcp server`

### ISSUE THREAD

**Issue by haylinmoore** [aristanetworks/ansible-avd#3007]
### Enhancement summary

Add support for `dhcp server` related options in EOS

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Running a DHCP server on-device

### Describe the solution you would like

```
dhcp_server:
    debug:
        file: str
    disabled: bool
    dns:
        domain:
            name:
                ipv4: str
                ipv6: str
        server:
            ipv4: str[]
            ipv6: str[]
    lease:
        ipv4:
            days: int (0-2000)
            hours: int (0-23)
            minutes: int (0-59)
        ipv6:
            days: int (0-2000)
            hours: int (0-23)
            minutes: int (0-59)
     subnets:
         - cidr: str
            default-gateway: str
            name: str
            lease: 
                days: int (0-2000)
                hours: int (0-23)
                minutes: int (0-59)
            range:
                start: str
                end: str
```

### Describe alternatives you have considered

eos_cli

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
@hamptonmoore Check if everything needed is covered by #3269. And if not, rewrite the text here to only point out the missing pieces. Otherwise close.

**Comment by Shivani-gslab** [comment]
@hamptonmoore could you please confirm on this one. #3269

**Comment by ClausHolbechArista** [comment]
I believe this has been implemented. If not, please reopen and point to the missing pieces. Thanks.
