### ISSUE TITLE
Fix(eos_designs): Doc typo in input variables

### ISSUE THREAD

**Issue by xaviramon** [aristanetworks/ansible-avd#3019]
### Issue Summary

There is a typo in the eos_designs/docs/input-variables.md file at line 930:
`The network services variabless`
Should be:
`The network services variables`

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
https://avd.arista.com/devel/roles/eos_designs/docs/input-variables.html##
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
push the fix to PR #3001
