### ISSUE TITLE
Make yaml_templates_to_facts more generic

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#3020]
### Enhancement summary

Make yaml_templates_to_facts a generic plugin to render facts base on Jinja templates or Python modules as described in the docs.
Remove references to AVD facts as these are now managed on a separate plugin

### Which component of AVD is impacted

plugins

### Use case example

For people not using `eos_designs` role, it becomes confusing when trying to use the plugin to render facts and structured data for `eos_cli_config_gen`. I have a role that started from an older version of eos_designs, and tries to render switch facts with Jinja. The plugin was working on AVD 3.8 but AVD 4.1.0 breaks it as it now overwrites my rendered switch facts with an empty dictionary

### Describe the solution you would like

Revert the plugin `yaml_templates_to_facts` to be more generic and do exactly what described in the plugin documentation. Since AVD facts for `eos_designs` have been now moved to `eos_designs_structured_data`, it should be possible to have `yaml_templates_to_facts` as a more general purpose action plugin.

### Describe alternatives you have considered

Forking the plugin (would like to avoid)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
To avoid breaking changes in 4.x I have created a simple workaround allowing a new argument `set_switch_fact: <bool, default true>` which you can set to `false`. Please test out my PR and let me know if it solves it short term. We can look into building a new more generic plugin over time.

**Comment by gusmb** [comment]
> To avoid breaking changes in 4.x I have created a simple workaround allowing a new argument `set_switch_fact: <bool, default true>` which you can set to `false`. Please test out my PR and let me know if it solves it short term. We can look into building a new more generic plugin over time.

Yes, this workaround solves my issue

**Comment by gusmb** [comment]
Not sure if I am missing something, but once I refactor dict of dicts into list of dicts, the lists are not being merged correctly by primary key, but replaced. For instance,. Ethernet interfaces list for underlay gets overwriten by the Ethernet interfaces list for endpoints.

**Comment by gusmb** [comment]
> Not sure if I am missing something, but once I refactor dict of dicts into list of dicts, the lists are not being merged correctly by primary key, but replaced. For instance,. Ethernet interfaces list for underlay gets overwriten by the Ethernet interfaces list for endpoints.

Update: It actually works, I had a template which I hadn't refactored yet and that was causing the overwrite.

**Comment by gusmb** [comment]
This is actually a good use case for this plugin, which makes it unique to AVD, independent from eos_designs. The ability to template random facts that are compliant with the eos_cli_config_gen schema, and the  plugin knows how to merge the data properly

**Comment by gusmb** [comment]
> > Not sure if I am missing something, but once I refactor dict of dicts into list of dicts, the lists are not being merged correctly by primary key, but replaced. For instance,. Ethernet interfaces list for underlay gets overwriten by the Ethernet interfaces list for endpoints.
> 
> Update: It actually works, I had a template which I hadn't refactored yet and that was causing the overwrite.

@ClausHolbechArista  List items do not get merged by primary key correctly. If I try adding an ethernet interface as switched on endpoints, and later on declare it as routed on network_services, I end up with 2 entries in the list and I get a warning as duplicated key. Is there a way to merge list items by list keys according to the schema?

Also tried setting the list_merge: append_rp, to see if at least the existing item would get overwritten, but it doesn't, I still ended up with the 2 items in the list. Ideally, I would expect that the default behavior would be a true merge of list items based on the output schema, considering the list unique keys as a way to identify the items to merge together

**Comment by ClausHolbechArista** [comment]
The default behavior should indeed be to merge on the output schema. So you need to set the output schema id to "eos_cli_config_gen" for this to work. You also need to _not_ use replace as list_merge strategy.
If you have these points covered, something else is going on. We can discuss and troubleshoot on zoom when you have time.

**Comment by gusmb** [comment]
I guess I'm just missing setting the output schema correctly, but I'm struggling to find where I should do that

**Comment by ClausHolbechArista** [comment]
> I guess I'm just missing setting the output schema correctly, but I'm struggling to find where I should do that

It is an argument for `yaml_templates_to_facts`:
```yaml
  output_schema_id:
    description: ID of AVD Schema for output data. Used for automatic merge of data.
    required: false
    type: str
    choices: [ "eos_cli_config_gen", "eos_designs" ]
```

**Comment by gusmb** [comment]
> > I guess I'm just missing setting the output schema correctly, but I'm struggling to find where I should do that
> 
> It is an argument for `yaml_templates_to_facts`:
> 
> ```yaml
>   output_schema_id:
>     description: ID of AVD Schema for output data. Used for automatic merge of data.
>     required: false
>     type: str
>     choices: [ "eos_cli_config_gen", "eos_designs" ]
> ```

Thanks, now it is working as expected :)

The docs need to be updated, as they don't mention anything about the output schema ID: https://avd.sh/en/devel/plugins/index.html#yaml-templates-to-facts
