### ISSUE TITLE
Documentation: Make sure Ansible plugins are properly documented and use this to keep our doc up to date

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3034]
### Enhancement summary

Probably multiples PRs to go through to achieve this

### Which component of AVD is impacted

plugins, others

### Use case example

when updating yaml_template_to_fact inputs, the avd.sh doc is not updated automatically which can lead to misleading doc

### Describe the solution you would like

go through doc of all plugins in order to leverage this for avd doc

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Maybe we can remove the static docs of plugins and use antsibull generated artifacts for those components?
