### ISSUE TITLE
utils/eos_designs_facts.py -- vlans="all" but mode is not set (to "trunk")

### ISSUE THREAD

**Issue by lcphill** [aristanetworks/ansible-avd#3074]
### Issue Summary

This issue is the result of code introspection versus playbook execution.

Here: https://github.com/aristanetworks/ansible-avd/blob/v3.8.6/ansible_collections/arista/avd/plugins/plugin_utils/eos_designs_facts.py#L771 

If vlans is "all" but mode is not "trunk", then vlans is hard wired to '1'.

Is this the correct/intended behavior?

The above is repeated further below in the network_ports for loop.

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

None

### Steps to reproduce

```shell
This is a la code introspection, with link provided in description.
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
The default behavior for vlans on EOS is `all` if it is a trunk and `1` if it is an access port. So this is an attempt to mirror that behavior. Have you seen any issues causing you to inspect the code?

**Comment by lcphill** [comment]
Hi, I suspect vlans being 'all' and mode not 'trunk' would be a mis-configuration? (this seems obvious, but just checking).
I am working with a (mutual) customer and I am attempting to ascertain semantics of inventory as supplied to eos designs.

addendum: I am not adept at github ticket handling, in particular, the etiquette of closing a ticket (the practice is seemingly inconsistent from repos to repos). I presume that you can close this ticket from your end? Thank you.

**Comment by ClausHolbechArista** [comment]
You are correct that `vlans: all` should not be a valid value in case of `mode != "trunk"` but we don't have checks for that.

We could consider emitting an error for this invalid case, but currently we have decided to ignore it silently. 

No worries on the issue. I can close it from here.

Thank you for your inquiry, and feel free to come back any time.
For questions/concerns that are not specifically an issue (bug/feature request) you can use github discussions.
