### ISSUE TITLE
(eos_designs): Add key to indicate MLAG port channel manually

### ISSUE THREAD

**Issue by danieltmurphy** [aristanetworks/ansible-avd#3082]
### Enhancement summary

We need a way to selectively make a port-channel an MLAG port-channel instead of solely relying on eos_designs to automatically detect if a port-channel should or should not be an mlag port-channel.

### Which component of AVD is impacted

eos_designs

### Use case example

From an AVD perspective: when a user only wants to generate config for access interfaces and doesn't want to rely on AVD switch facts being accurate in order to determine whether or not a port-channel towards an endpoint device should be an MLAG port-channel or not
.
From a networking perspective: when a user wants to create a port-channel to an end device but doesn't want the port-channel to be an mlag port-channel.

### Describe the solution you would like

Add a key that indicates that the user would want to set an mlag port channel manually, rather than having avd detect it.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Hi Daniel

Since this would be an override of the built-in logic, I think this would be a good use case for `structured_config` under the adapter `port_channel` key.

You should be able to add:

```yaml
...adapter config...
    port_channel:
      mode: active
      structured_config:
        mlag: <mlag id>
```
