### ISSUE TITLE
Scheduled GH workflows should not run on forked repositories

### ISSUE THREAD

**Issue by ankudinov** [aristanetworks/ansible-avd#3088]
### Enhancement summary

Scheduled GH workflows should not run on forked repositories

### Which component of AVD is impacted

others

### Use case example

-

### Describe the solution you would like

add `if: github.repository_owner == 'aristanetworks'` condition to scheduled workflows or similar

### Describe alternatives you have considered

-

### Additional context

-

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Resolved by #3335
