### ISSUE TITLE
SVI in overlay MTU knob

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#310]
- Role enhancement

This is required when customer would like to introduce jumbo MTU for overlay services that communicate in different subnets, or in other words inter VLAN routing.

interface vlan 10
mtu 9000

We'd like to have a knob similar to the transport links

```
# Update p2p mtu 9000 -> 1500
p2p_uplinks_mtu: 1500
```

Using static config or custom role as workaround for now.

**Comment by ClausHolbechArista** [comment]
This is already working, since variables defined under SVIs are carried directly to vlan_interfaces in eos_cli_config_gen.
I have tested with:
```tenants:
  # Tenant A Specific Information - VRFs / VLANs
  Tenant_A:
    mac_vrf_vni_base: 10000
    vrfs:
      Common_VRF:
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.255.1.0/24
        svis:
          12:
            name: Tenant_A_OP_Zone_Test
            tags: [opzone]
            enabled: true
            ip_subnet: 172.16.112.0/24
            mtu: 9000
```
resulting in:
```
interface Vlan12
   description Tenant_A_OP_Zone_Test
   mtu 9000
   vrf Common_VRF
!
```

**Comment by onurgashi** [comment]
I guess we can simply just add documentation for this and mark it resolved @titom73 ?

**Comment by onurgashi** [comment]
Already there, closing.
