### ISSUE TITLE
arista.avd.inventory_to_container allows cv_configlets to reference AVD-generated configlet and duplicate entries

### ISSUE THREAD

**Issue by alexeygorbunov** [aristanetworks/ansible-avd#3107]
### Issue Summary

Hey AVD team!
*arista.avd.eos_config_deploy_cvp* supports *cv_configlets* knob (to attach additional configlets to device).
This knob is processed by *arista.avd.eos_config_deploy_cvp* which engages *arista.cvp.cv_device_v3* which eventually uses *__get_reordered_configlets_list(configlets_attached, device.configlets)* to prepare new stack of configlets for target device.
Current overall workflow allows users to:
1. Specify AVD-generated configlet inside *cv_configlets* - effectively leading to the state where AVD-generated configlet stack contains multiple instances of the AVD-generated configlet (as *cvp-devices-v3.j2* always pushes AVD-generated configlet to the bottom).
2. Specify any other configlets multiple times within *cv_configlets*, leading to AVD sending to CVP configlet stack with possible duplicates.

In both cases - actual order of applying those dupllicated configlets to target device depends on the CVP behavior (when it processes this configlet stack with duplicated configlets).

### Which component(s) of AVD impacted

eos_config_deploy_cvp

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
0. define the following cv_configlets knob (at any level where it's applied to "device1")


cv_configlets:
  devices:
    device1:
      - AVD_device1
      - another_device1_configlet (this is a side configlet already existing in CVP)
```

1. generate target configuration for "device1"

2. this creates intended cli config "./intended/configs/device1.cfg"

3. run playbook&task that uses "arista.avd.eos_config_deploy_cvp" with vars:

```
      vars:
        configlets_prefix: AVD
        container_root: BBB
        cv_collection: v3
        state: present
```

4. This generates the following stack of configlets for device1:

```
"CVP_VARS":
  "CVP_CONTAINERS": {...}
  "CVP_DEVICES":
     ...
     - "configlets":
       - "AVD_device1"
       - "another_device1_configlet"
       - "AVD_device1"
      "fqdn": "device1"
      "parentContainerName": "XXX"
```

5. This stack of 3 configlets is then compared with the current list of configlets applied to device1 on CVP. If this configlets are already present in currently-applied stack -> they are effectively moved to the end of the stack/list. All 3 configlets (including 2 duplicated) end up in the list eventually pushed to CVP.

```
configlets_reordered_list = self.__get_reordered_configlets_list(
   configlets_attached, device.configlets
)

---

    def __get_reordered_configlets_list(
        self, configlet_applied_to_device_list, configlet_playbook_list
    ):
        new_configlets_list = []
        for configlet in configlet_playbook_list:
            new_configlet = self.__get_configlet_info(configlet_name=configlet)
            if new_configlet is None:
                error_message = (
                    "The configlet '%s' defined to be applied on the device does not exist on CVP.",
                    str(configlet),
                )
                MODULE_LOGGER.error(error_message)
                self.__ansible.fail_json(msg=error_message)

            # If the configlet is not applied, add it to the new list
            if configlet not in [x.name for x in configlet_applied_to_device_list]:
                new_configlets_list.append(new_configlet)

            # If the confilet is already applied, remove it from the main list and add it to the end of the new list
            else:
                MODULE_LOGGER.debug(
                    "Removing the configlet %s from the current configlet list and adding it to the new list.",
                    str(configlet),
                )
                for x in configlet_applied_to_device_list:
                    if x.name == configlet:
                        configlet_applied_to_device_list.remove(x)
                        new_configlets_list.append(new_configlet)
        configlets_attached_get_configlet_info = [
            self.__get_configlet_info(configlet_name=x.name)
            for x in configlet_applied_to_device_list
        ]
        # Joining the 2 new list (configlets already present + new configlet in right order)
        return configlets_attached_get_configlet_info + new_configlets_list
```

Overall either device_tools.py (function __get_reordered_configlets_list) or cvp-devices-v3.j2 should:
* make sure that AVD-generated configlet is not referenced inside cv_configlets
* cv_configlets does not contain duplicated configlets for any devices/containers (by converting configlets_reordered_list to set ?).
* if existing stack of device's configlets contains reconcile configlet - AVD should place it in the tail of the configlets_reordered_list otherwise proposed new list will contradict configlet order logic that CVP follows)
* "cv_configlets"-related documentation on avd.sh should also explicitly state that all side device-level configlets defined under "cv_configlets" will be applied before AVD-generated configlet and that there is no way to overwrite this order.
```


### Relevant log output

_No response_

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
I agree that it would be useful to be able to have the AVD configlet applied before some other static configlet, but that is not possible (in a consistent way) today because of the template as you point out.
~We should document the current behavior, but we cannot change it in a minor release, as reordering config could be a breaking change.~ Since CVP only uses the first entry, we can implement a fix that prevents the duplicate entry at the end of the stack with no impact.
