### ISSUE TITLE
Exclude interfaces from `eos_validate_state` report

### ISSUE THREAD

**Issue by slappey-ibkr** [aristanetworks/ansible-avd#3113]
### Enhancement summary

My engineering team would like to exclude interfaces from the state validation report.  An example would be at a campus site.  I used network_ports to configure a large range of generic user access ports.  The engineering team would like to exclude the user access ports from the validation report.  The interfaces are not critical.  Currently, the report is full of 200+ ethernet interfaces which show up as failed.  

### Which component of AVD is impacted

eos_validate_state

### Use case example

An example would be at a campus site.  I used network_ports to configure a large range of generic user access ports.  The engineering team would like to exclude the user access ports from the validation report.  The interfaces are not critical.  Currently, the report is full of 200+ ethernet interfaces which show up as failed.  

### Describe the solution you would like

Introduce `eos_validate_state_exclude_interfaces` variable.  In `interface_state.yml` tasks file, add `( ethernet_interface.name in eos_validate_state_exclude_interfaces ) or ` to the beginning of the assertion in the `Validate Ethernet interfaces state` task.  In `generate_state_report_results.j2` change `if not result.ethernet_interface.shutdown` to `elif` and add `if result.ethernet_interface.name in eos_validate_state_exclude_interfaces` above it with `test_description: "Ethernet Interface Excluded From Validation".

### Describe alternatives you have considered

Add `validate_state: <bool>` to the structured config under every interface allowing developers to have full control.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Hi @slappey-ibkr

Thank you for your enhancement request and thoughts on this. It is a really good idea to provide some means of excluding interfaces from the tests.

Instead of having to maintain another list of interfaces, I would prefer to introduce some variable in the `eos_designs` data models, that will be part of the structured config and picked up by `eos_validate_state`. Maybe `validate_state: <bool; default=true>` or something. I think we should try to avoid negations like `exclude_` or `skip_`.


Would that work for you?


Examples:
```yaml
port_profiles:
  - profile: <name>
    validate_state: false
 
network_ports:
  - ...
    validate_state: false

servers:
  - name: <name>
    adapters:
      - ...
        validate_state: false
```

We can always add the same knob in other areas as the need arises.

**Comment by slappey-ibkr** [comment]
I like it.  I would just set `validate_state: false` under the user access port definition.  Very easy.

**Comment by ClausHolbechArista** [comment]
@carl-baillargeon

**Comment by carl-baillargeon** [comment]
Hello @slappey-ibkr

Thank you for your patience.

We are actually working on a major refactor of the `eos_validate_state` role, integrating it with the ANTA Python framework as the core engine of the validation.

The feature you requested has been merged in the `devel` branch and will make it to AVD 4.6  (will be released soon).

You can now use `eos_validate_state` in ANTA mode, supporting this new feature. Please refer to https://avd.sh/en/devel/roles/eos_validate_state/ANTA-Preview.html

Let us know if you have any questions.

Thank you
