### ISSUE TITLE
Allow for IPv6 Addresses in Network Services 

### ISSUE THREAD

**Issue by theotherguy2175** [aristanetworks/ansible-avd#3121]
### Enhancement summary

With this current config:
svis:
```
          - id: 308
            # SVI Description
            name: VLAN308
            enabled: true
            ip_address_virtual: 10.x.x.x/27
```
            
  There is no option for IPv6 address(es). Is it possible to add this feature?

### Which component of AVD is impacted

eos_designs

### Use case example

To add Dual Stack capability for managing network services for VRFs

### Describe the solution you would like

To add Dual Stack capability for managing network services for VRFs

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Please make sure to use code blocks with tripple back tick like ``` when you include yaml data or code. It makes it much easier to read the issue.

We _do_ have options for IPv6 already. Please refer to the documentation here https://avd.arista.com/4.3/roles/eos_designs/docs/input-variables.html#network-services-vrf-svis-configuration, where you can find `ipv6_address_virtuals`, which accepts a list of addresses.
