### ISSUE TITLE
Support of route-target route-map

### ISSUE THREAD

**Issue by mmaaloul** [aristanetworks/ansible-avd#3127]
### Enhancement summary

Under router_bgp/vrf stanza, the eos_cli_config_gen schema doesn't support route-target route-map:

"The route-target route-map command allows the user to export and import route target extended community lists from one VRF to another using route maps.

Syntax
route-target {import | export} [evpn | vpn-ipv4 | vpn-ipv6] route-map RM"

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

vrf STK-HUB-SMT80-001
      rd 10.64.4.18:42001
      route-target import evpn 42001:1
      route-target import evpn 42001:42001
      route-target export evpn 42001:2
      route-target export evpn 42001:42001
      route-target import evpn route-map RM_DENY-DEFAULT  <<<<<<<<<<<
     ...

### Describe the solution you would like

1/ In eos_cli_config_gen schema, under router_bgp/vrfs/route_targets/import or export, in addition to "address_family" and "route_targets" properties, we add a new property (key: "route_map", value: "string")

2/ In jinja2 template "router-bgp.j2", make the relevant changes

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
We need this yes. For now I believe others have just entered `"route-map RM_DENY-DEFAULT"` under `additional_route_targets`.
