### ISSUE TITLE
Feat(eos_designs): Add `custom_foo` keys for large default

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3152]
### Enhancement summary

The `platform_settings` and `node_typekeys` keys have large default (as in many lines of yaml) and today the only way to overwrite part of them while keeping the rest of the default is to fully copy the default and modify accordingly

This issue is for adding two keys `custom_platform_settings` and `custom_node_type_keys` to be prepended to the AVD defaults when defined to avoid copying over everything.

prepended because this way if you overwrite some existing default, because we match in order, it would take precedence.

NOTE: if both `custom_platform_settings` and `platform_settings` are defined by the user in the playbook, then we would prepend `custom_` to the user defined `platform_settings` though this is a quite convoluted way of working and only overriding `platform_settings` should be sufficient

NOTE: could be implemented also for connected_endpoints_keys and network_services_keys but it is less necessary because the defaults are very small

### Which component of AVD is impacted

eos_designs

### Use case example

cf summary

### Describe the solution you would like

cf summary

### Describe alternatives you have considered

copying over large defaults

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by jonxstill** [comment]
Happy to take a look at this this week/next
