### ISSUE TITLE
Automatically set software-forwarding SFE when configuring EVPN multicast in tenants

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#3153]
### Enhancement summary

As discussed, with the following configuration at the fabric level:
_underlay_multicast: true_

And tenants files set with EVPN multicast:
_evpn_l2_multicast: true_

SFE was not configured:
```
router multicast
   ipv4
      routing
```
I required configuring at the fabric level:
_evpn_multicast: true_

This can be enhanced to set "software-forwarding sfe" when EVPN multicast is set already in the tenant files.

### Which component of AVD is impacted

eos_designs

### Use case example

L2 EVPN multicast: https://www.arista.com/en/support/toi/eos-4-26-0f/14669-layer-2-multicast-evpn

### Describe the solution you would like

Automatically set software-forwarding SFE when EVPN multicast is enabled in the tenant files.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by carlbuchmann** [comment]
We should raise that evpn_multicast: true is required, similar to the behavior of evpn_multicast: true requires underlay_multicast: true
