### ISSUE TITLE
Inband ZTP Support in EOS Designs

### ISSUE THREAD

**Issue by jrecchia1029** [aristanetworks/ansible-avd#3158]
### Enhancement summary

Need the ability to automate the configuration that enables switches to perform inband ZTP.

This configuration gets applied on switches upstream of the switches undergoing ZTP.

There are several ways to accomplish this.

1.  Port-Channel from upstream device to downstream devices configured with `port-channel lacp fallback static` with either the ztp vlan advertised as an lldp tlv or the ztp vlan configured as the native vlan.
2.  Port-Channel from upstream device to downstream configured with `port-channel lacp fallback individual` and port-channel member interfaces configured as trunk interfaces with either the ztp vlan advertised as an lldp tlv or the ztp vlan configured as the native vlan.
3. Port-Channel from upstream device to downstream configured with `port-channel lacp fallback individual` and port-channel member interfaces configured as access interfaces accessing the ztp vlan.

### Which component of AVD is impacted

eos_designs

### Use case example

When configuring a campus fabric network with AVD through CVP, the devices need some way to ZTP themselves to CVP.  This requires connectivity through the data plane of the campus. 

### Describe the solution you would like

An `inband_ztp` key that indicates that an upstream switch needs to configure its downstream interfaces with the appropriate configuration to allow for the downstream switch to perform inband ztp.

### Describe alternatives you have considered

Using structured_config keys to generate the necessary configuration.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by jrecchia1029** [comment]
Adding `inband_ztp_interfaces` under `default_interfaces` could allow users to be specific when enabling ZTP for downstream devices.  This key should also be configurable under node settings for unique, one-off topologies.

**Comment by jrecchia1029** [comment]
Add a node setting `deploy_via_inband_ztp` that indicates whether or not the node will be deployed through inband ztp. If set to True, this will enable an inband ztp configuration from this node's upstream devices and mlag peer.

**Comment by jrecchia1029** [comment]
Methods mentioned in Enhancement Summary for configuring inband ztp will be options for configuration later down the road but initially will only support 1 method (Tbd - but most likely the Port-Channels configured with `port-channel lacp fallback individual` with member interface configured as an access interface for the inband management interface).

**Comment by carlbuchmann** [comment]
We may want to consider the issue raised in #3400 when we develop this feature.

**Comment by jrecchia1029** [comment]
The model being using for inband ZTP in the campus studio is

```
inband_ztp:
  lacp_fallback:
    mode: <individual>
    timeout: <int;| default=30>
  interface_ztp_method: <access>

default_interfaces:
  - types: [ spine, l3leaf ]
    platforms: [ "7050[SC]X3", vEOS.*, default ]
    inband_ztp_interfaces: []
```

This could be simplified even further since we are only offering one ztp method currently which is the combination of fallback_mode: individual and interface_ztp_method: access.  So I'm wondering if we want to just condense this down to a single `enable_inband_ztp` knob.  The inband ztp interfaces are typically just the downstream interfaces and mlag peer interfaces but I'm not sure we want to automatically assume those downstream/mlag peer interfaces should always be the inband_ztp_interfaces as well.  Although maybe we do now that I think about it a bit more.

**Comment by ClausHolbechArista** [comment]
Until we have other options we can just expose:
```
inband_ztp:
  lacp_fallback:
    timeout: <int; default=30>

default_interfaces:
  - types: [ spine, l3leaf ]
    platforms: [ "7050[SC]X3", vEOS.*, default ]
    inband_ztp_interfaces: []
```

And *only* configure inband_ztp on the interface you have in the list if either of these are true:
- The interface is a downlink interface which is part of a l2 port-channel.
- The interface is an mlag peer interface which is part of the mlag peer port-channel.
- The interface is not used for anything in eos_designs (downlink, uplink, mlag, l3_interfaces or connected endpoints).

If the interface is not covered by any of the above rules, we will ignore the interface, and *not* configure it for inband ztp.

This way you can "blindly" set all your interfaces for inband ztp.

Later we can offer tweaks for this behavior.

**Comment by jrecchia1029** [comment]
Plan is now to accomplish inband ztp by using a knob `inband_ztp_parent` which will configure ethernet interfaces as access ports in the inband mgmt vlan and members of a port-channel towards neighbor with lacp fallback individual mode configured.  Doing away with the `inband_ztp_interfaces` key for now.
