### ISSUE TITLE
Fix(eos_validate_state): When an interface is shutdown, `VerifyReachability` tests are still created for the peer IP address on that interface.

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3182]
When an interface is shutdown, I can still see `VerifyReachability` tests created for the peer IP address on that interface. 

This is an existing behaviour in current eos_validate_state that has caused confusion/grip about false positives before as well.

_Originally posted by @chetryan in https://github.com/aristanetworks/ansible-avd/issues/3171#issuecomment-1740960416_

**Comment by carl-baillargeon** [comment]
Fixed in #3272
