### ISSUE TITLE
Fix(eos_validate_state): When an interface is shutdown, the BGP peer check `VerifyBGPSpecificPeers` is still created for the peer on that interface.

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3183]
Similarly - when an interface is shutdown, the BGP peer check `VerifyBGPSpecificPeers` is still created for the peer on that interface. Is this in scope to be solved in this PR ? Without this, we would still have false positive when some devices are not still deployed.

_Originally posted by @chetryan in https://github.com/aristanetworks/ansible-avd/issues/3171#issuecomment-1740985553_

**Comment by carl-baillargeon** [comment]
Fixed in #3272
