### ISSUE TITLE
Feat(eos_cli_config_gen): EOS 4.30 system l1 defaults

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3202]
### Enhancement summary

In EOS >= 4.30 the following l1 config is being printed by default
```
leaf1(config-system-l1)#show active
system l1
   unsupported speed action error
   unsupported error-correction action error
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

when booting up an EOS device running >= 4.30 the system l1 config above shows up in running-config

### Describe the solution you would like

Need to implement the knobs and to define the default behavior for AVD.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Beware that this will not work on older EOS versions, so I think we should only implement the knobs, but not produce any config by default.
