### ISSUE TITLE
Allow for Not setting QSFP default mode

### ISSUE THREAD

**Issue by Kennochas** [aristanetworks/ansible-avd#3246]
### Enhancement summary

Right now, you are forced to set qsfp default-mode if you have the default config generation enabled.

We leave this disabled on our hardware, as we have 40gs, 100gs, etc.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

We do not set the QSFP default mode.

### Describe the solution you would like

Allow for us to remove it, which probably means getting it out of the default config.

Its not a problem to have it to default being there, but the ability to not set it would be useful.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Closing this one in favor of duplicate #3261, since that one contains the full story/background. Thanks
