### ISSUE TITLE
Service - unsupported-transceiver 

### ISSUE THREAD

**Issue by Kennochas** [aristanetworks/ansible-avd#3253]
### Enhancement summary

We would like to be able to set:
```
service unsupported-transceiver {{ name }} {{ secret }}
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

We use unsupported trancievers

### Describe the solution you would like

Something akin to:
```
unsupported-transceiver:
   name: {{ company name }}
   key: {{ secret }}
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
already implemented, but kept out of the docs for non-technical reasons.

**Comment by Kennochas** [comment]
Hey thanks, I found it. 

Sneaky sneaky :)
