### ISSUE TITLE
 arista.cvp.cv_task_v3 dependency: arista.cvp.cv_container_v3

### ISSUE THREAD

**Issue by arista-matt** [aristanetworks/ansible-avd#3260]
`arista.cvp.cv_task_v3` depends upon `arista.cvp.cv_container_v3`'s `cvp_container_results`, but doesn't share the `containers` tag. If the `containers` tag is skipped,  `arista.cvp.cv_task_v3` will fail due to missing `cvp_container_results`.

https://github.com/aristanetworks/ansible-avd/blob/6c687827de2cf9fa4e6aac2ff09e554051e7c243/ansible_collections/arista/avd/roles/eos_config_deploy_cvp/tasks/v3/present.yml#L31-L37

**Comment by ClausHolbechArista** [comment]
Good catch. Thank you for reporting this. Could you also submit a fix for this? Thanks.

**Comment by arista-matt** [comment]
Additional error information

When using the [documented](https://avd.arista.com/4.4/roles/eos_config_deploy_cvp/index.html?h=skip+tags#run-module-with-different-tags) **--skip-tags** option: `ansible-playbook playbook.to.deploy.with.cvp.yml --skip-tags "containers"
` the error below occurs:


```
TASK [arista.avd.eos_config_deploy_cvp : Execute pending tasks on cvaas] *******
Friday 10 November 2023  12:46:54 +0000 (0:00:00.040)       0:00:06.621 ******* 
Friday 10 November 2023  12:46:54 +0000 (0:00:00.040)       0:00:06.621 ******* 
fatal: [cvaas]: FAILED! => 
  msg: |-
    The conditional check 'cvp_container_results.taskIds | length > 0' failed. The error was: error while evaluating conditional (cvp_container_results.taskIds | length > 0): 'cvp_container_results' is undefined. 'cvp_container_results' is undefined
  
    The error appears to be in '/root/.ansible/collections/ansible_collections/arista/avd/roles/eos_config_deploy_cvp/tasks/v3/present.yml': line 31, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: "Execute pending tasks on {{ inventory_hostname }}"
      ^ here
    We could be wrong, but this one looks like it might be an issue with
    missing quotes. Always quote template expression brackets when they
    start a value. For instance:
  
        with_items:
          - {{ foo }}
  
    Should be written as:
  
        with_items:
          - "{{ foo }}"
```

**Comment by ClausHolbechArista** [comment]
We need to add a check to the apply task to check if the variable is defined. That will be simpler and safer than changing the tags.
