### ISSUE TITLE
Post EOS 4.26, QSFP default mode shouldn't be forced to 4x10G

### ISSUE THREAD

**Issue by mmaaloul** [aristanetworks/ansible-avd#3261]
### Enhancement summary

1/ Current AVD behaviour:
- Template "transceiver-qsfp-default-mode.j2" is configuring QSFP default mode to 4x10G unless we set "generate_default_config" to False
- But, setting this var to False is not only removing the QSFP default mode config...

2/ Current EOS behaviour:
- Starting from 4.26, the default beahviour changed for Trident and Tomahawk based equipments: the default mode is 40G instead of 4x10G (bug #90187)
- The "no transceiver qsfp default-mode 4x10G" is now possible but only for Trident/Tomahawk (I confirmed in lab it is not effective on Jericho+ while effective on Trident3... I am using EOS 4.28.3M)

3/ Target AVD behaviour:
- Introducing a new var of type boolean (example "qsfp_default_mode_channelized")
- If True, configure "transceiver qsfp default-mode 4x10G"
- If False, configure nothing
- Since we don't used conditionals of type "if platform" or "if version", it is up to the user to ensure it is set to True for platforms other than Trident/Tomahawk and for EOS version lower than 4.26... 

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Trident/Tomahawk based device running 4.26+ has qsfp default mode 40G

### Describe the solution you would like

- Introducing a new var of type boolean (example "qsfp_default_mode_channelized")
- If True, configure "transceiver qsfp default-mode 4x10G"
- If False, configure nothing
- Since we don't used conditionals of type "if platform" or "if version", it is up to the user to ensure the var is set to True for platforms other than Trident/Tomahawk and for EOS version lower than 4.26... 

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Duplicate of #3246

**Comment by ClausHolbechArista** [comment]
Keeping this one because of the better description / background.
