### ISSUE TITLE
Test: Address warning in ansible when running molecule

### ISSUE THREAD

**Issue by ankudinov** [aristanetworks/ansible-avd#3270]
### Issue Summary

Following error message is observed when running molecule tests for `eos_designs_unit_tests`.
Possibly other scenarios as well.

```
[WARNING]: Invalid characters were found in group names but not replaced, use
-vvvv to see details
```

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
molecule converge --scenario-name eos_designs_unit_tests
```

### Relevant log output

```shell
INFO     Running from /workspaces/ansible-avd/ansible_collections/arista/avd : ansible-galaxy collection install -vvv --force /workspaces/ansible-avd/ansible_collections/arista/avd
INFO     Running eos_designs_unit_tests > syntax
[WARNING]: Invalid characters were found in group names but not replaced, use
-vvvv to see details

playbook: /workspaces/ansible-avd/ansible_collections/arista/avd/molecule/eos_designs_unit_tests/converge.yml
INFO     Running eos_designs_unit_tests > create
[WARNING]: Invalid characters were found in group names but not replaced, use
-vvvv to see details
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Change all ansible groups to be upper case with underscores. Maybe require adjustments of `fabric_name` variables as well. There should be *no* changes to configs from this.
