### ISSUE TITLE
Refactor(eos_cli_config_gen)!: Redo the model for additional-paths in BGP

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3279]
As discussed - this model for additional-paths MUST
1/ be revisited for 5.0
2/ be made a defs in schema to reuse it everywhere it is needed

This will ensure consistency in every places we use it

_Originally posted by @gmuloc in https://github.com/aristanetworks/ansible-avd/issues/3278#issuecomment-1772517013_

**Comment by ClausHolbechArista** [comment]
The whole model should be rewritten to not have multiple booleans where only one is used at any time. Instead it should be a string with valid values or similar.
