### ISSUE TITLE
l2_mtu on port-channel in eos_cli_config_gen role not working

### ISSUE THREAD

**Issue by rradim** [aristanetworks/ansible-avd#3290]
### Issue Summary

Hello,

using version 4.4.0

it seems to me that l2_mtu on port channel in eos_cli_config_gen is not working. I have the l2_mtu set in connected endpoint yaml, once I use playbook to build intended config, i can see that its in structured config:

<code>
- name: Port-Channel102
  type: switched
  shutdown: false
  service_profile: QPROF-CUST-MULTI-1
  mode: trunk
  l2_mtu: 2000
  vlans: XXXX
  spanning_tree_portfast: edge
  storm_control:
    broadcast:
      level: '1000'
      unit: pps
    multicast:
      level: '10'
      unit: pps
    unknown_unicast:
      level: '1000'
      unit: pps
  evpn_ethernet_segment:
....
</code>

but in cli config l2_mtu is not configured...when the same is used on non-port channel port => it works as expected.

<code>
interface Port-Channel102
   no shutdown
   switchport
   switchport trunk allowed vlan XXXX
   switchport mode trunk
   evpn ethernet-segment
....
   spanning-tree portfast
   service-profile QPROF-CUST-MULTI-1
   storm-control broadcast level pps 1000
   storm-control multicast level pps 10
   storm-control unknown-unicast level pps 1000
  </code>

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
1) edit l2_mtu in connected endpoints for endpoint with port-channel
2) run playbook to build config
3) check cfg for the switch
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Thank you for reporting this. I have submitted a fix also including some background of why we ended here :)
Let me know if you need this immediately of if it can wait for the next planned minor version in about 3-4 weeks.

**Comment by rradim** [comment]
Hello Claus,
Thanks a lot for quick fix.

we can wait till next release;)

Radim
