### ISSUE TITLE
It is better to have a possibility to customize the RD/RT of VRF

### ISSUE THREAD

**Issue by forcecity** [aristanetworks/ansible-avd#3296]
### Enhancement summary

For now, the RT/RD value can only be generated by vrf_id or vrf_vni. But in some customers' env, they normally use many different values, not just <vrf_id>:<vrf_id>. In case for the inter-communication with existing un-ruled vrfs, a flexible way to tune this value is necessary.

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen

### Use case example

For example, VRF xxx RD is VTEP IP:1001, RT evpn for both 1001:1 (1001 is an id we defined, not the vrf_id or vni). 

### Describe the solution you would like

Like mac-vrf using rd/rt_override. These 2 vars could help to generate any kinds of RD/RT values.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ankudinov** [comment]
Looking into that.

**Comment by bjmeuer** [comment]
Looking into it together with Petr
