### ISSUE TITLE
It is better to have a possibility to configure one vlan-aware-bundle for VLANs which belonged into different VRFs

### ISSUE THREAD

**Issue by forcecity** [aristanetworks/ansible-avd#3297]
### Enhancement summary

For now, the vlan-aware-bundle is only possible to include VLANs which belong to the same VRF. But in real life, SVIs which belonging to different VRFs, their VLANs could be in same evpn instance (mac-vrf) with same RD/RT (which could also be defined by network administrator). To intercommunication with this situation and also flexible usage. I suggest you could also add this feature. From the capability of the switch and principle, it should work.

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen

### Use case example

The configs would be like this:

In BGP sub-view:
vlan-aware-bundle service-vlans
      rd xxxx:yyyy
      route-target both xxxx:yyyy
      redistribute learned
      vlan 1007-1008,1301,1401,1496-1499,1780-1789,1799,2000-2001,2005-2008

For SVIs configs:
interface Vlan1799
   mtu 9100
   vrf OS
   arp gratuitous accept
   ip address virtual xx.xx.xx.xx/zz
!
interface Vlan1007
   mtu 9100
   vrf INET
   arp gratuitous accept
   ip address virtual aa.bb.cc.dd/ee

### Describe the solution you would like

Maybe "evpn_vlan_bundles" dictionary (in 4.4) could be referred by Network services VRF SVIs configuration (like Network services L2 VLANs configuration)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ankudinov** [comment]
Looking into that.

**Comment by xaviramon** [comment]
We should also consider the idea of having a bundle linked at the tenant level that can be used in all SVIs and l2vlans inside this tenant.

**Comment by bjmeuer** [comment]
Looking into it together with Petr

**Comment by forcecity** [comment]
After the testing, i just noticed that if i enabled common "evpn_vlan_aware_bundles" option to this new feature, i can't configure the single vlan service any more?
Regarding this feature is supported, and it is bound based on SVI/L2 VLAN, i think it is worth to support vlan-aware-bundle can be enable/disable based on SVI/L2VLAN. So people can configure the mac-vrf more flexible. Our scenario is under router bgp xxxx, we have both vlan-aware-bundle and single vlan configs to work for different situation, for example:
```
...
vlan 100
      rd 1.1.1.1:100
      route-target both 100:1
      redistribute learned
      no redistribute host-route
   !
   vlan 200
      rd 1.1.1.1:200
      route-target both 200:1
      redistribute learned
      no redistribute host-route
   !
   vlan-aware-bundle service-vlans
      rd 1.1.1.1:5001
      route-target both 5001:1
      redistribute learned
      vlan 2000-2008
...
```
Do you think i could open a new feature request or ?

**Comment by ClausHolbechArista** [comment]
@forcecity this ask is already tracked in #3355. Please add any missing nuances there. Thanks.
