### ISSUE TITLE
(eos_cli_config_gen) incomplete cli command with logging event storm-control unter interface ethernet

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#3299]
### Issue Summary

This is in reference to my own feature request #2781 and pr #2783:

We missed the mandatory keyword `discards` for the `logging event storm-control` under ethernet interfaces,
and the optional keyword `use-global`.

```
access(config)#int eth 5
access(config-if-Et5)#logging event ?
  congestion-drops  Drops due to congestion
  link-status       UPDOWN messages
  spanning-tree     Spanning tree messages
  storm-control     Configure storm-control

access-10-111-01.LAN.MU__17:32:03(config-if-Et5)#logging event storm-control ?
  discards  Discards due to storm control

access-10-111-01.LAN.MU__17:32:03(config-if-Et5)#logging event storm-control discards ?
  use-global  Use the global configuration
  <cr>
```

`logging event storm-control % Incomplete command` 

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
ethernet_interfaces:
  - name: Ethernet5
    logging:
      event:
        storm_control: true

will cause `logging event storm-control % Incomplete command`  in CVP CC and on cli.
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Since this never worked we can rename the key to storm_control_discards and fix the template.
I think the `use-global` option also applies to the other options, so unless you need it, you can leave that out. It should be added as a separate boolean like `logging.event.use_global`.

**Comment by kmueller68** [comment]
@ClausHolbechArista I assume that we can not use a single key for `logging.event.use_global` since it could be enabled per event individually.

```
access#show run all interface eth 5 | i logging event
   logging event link-status use-global
   default logging event congestion-drops
   logging event storm-control discards use-global
   logging event spanning-tree
   ```

```
ethernet_interfaces:
  - name: Ethernet5
    logging:
      event:
        use_global: <bool>
        link_status: <bool>
        congestion_drops: <bool>
        spanning_tree: <bool>
        storm_control: <bool>
   ```

**Comment by ClausHolbechArista** [comment]
Good point. Let's keep it out for now unless you need it.
