### ISSUE TITLE
Fix(eos_validate_state): ANTA jinja2.exceptions.UndefinedError: "hostvars['BB1']" is undefined

### ISSUE THREAD

**Issue by carl-baillargeon** [aristanetworks/ansible-avd#3309]
Need to add a check if the peer exists and is part of the inventory in the P2P reachability test.

**Comment by carl-baillargeon** [comment]
@philippebureau

**Comment by philippebureau** [comment]
We have seen this in both l3_edge and core_interfaces in the eos_designs role

**Comment by gmuloc** [comment]
`l3_edge` and `core_interfaces` use the same underlying code so it should be possible to `kill two bugs with one fix`

**Comment by carl-baillargeon** [comment]
Fixed in #3272
