### ISSUE TITLE
Extend CLI model for ip_security

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#3310]
### Enhancement summary

Add additional CLI for the following ip security config knobs:

* IKE policies
  *  IKE lifetime
  * encryption
  * DH group

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

More advanced configuration of IPSec within Campus deployments

### Describe the solution you would like

Extended J2 template to support those commands under IKE policies

### Describe alternatives you have considered

None

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gusmb** [comment]
I'll try to work on this, please assign this issue to me

**Comment by ClausHolbechArista** [comment]
Thank you for taking this on!

**Comment by gusmb** [comment]
Hi @ClausHolbechArista ,

I am getting some errors when trying to run the pre-commit inside the dev container:

```
Traceback (most recent call last):
  File "python-avd/scripts/build-schema-tables.py", line 13, in <module>
    from schema.generate_docs.mdtabsgen import get_md_tabs
  File "/workspace/ansible-avd/python-avd/pyavd/schema/generate_docs/mdtabsgen.py", line 7, in <module>
    from ..metaschema.meta_schema_model import AristaAvdSchema
  File "/workspace/ansible-avd/python-avd/pyavd/schema/metaschema/meta_schema_model.py", line 9, in <module>
    from typing import Annotated, Any, ClassVar, Generator, List, Literal
ImportError: cannot import name 'Annotated' from 'typing' (/usr/local/lib/python3.8/typing.py)

Check for Linting errors on MarkDown files......................(no files to check)Skipped
➜  ansible-avd git:(issue3310-ip-security) ✗ python --version
Python 3.8.12
```

It seems that it doesn't like the `Annotated` import, which was introduced in python3.9, but the container is running 3.8.12?

**Comment by ClausHolbechArista** [comment]
You need at least 3.10 for development these days. There are other issues with 3.9 as well.

**Comment by gusmb** [comment]
> You need at least 3.10 for development these days. There are other issues with 3.9 as well.

Do you have an updated Dockerfile? Or do I need to use my own environment?

```
ARG VARIANT="3.8-v2.0"
FROM avdteam/base:${VARIANT}

WORKDIR /workspace
VOLUME ["/workspace"]

USER avd
RUN rm -f /home/avd/.gitconfig
```

**Comment by ClausHolbechArista** [comment]
I don't have one handy. I use my own env. @ankudinov is working on updated dev containers. Maybe he can provide something more recent.

**Comment by gusmb** [comment]
I switched to my own environment for the time being. Quick question, I see some other aspects of running the  molecule tests have also changed. How do I re-run tests for `eos_cli_config_gen`?

**Comment by gusmb** [comment]
> I switched to my own environment for the time being. Quick question, I see some other aspects of running the molecule tests have also changed. How do I re-run tests for `eos_cli_config_gen`?

Ah nevermind, I can still run the molecule scenario directly or use `make refresh-facts`. Thanks
