### ISSUE TITLE
(eos_cli_config_gen) Extend support for platform sand

### ISSUE THREAD

**Issue by chetryan** [aristanetworks/ansible-avd#3342]
### Enhancement summary

Currently the `platform sand` command does not support specifying mdb configuration. At the moment any such configuration has to be done via `eos_cli` commands

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

For example, it would be great to support the following:

```
platform:
  sand:
     mdb_profile: <profile name>
```

### Describe the solution you would like

```
platform:
  sand:
     mdb_profile: <profile name>
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
Probably fixed by https://github.com/aristanetworks/ansible-avd/pull/3372
