### ISSUE TITLE
prefix_lists are rendered at the wrong level by eos_desings role 

### ISSUE THREAD

**Issue by tosha25** [aristanetworks/ansible-avd#3348]
### Issue Summary

AVD would render prefix-lists directly under specific VRF configuration stanza when they are specified inside network services -> bgp_peers settings. Arista EOS does not accept prefix-lists for all address families. Instead, prefix-lists need to be specified under specific address family such as ipv4 or ipv6 unicast. The screenshot below shows where AVD would render prefix-lists with red arrows pointing to the wrong location, and green arrow pointing where it is supposed to be. 

![image](https://github.com/aristanetworks/ansible-avd/assets/117962337/a8b17628-2bc6-4d9c-8168-919788e23299)

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
This is an example of YML settings, which should reproduce the problem. This should be inside network settings for a VRF:

---
VGPDMZz11003_VRF:
  name: VGPDMZz11003
  # vrf_id: 3
  description: DMZ_VRF
  vrf_vni: 11003
  bgp_peers:
    - ip_address: 214.70.15.100
      peer_group: SDWAN-VP01-VP02
      remote_as: 4200066012
      route_map_out: ndpn-velo-vp-out
      prefix_list_out: DO-NOT-ADV-HOST-ROUTES
      nodes: [ EST1-BL-0001, EST1-BL-0002 ]
    - ip_address: 214.70.15.101
      peer_group: SDWAN-VP01-VP02
      remote_as: 4200066013
      route_map_out: ndpn-velo-vp-out
      prefix_list_out: DO-NOT-ADV-HOST-ROUTES
      nodes: [ EST1-BL-0001, EST1-BL-0002 ]
```

### Relevant log output

```shell
There will not be any indication from AVD if there is anything wrong with the generated configuration. However, you will see messages on the devices or CVP server that it can't accept prefix-list statements at all address families level if you attempt to paste configuration to a device, or apply it via CVP.
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
@tosha25 thank you for reporting this. I will look into getting this fixed asap.
