### ISSUE TITLE
Refactor: AVD 5.0 Remove tmp_vrf_neighbor_prefix_list_in and tmp_vrf_neighbor_prefix_list_out

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#3361]
TODO: AVD5.0 remove tmp_vrf_neighbor_prefix_list_in and tmp_vrf_neighbor_prefix_list_out. Special temporary variables set under vrf neighbors but read under vrf address_family_ipv4. This is required to move the deprecated vrfs[].neighbors[].ip_prefix_list_in/out to vrfs[].address_family_ipv4.neighbors[].ip_prefix_list_in/out #}

_Originally posted by @gmuloc in https://github.com/aristanetworks/ansible-avd/pull/3358#discussion_r1399200132_

**Comment by gmuloc** [comment]
Resolved in https://github.com/aristanetworks/avd/pull/4311
