### ISSUE TITLE
[Feature] collection artifacts should pass default lint rules

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#3375]
### Enhancement summary

Artifacts should idealy match the default lint rules.  This should apply to all roles.

### Which component of AVD is impacted

all

### Use case example

when validating artifacts, linters are very much useful for validating proper file formats

### Describe the solution you would like

|file extension|linter|failures|
| ------- | ---- | ------ |
| yaml, yml | yamllint | document-start, indentation |
| md | markdownlint-cli2 | MD012/no-multiple-blanks |

### Additional context

Totally nitpicking here, but its good form when adding to a whole ci pipeline to lint your artifacts.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
Thanks for opening the issue - can you please indicate on which artifacts you have seen these errors so far?

**Comment by ryanmerolle** [comment]
devices markdown files seem to have this issue (notice the 2 lines) before `#### Loopback Interfaces Device Configuration`

```markdown
### Loopback Interfaces

#### Loopback Interfaces Summary

##### IPv4

| Interface | Description | VRF | IP Address |
| --------- | ----------- | --- | ---------- |
| Loopback0 | EVPN_Overlay_Peering | default | 192.0.255.2/32 |
| Loopback1 | VTEP_VXLAN_Tunnel_Source | default | 192.0.254.2/32 |
| Loopback100 | Tenant_A_OP_Zone_VTEP_DIAGNOSTICS | Tenant_A_OP_Zone | 10.255.1.2/32 |

##### IPv6

| Interface | Description | VRF | IPv6 Address |
| --------- | ----------- | --- | ------------ |
| Loopback0 | EVPN_Overlay_Peering | default | - |
| Loopback1 | VTEP_VXLAN_Tunnel_Source | default | - |
| Loopback100 | Tenant_A_OP_Zone_VTEP_DIAGNOSTICS | Tenant_A_OP_Zone | - |


#### Loopback Interfaces Device Configuration
```

yaml files do not start with a `---` AND lists are not indented correctly:
```bash
./intended/structured_configs/spine1.yml
  1:1       warning  missing document start "---"  (document-start)
  19:3      error    wrong indentation: expected 4 but found 2  (indentation)
  33:5      error    wrong indentation: expected 6 but found 4  (indentation)
  38:3      error    wrong indentation: expected 4 but found 2  (indentation)
  41:3      error    wrong indentation: expected 4 but found 2  (indentation)
  59:5      error    wrong indentation: expected 6 but found 4  (indentation)
  62:1      error    wrong indentation: expected 2 but found 0  (indentation)
  73:1      error    wrong indentation: expected 2 but found 0  (indentation)
  80:1      error    wrong indentation: expected 2 but found 0  (indentation)
  85:1      error    wrong indentation: expected 2 but found 0  (indentation)
  88:1      error    wrong indentation: expected 2 but found 0  (indentation)
  97:3      error    wrong indentation: expected 4 but found 2  (indentation)
  101:1     error    wrong indentation: expected 2 but found 0  (indentation)
  120:1     error    wrong indentation: expected 2 but found 0  (indentation)
  125:1     error    wrong indentation: expected 2 but found 0  (indentation)
  127:3     error    wrong indentation: expected 4 but found 2  (indentation)
  130:1     error    wrong indentation: expected 2 but found 0  (indentation)
  132:3     error    wrong indentation: expected 4 but found 2  (indentation)
  135:5     error    wrong indentation: expected 6 but found 4  (indentation)
```

**Comment by carlbuchmann** [comment]
@ryanmerolle 
I agree with you regarding the markdown-lint issues, and I'm addressing them in PR #3377 

Regarding the yaml files, the indentation is within specifications: https://yaml.org/spec/1.2-old/spec.html#id2802665
I have discussed this in the past with @ClausHolbechArista. We use `yaml.dump` function, and this function doesn't support the indentation of the list. We have explored leveraging `ruamel.yaml` but this had performance implications.

**Comment by ryanmerolle** [comment]
Interesting so is yamllint’s default config not in spec?

**Comment by ClausHolbechArista** [comment]
> Interesting so is yamllint’s default config not in spec?

The spec allows for both formats.

**Comment by ClausHolbechArista** [comment]
We will not be addressing the yaml changes. We are already running both markdownlint and yamllint but we have some more lenient settings. Ex. see `.github/yamllintrc`.
