### ISSUE TITLE
Doc: Capitalize the header for Management Interface description in doc template

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3394]
Do not fix this in this PR as it would impact **all** molecule scenarios
just commenting to open an issue

```suggestion
| Management Interface | Description | Type | VRF | IP Address | Gateway |
```

_Originally posted by @gmuloc in https://github.com/aristanetworks/ansible-avd/pull/3364#discussion_r1406218518_

**Comment by MuhammadHasnain77** [comment]
Hi,
It's my first time on Github can you guide me more about the issue where can i find this file in your repository, I want to work on it.
Thanks

**Comment by ClausHolbechArista** [comment]
@MuhammadHasnain77 sorry we missed your ask here. The file is this one: https://github.com/aristanetworks/ansible-avd/blob/43b375984ac919a93b9cc7d492968329b81df0e7/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/management-interfaces.j2#L15.
After fixing the template, you would have to rerun molecule for all scenarios.
```sh
cd ansible_collections/arista/avd/molecule
make refresh-facts
```
Make sure to have all the requirements installed from `requirements.txt` and `requirements-dev.txt`.
