### ISSUE TITLE
Doc(plugins): Better escaping and list rendering in automated plugin documentation

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3430]
To summarize most of @JulioPDX's comments in the PR - the auto generated doc for module where we are using `ansible-doc-extractor` would need some love for lists and some escaping being done (e.g. `;`). which renders weirdly in mkdocs

_Originally posted by @gmuloc in https://github.com/aristanetworks/ansible-avd/issues/3352#issuecomment-1856769933_

**Comment by ClausHolbechArista** [comment]
@gmuloc I believe this was resolved a while back. Reopen if you still think it needs work.
