### ISSUE TITLE
Fix(eos_cli_config_gen): MAC Security key fallback configured even if set to false

### ISSUE THREAD

**Issue by bjmeuer** [aristanetworks/ansible-avd#3436]
### Issue Summary

When defining a Mac Security key with the option "fallback: false" the fallback will be configured anyway. 

In the code I see that it is just checked if "fallback" is defined, but not if it is also set to "true"

```
{%                 if connection_key.fallback is arista.avd.defined %}
{%                     set key_cli = key_cli ~ " fallback" %}
{%                 endif %}
```

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
mac_security:
  profiles:
    - name: CONG_MACSEC_PROF
      cipher: aes256-gcm-xpn
      connection_keys:
        - id: "ab"
          encrypted_key: primary_key
          fallback: false
        - id: "ba"
          encrypted_key: fallback_key
          fallback: true
      mka:
        session:
          rekey_period: 3600
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by bjmeuer** [comment]
I will look into that

**Comment by gmuloc** [comment]
From what you describe, this should fix it.

Thanks for catching it.
```
{%                 if connection_key.fallback is arista.avd.defined(true) %}
{%                     set key_cli = key_cli ~ " fallback" %}
{%                 endif %}
```
