### ISSUE TITLE
Remove BGP Maximum-Routes setting

### ISSUE THREAD

**Issue by theotherguy2175** [aristanetworks/ansible-avd#3475]
### Enhancement summary

It seems by default if you don't set the max-routes for bgp it set's it to 0. Which technically is unlimited but it just seems like extra config we don't need since not having it at all will do the same thing. I don't see anything on AVD's docs to remove the config all together. Is there such an AVD section to allow that? To just not all maximum-routes?

### Which component of AVD is impacted

eos_designs

### Use case example

It seems by default if you don't set the max-routes for bgp it set's it to 0. Which technically is unlimited but it just seems like extra config we don't need since not having it at all will do the same thing. I don't see anything on AVD's docs to remove the config all together. Is there such an AVD section to allow that? To just not all maximum-routes?

### Describe the solution you would like

It seems by default if you don't set the max-routes for bgp it set's it to 0. Which technically is unlimited but it just seems like extra config we don't need since not having it at all will do the same thing. I don't see anything on AVD's docs to remove the config all together. Is there such an AVD section to allow that? To just not all maximum-routes?

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
The only option to remove the maximum_routes command completely would be to use `structured_config` or `custom_structured_configuration_router_bgp` where appropriate, and set the value for these `maximum_routes` keys to `null`. That would make `eos_cli_config_gen` think they were not set at all.
Notice that not setting them will make you fall back to EOS defaults which vary slightly in some older versions and also varies between address families.
