### ISSUE TITLE
Feat(eos_cli_config_gen): Add InfluxDB support

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#3479]

**Comment by ClausHolbechArista** [comment]
@chetryan can you share a config snip for the requested CLI?

**Comment by ClausHolbechArista** [comment]
See the parent issue for details: https://github.com/aristanetworks/avd/issues/2464

**Comment by MaheshGSLAB** [comment]
/ spend 1h

**Comment by chetryan** [comment]
I have updated #2464 with more details as requested by @Vibhu-gslab

**Comment by ClausHolbechArista** [comment]
Fixed in #2464
