### ISSUE TITLE
Remove spine-peer-filters.j2 and references to it

### ISSUE THREAD

**Issue by ankudinov** [aristanetworks/ansible-avd#348]
## Issue Type

- Documentation Report

## Summary

As AVD is not using BGP listen-range for dynamic peering any more, `spine-peer-filters.j2` template and references in the documentation have to be removed.

## Role or Module Name

- eos_l3ls_evpn
- eos_cli_config_gen

**Comment by titom73** [comment]
Will be solved with PR #355
