### ISSUE TITLE
Allow port-channels with id >2000 to pass validation

### ISSUE THREAD

**Issue by optiz0r** [aristanetworks/ansible-avd#3491]
### Issue Summary

Creating a port-channel from a 7388 interface Ethernet3/16/1 using the default auto-generated Port-Channel ID causes validation to fail:

```[WARNING]: [lab7388]: 'Validation Error: port_channel_interfaces[25].mlag': 3161 is greater than the
maximum of 2000```

From the manual, this should be a legitimate port-channel id, so the validation failure is a false alarm

https://www.arista.com/en/um-eos/eos-port-channels-and-lacp (4.31.1F)
> Previously, the maximum valid port channel ID was equal to the maximum number of port channels configurable on the system, 2000, and this feature increases the maximum ID to 999,999 while maintaining the same limit of 2000 port channels on the system.

versions:
* `arista.avd:4.5.0`

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
servers:
  -name: test
   adapters:
    - mode: access
      switches: [lab7388]
      switch_ports: [Ethernet3/16/1]
      endpoint_ports: [eth0]
      port_channel:
        mode: 'on'
```
```


### Relevant log output

```shell
[WARNING]: [lab7388]: 'Validation Error: port_channel_interfaces[25].mlag': 3161 is greater than the
maximum of 2000```
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
@optiz0r Thank you for opening this issue. The current limitation was kept in place since we also use the port-channel ID as MLAG ID. And MLAG IDs are unfortunately still limited to 1-2000 on EOS.
The error you see is actually for MLAG and not for the channel-group ID.

**Comment by optiz0r** [comment]
Ah thank you. I've worked around this for now by manually specifying the port-channel id to use a number within the mlag range (although it's a bit annoying to have to manually allocate the IDs and avoid conflicts with other auto-generated port-channels :( )

I'll close this issue since it can't be fixed without EOS changes. Sorry for the noise.

**Comment by ClausHolbechArista** [comment]
NP Ben and thanks a gain for reporting issues. I follow your point, and one workaround we have been talking about is to have a configurable port-channel algorithm, where we ignore the last /1. Obviously it would not work for breakouts, and we would raise an error if used in such cases. But for most usecases I think it would address the concern and also keep the port-channel IDs on fixed switches simpler (Ethernet48/1 -> Port-channel 48)

**Comment by optiz0r** [comment]
FWIW: I couldn't just drop the `/1` since that then introduced a conflict between Ethernet2/1/1 auto-generated port channel for uplink and interface Ethernet2/11/1. I had to hardcode the ID used for a port channel containing Ethernet21/1/1 to 1211 to workaround this.

**Comment by ClausHolbechArista** [comment]
~Right. But if our auto-generation algorithm always ignored the /1, we would produce 21 and 211 for this scenario.~ Sorry I misread your example. Indeed that would trigger new issues...
I don't see a way out of this except of a pool-manager (automatic assignment with no specific logic), but then we loose the human-friendly numbers.

**Comment by optiz0r** [comment]
I think feel free to keep this closed this for now. if/when EOS starts supporting higher mlag numbers, I'll remove my workaround. I think changing the port id assignment for something more flexible would introduce more complexity and chance for confusion than it would gain (at least in this specific case; there might be other examples where it would be more beneficial).

As you were!
