### ISSUE TITLE
Bug(eos_cli_config_gen): Add missing IP security SA encryption values to schema

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#3496]
### Enhancement summary

I get the following validation warning when configuring `ip_security`:

```
[WARNING]: [switch1]: 'Validation Error:

ip_security.sa_policies[0].esp.encryption': 'aes256gcm128' is not one of

['disabled', 'aes128', 'aes128gcm128', 'aes128gcm64', 'aes256', 'aes256gcm256',

'null']
```

Seems like ESP encryption value `aes256gcm128` for SA policies is missing in the schema options

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Configure IPSEC SA policies using `aes256gcm128` as ESP encryption value

### Describe the solution you would like

Modified AVD schema to support this value

### Describe alternatives you have considered

N/A

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Thank you for reporting. Can you share the platform and EOS version you have used?
Just checked in lab and it seems like a typo where aes256gcm256 should have been aes256gcm128.

**Comment by gusmb** [comment]
> Thank you for reporting. Can you share the platform and EOS version you have used? Just checked in lab and it seems like a typo where aes256gcm256 should have been aes256gcm128.

AWE-5310 and AWE-5510. Version I think it is 4.27.1 or higher
