### ISSUE TITLE
Split J2 logic into specific templates in eos_l3ls_evpn

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#350]
**Issue Type**

- Template enhancement

**Is your feature request related to a problem? Please describe.**

Main device templates in `eos_l3ls_evpn` become complex to maintain and operate

**Describe the solution you'd like**

By splitting `j2` logic into specific template will reduce size of these templates and make it easier to extend as it is same logic as for data: include a new subtemplate

**Comment by ClausHolbechArista** [comment]
In PR #661 I have tried to move some complex logic into seperate templates, to ease reuse and maintenance.
