### ISSUE TITLE
No Jinja support for "ribd" Routing Protocol Model

### ISSUE THREAD

**Issue by n8dagreat2** [aristanetworks/ansible-avd#3507]
### Issue Summary

eos_cli_config_gen role has two options for routing protocols (ribd and multi-agent). However, there is no jinja implementation for the "ribd" option.
![image](https://github.com/aristanetworks/ansible-avd/assets/43422176/6a273dfa-cc50-41c8-8afd-c526ebe7ccbd)
![image](https://github.com/aristanetworks/ansible-avd/assets/43422176/a4119543-1a12-4a89-9168-4fddc0ceb8dc)

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Apply "ribd" to the service_routing_protocols_model variable on any device. The command "service routing protocols model ribd" should not be in the final intended cfg file.
```

### Relevant log output

```shell
n/a
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by carlbuchmann** [comment]
Thanks for reporting this issue, this was historical behavior of AVD, as prior to EOS 4.30.1 the default protocolmodel is ribd, therefore we didn't print the configuration.
That said AVD should be declarative and always configure the desired command regardless of the EOS default when defining the variable in host/group vars.

Would you like to submit a PR for this, or we can take this on?
