### ISSUE TITLE
Expand eos_cli support for BGP configuration

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#3570]
### Enhancement summary

Hi,

When trying to configure some features that are still missing in BGP, i believe we do not have the option of using raw_cli in some sections of the BGP configuration.

It wold be useful to be able to render raw cli commands directly under the root of BGP and the "address_family_evpn" for features that are yet to be natively supported.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

For example, this feature (tracked support under a separate issue):
https://www.arista.com/en/support/toi/eos-4-29-0f/16349-evpn-vxlan-all-active-multihoming-gateway

Requires to append some additional BGP configuration as follows:
```
   address-family evpn
      neighbor WAN activate
      neighbor WAN domain remote
      neighbor SPINE activate
      ...
      !
      **evpn ethernet-segment domain all
         identifier 0011:1111:1111:1111:1111
         route-target import 00:01:00:01:00:01
            !
            layer-2 fec in-place update**
```
I believe eos_cli is supported under bgp vrf, vlan and vlan aware bundle only by looking at the documentation.
https://avd.arista.com/4.5/roles/eos_cli_config_gen/docs/input-variables.html#router-bgp

### Describe the solution you would like

Additional eos_cli support in BGP.

### Describe alternatives you have considered

Could not find alternatives to support this configuration yet.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
@dgonzalez85 `eos_cli` was added directly under `router_bgp` so you can achieve adding the required commands using this escape hatch.
Please open issues to track adding the TOI commands as well if not already done!
