### ISSUE TITLE
Feature request Extend the functionality of the is_deployed flag to shutdown BGP peerings as well as interfaces

### ISSUE THREAD

**Issue by rich9474** [aristanetworks/ansible-avd#3604]
### Enhancement summary

Currently if a device in the inventory has the ``is_deployed: true`` flag set, then the interfaces towards that device in the configuration are shutdown (Issue #1744/#1745).  However, because the BGP peerings are not shutdown, when running  the CVP ``BGP exit Maintenence mode`` action, it fails as some of the peers are idle(noif), or if the interfaces are set to not shutdown towards undeployed peers, they would be in a state other than Established and also fail.  If they were also shutdown, the test would pass.

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen

### Use case example

Having BGP peers in a state other than active, causes monitoring issues, and breaks CVP tests.  If hosts are intentionally not deployed, then the BGP peerings should be shutdown.  As with the interfaces , there could be a flag to override this behaviour.

### Describe the solution you would like

if ``is_deployed: false`` is set and ``shutdown_interfaces_towards_undeployed_peers: true`` is set, then any BGP peers should also be shutdown.  A variable ``shutdown_bgp_peers_towards_undeployed_peers`` could be used to independently control the behaviour.

### Describe alternatives you have considered

the only workarounds I currently have are:

1. Manually override the AVD generated config to shutdoen the BGP peers, 
2. Not run the BGP Maintenance mode task, and accept the packet loss (not ideal)
3. Comment out the undeployed devices and remove all the config

None of these are particularly appealing, and a big bonus of CVP automated rolling upgrades is broken by having an undeployed switch inthe config.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by laxmikantchintakindi** [comment]
@rich9474 Could you help to test this PR?
