### ISSUE TITLE
Add ISIS support in arista.avd.encrypt plugin

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#3624]
### Enhancement summary

Currently the plugin supports encrypting BGP and OSPF clear text passwords into EOS passwords.

We have a project with ISIS, and we would need the same functionality for ISIS.

### Which component of AVD is impacted

plugins

### Use case example

SP project using ISIS as routing-protocol and AAP to store credentials in clear text.

### Describe the solution you would like

Extend the plugin to support ISIS passwords.

https://avd.arista.com/4.5/roles/eos_cli_config_gen/docs/input-variables.html#router-isis

We can set already ISIS authentication keys using eos_cli_config_gen:
```
    isis_authentication_mode: <str; "text" | "md5">

    # Type-7 encrypted password
    isis_authentication_key: <str>
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
@dgonzalez85 please test PR #3662 which should address this.

**Comment by dgonzalez-arista** [comment]
Hi Clause, sure i will test and get back
