### ISSUE TITLE
Add support for connected endpoints running PTP on MLAG switches

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#3627]
### Enhancement summary

Certain connected endpoints, notably Audio Visual devices run PTP for audio synchronization amongst their peers.  In an mlag environment, their ptp packets loop back to themself.  The solution is to configure `ptp mpass` on the mlag port-channel.  This is also true in the case of a single homed device in a L2 leaf subordinate to an mlag pair. 

### Which component of AVD is impacted

eos_designs

### Use case example

support devices that use ptp without a formal ptp infrastucture.

### Describe the solution you would like

Add a new key to connected endpoints, maybe `ptp` or `mpass` that will signal to avd to add `ptp mpass` to the mlag port-channel to the endpoint.

### Describe alternatives you have considered

The alternative to manually determine all impacted port-channels and apply eos_cli to each. 

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
ptp_mpass could be added under the port-channel key for the connected endpoint. It should only take effect if ptp is enabled on the switch and if the switch is an mlag switch.
