### ISSUE TITLE
Add support for setting mgmt_gateway under the node settings

### ISSUE THREAD

**Issue by Spandanaarista** [aristanetworks/ansible-avd#3635]
### Enhancement summary

To simplify the process of configuring distinct mgmt_gateway settings for nodes according to their management subnet allocation within the same fabric.

### Which component of AVD is impacted

eos_designs

### Use case example

The customer's OT fabric utilizes different management VLANs to oversee various IDF devices across different buildings. This enhancement will simplify the process of adding management gateways either per node or node group based on their allocated management subnets.

### Describe the solution you would like

Add **mgmt_gateway** fabric setting also under Node_type, Node_group, Nodes.

### Describe alternatives you have considered

Considering the addition of mgmt_gateway per group_vars, this would result in the creation of multiple groupvars files. Consequently, the customer might need to consistently include new hosts in the groups whenever they need to add new devices.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
When implementing this, please make sure to make the setting under node group take precedence over the root key.
