### ISSUE TITLE
Fix(eos_cli_config_gen): Check that the `ptp mode` valid values are correct on some platform (especially transparent)

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3669]
Hmmm regarding the valid_values `transparent` for mode:

```
l3leaf1(config)#ptp mode ?
  boundary        Boundary Clock Mode
  disabled        Disable PTP and forward PTP messages normally
  e2etransparent  End-to-End Transparent Clock
  gptp            Generalized PTP Clock
  ordinarymaster  Ordinary Master Clock
  p2ptransparent  Peer-to-Peer Transparent Clock
```

@ClausHolbechArista maybe on another device (using CloudEOS here)

_Originally posted by @gmuloc in https://github.com/aristanetworks/avd/pull/3666#discussion_r1504156794_

**Comment by ClausHolbechArista** [comment]
checked even very old platforms and "transparent" is not a valid option. The list above is the same in eos 4.23 and 4.31 on various hardware platforms.

**Comment by Shivani-gslab** [comment]
Shall we replace `transparent` with all of these options in valid values?

**Comment by ClausHolbechArista** [comment]
> Shall we replace `transparent` with all of these options in valid values?

In eos_cli_config_gen I would say yes. Thanks.
