### ISSUE TITLE
Add ISIS global knob to enable authentication 

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#3674]
### Enhancement summary

ISIS authentication is not enabled by default when enabling ISIS as the underlay protocol for the fabric. 

It would be great to have a global knob to enable authentication in the fabric links like we do for BGP. 

### Which component of AVD is impacted

eos_designs

### Use case example

ISIS authentication set between P2P links in the fabric.

### Describe the solution you would like

Global knob in eos_designs to enable ISIS authentication by default.

### Describe alternatives you have considered

Currently tested with custom_structured configuration in host_vars.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
I suggest `underlay_isis_authentication_mode`, `underlay_isis_authentication_key` to match what we have in the l3_edge/core_interfaces model.
