### ISSUE TITLE
Erroneous code comment (eos_designs/python_modules/network_services/ethernet_interfaces mixin)

### ISSUE THREAD

**Issue by lcphill** [aristanetworks/ansible-avd#3694]
https://github.com/aristanetworks/avd/blob/fb694911e62d0774ddf61ecb5fe70c884c91aea2/ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/ethernet_interfaces.py#L33

Hi, the referenced comment line goes back to 3.8.0-rc1, when apparently a refactoring activity created the resultant ethernet_interfaces.py python code and, now / presume, the comment no longer applies (but is confusing in the context for which it is placed).  _I presume (hope) the comment no longer applies?_

This is a minor change request (I would have preferred to do an in-line comment versus a ticket).

Thank you.

**Comment by ClausHolbechArista** [comment]
Correct. We will remove it.
