### ISSUE TITLE
Feat(eos_cli_config_gen): Add support for BGP TCP AO

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#3699]
### Enhancement summary

We have a project where a customer is asking for BGP TCP authentation as described in this TOI:
https://www.arista.com/en/support/toi/eos-4-28-2f/16087-bgp-tcp-authentication-option-tcp-ao

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Customer wants additional encryption security in the fabric and password rotation in the fabric between leaves and spines.

### Describe the solution you would like

Currently BGP does not allow to specifiy this type of encryption:

https://avd.arista.com/4.6/roles/eos_cli_config_gen/docs/input-variables.html#router-bgp

Configuration shoud allow:
```
neighbor NEIGHBOR_ID password shared-secret profile NAME algorithm ALGORITHM

```
Also the following:
```
management security
   session shared-secret profile NAME
      secret ID [LEVEL] SECRET {LIFETIME}
      ...
```
### Describe alternatives you have considered

PS engineer is considering custom templates for this until this is natively supported.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
I dont think we support this:

```
management security
   session shared-secret profile NAME
      secret ID [LEVEL] SECRET {LIFETIME}
      ...
```

Can you please add it to the issue.

Is someone from the project going to implement this? If so can we assign the issue to them?

**Comment by dgonzalez-arista** [comment]
Thanks @gmuloc, i missed that and edited the original issue. I dont think anyone in the project can work on this, not sure if someone from eos+ or avd team has some cycles for this. At the moment the PS engineer is looking into custom templates, but maybe not the best option.

**Comment by ClausHolbechArista** [comment]
@dgonzalez85 please test pr #3853 if it addresses what you need.

**Comment by dgonzalez-arista** [comment]
> @dgonzalez85 please test pr #3853 if it addresses what you need.

Sorry for getting late to this, but i tested and working well :)
