### ISSUE TITLE
eos_cli support under router_isis

### ISSUE THREAD

**Issue by perimore** [aristanetworks/ansible-avd#3742]
### Enhancement summary

Allow users to add eos_cli under router_isis for unsupported configs in the model

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```
router_isis:
  eos_cli: |
    address-family ipv6 unicast
      multi-topology
    traffic-engineering
      no shutdown
      is-type level-2
```

### Describe the solution you would like

```
router_isis:
  eos_cli: <str>
```

### Describe alternatives you have considered

Adding full support for traffic-engineering commands. This will follow with a separate issue

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
@perimore this has been merged in devel.
Please open the issues you need for the CLI you are currently targeting to use via `eos_cli` so this can be added properly to AVD!
