### ISSUE TITLE
Not able to generate region isolation event on set up with tags provisioned by AVD  router role transit needs to be  changed to transit region

### ISSUE THREAD

**Issue by mansihanda** [aristanetworks/ansible-avd#3749]
### Issue Summary

router role transit is changed to transit region
it seems there is a role mismatch in the caravan aeris path.

https://grafana.cv-staging.corp.arista.io/explore?orgId=1&left=%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22turbines%5C%22,app%3D%5C%22turbine-event-wan-fabric-region-isolation%5C%22%7D%20%7C%3D%20%5C%22systest-scale-10%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D

D2CB2D5B2CC101E704A75B01DDB21E23 | {   "Role": "transit",   "Site": "Site3",   "Zone": "India-ZONE",   "Region": "India",   "VtepIP": "192.168.100.4",   "SerialNumber": "D2CB2D5B2CC101E704A75B01DDB21E23",   "WanInterfaces": {     "Ethernet1": {       "Carrier": "internet",       "CircuitID": "",       "PathGroupName": "internet"     }   } }
-- | --

### How do you run AVD ?

None

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
This was already resolved by a recent fix in #3744.
