### ISSUE TITLE
Documentation error in Intro to Ansible and AVD section - AVD 4.6.0

### ISSUE THREAD

**Issue by chuajen** [aristanetworks/ansible-avd#3764]
ansible_collections/arista/avd/docs/getting-started/intro-to-ansible-and-avd.md

In AVD 4.6 documentation - Under the section "Using Ansible AVD in conjunction with CloudVision"
The play Run AVD has a task that calls the arista.avd.eos_config_deploy_eapi role, which should not be there

**Comment by ClausHolbechArista** [comment]
Thank you for reporting!

**Comment by ClausHolbechArista** [comment]
@chuajen Can I ask you to verify that I fixed the right thing in #3778? Thanks.
