### ISSUE TITLE
Doc(eos_validate_state): Release note mention that CSV headers have changed

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3777]
Let's track for 5.0 to include in the release notes that the heading for CSV are now changing.

_Originally posted by @gmuloc in https://github.com/aristanetworks/avd/pull/3743#discussion_r1538896982_

**Comment by ClausHolbechArista** [comment]
This will be handled by the new anta role instead, and then old role wild be deprecated or removed.

**Comment by carl-baillargeon** [comment]
Completed in #4286
