### ISSUE TITLE
FIx(eos_validate_state): ANTA Inputs of BGP tests shows None for external BGP peer in the report

### ISSUE THREAD

**Issue by carl-baillargeon** [aristanetworks/ansible-avd#3805]
![image](https://github.com/aristanetworks/avd/assets/63206086/ebe41f81-1aa6-45af-a1d5-6cbb5b7f38ed)

That's expected since the external peer is not part of the structured_config but we should have a better message.

**Comment by gmuloc** [comment]
Fixed in #3872
