### ISSUE TITLE
Certain platforms only support configuring IP MTU globally and not on individual interfaces. However, AVD sets the MTU to 9214 on MLAG SVIs by default.

### ISSUE THREAD

**Issue by Spandanaarista** [aristanetworks/ansible-avd#3815]
### Issue Summary

For platforms T3X4, T3X2, and T3X1, there is currently no support for setting the per-interface MTU. However, AVD automatically configures "mtu 9214" for MLAG SVIs by default, which may pose an issue for these platforms. Therefore, the MTU behavior should be adjusted according to the platform.

The current workaround proposed by @carlbuchmann involves applying the following configuration to the switch pair, resulting in the removal of the default MTU of 9214 on the MLAG SVI.
custom_structured_configuration_vlan_interfaces:
  - name: Vlan4094
    mtu: null

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

None

### Steps to reproduce

```shell
#eos cli                                                                                 
   interface Vlan4094
   description MLAG_PEER
   no shutdown
   mtu 9214
   no autostate
   ip address 192.168.0.0/31
```

### Relevant log output

```shell
# structured_config                                                               
vlan_interfaces:
- name: Vlan4094
  description: MLAG_PEER
  shutdown: false
  ip_address: 192.168.0.0/31
  no_autostate: true
  mtu: 9214
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by kmueller68** [comment]
@Spandanaarista please have a look at the solution Claus already implemented on this issue.

https://github.com/aristanetworks/avd/pull/3128

I am using it successfully at customer.

**Comment by Spandanaarista** [comment]
Thank you, @kmueller68, for directing us to the existing solution. We overlooked it.
