### ISSUE TITLE
Docs Build fail due to md-toc dependency

### ISSUE THREAD

**Issue by ghost** [aristanetworks/ansible-avd#3835]
### Issue Summary

In the latest release of [md-toc 9.0.0](https://github.com/frnmst/md-toc/releases/tag/9.0.0) the API has changed causing AVD build to fail at
```
TASK [arista.avd.eos_designs : Generate fabric documentation] ********************************************************************************************************************
task path: /home/rahul/fdny/dc/mcast-testing/ansible_collections/arista/avd/roles/eos_designs/tasks/main.yml:62
The full traceback is:
.....
.....
  File "/home/rahul/fdny/dc/mcast-testing/ansible_collections/arista/avd/plugins/filter/add_md_toc.py", line 121, in add_md_toc
    toc = md_toc.build_toc("-", keep_header_levels=toc_levels, skip_lines=skip_lines).rstrip()
AttributeError: module 'md_toc' has no attribute 'build_toc'
fatal: [dc1-spine1 -> localhost]: FAILED! => changed=false
```

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by carlbuchmann** [comment]
@rahulg-arista - thank you for reporting this, the fix has been merged to devel and will be part of the next AVD release.
