### ISSUE TITLE
Bug(eos_cli_config_gen): BGP models has `supress-map` and `attribute-map` which are not supported

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3876]
Tried the CLI on EOS device and it was not present so need further investigation.

_Originally posted by @gmuloc in https://github.com/aristanetworks/avd/pull/3826#discussion_r1568901544_

**Comment by laxmikantchintakindi** [comment]
I see cfg has this cli `aggregate-address 1.12.1.0/24 as-set advertise-map ADV-MAP summary-only attribute-map RM-ATTRIBUTE match-map RM-MATCH advertise-only`. There is no option such as attribute-map. Can we remove this key as well?

**Comment by ClausHolbechArista** [comment]
Please remove both keys in the templates. To make it clear to existing deployments, please add the `deprecation` key in the schema with `removed: true` and `remove_in_version: 4.9.0`.
