### ISSUE TITLE
ARP aging timeout support for SVIs

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#388]
**Issue Type**

- Template enhancement

**Is your feature request related to a problem? Please describe.**
Using VRRP as first-hop redundancy protocol ARP entries age from the table before the MAC address ages away. This leads to "out discards" reported by CloudVision and a massive flood on the layer 2 domain accross the switches participating in this VRRP setup.

**Describe the solution you'd like**
Add support to configure the EOS `arp aging timeout` option from the Jinja2 templates.

**Describe alternatives you've considered**
Using a configlet simply feels ... wrong.

**Additional context**

Proposed extension to the VLAN interfaces data model:

```
vlan_interfaces:
  < Vlan_id_1 >:
    arp_aging_timeout: < timeout >
```

**Comment by onurgashi** [comment]
Thanks for opening the issue!
There is also development ongoing for the global ARP timer, would that cover your use case Christian?

**Comment by c-po** [comment]
@onurgashi unfortunately we need this be configurable per individual VLAN as per the requirement of the connected equipment
