### ISSUE TITLE
 Feat(eos_cli_config_gen): Interface IP NAT Support - origin_ip is not unique

### ISSUE THREAD

**Issue by SomaliRaven** [aristanetworks/ansible-avd#3894]
### Issue Summary

# Issue
We are using the IP NAT feature implemented in https://github.com/aristanetworks/avd/pull/2750 and have the issue that our Ansible Playbook Log gets flushed with error messages stating:

`Validation Error: svi_profiles[26].structured_config.ip_nat.destination.static': Values of Primary key 'original_ip' are not unique as required.`

The reason seems to be that `original_ip` is marked as `unique` in ansible_collections/arista/avd/roles/eos_cli_config_gen/docs/data_model/Interfaces.md. 

The `original_ip` does not have to be unique, because the combination of `original_ip` and `original_port` has to be unique. The same would be true for `translated_ip` and `translated_port`, which are both not marked as `unique`. 

Please unmark `original_ip` as `unique` or make sure that only the combination of `original_ip` and `original_port` is validated to be unique. This makes the creation of multiple entries for one `original_ip` and different `original_ports` possible without creating misleading warnings.

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
1. Create SVI Profile or Interface Configuration with IP NAT and multiple Entries with the same "original_ip". 
2. Execute Playbook and observe Warnings
3. See that configuration gets generated and can be implemented and works in EOS.
```

### Relevant log output

```shell
'Validation Error: svi_profiles[26].structured_config.ip_nat.destination.static': Values of Primary key 'original_ip' are                                                                                                                                                                   not unique as required.
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Thank you for reporting this issue. We will look into it.
BR
Claus
