### ISSUE TITLE
Documentation - WAN eos_designs missing ipv4_acls configuration

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#3897]
### Issue Summary

The documentation for WAN points out that we should configure ACLs under ipv4_acls section:
```
  # Name of the IPv4 access-list to be assigned in the ingress direction.
        # The access-list must be defined under `ipv4_acls`.
        # Required for all WAN interfaces (`wan_carrier` is set) unless the carrier is marked as 'trusted' under `wan_carriers`.
        ipv4_acl_in: <str>

        # Name of the IPv4 Access-list to be assigned in the egress direction.
        # The access-list must be defined under `ipv4_acls`.
        ipv4_acl_out: <str>
```
https://avd.arista.com/4.7/roles/eos_designs/docs/input-variables.html

However "ipv4_acls" is only found under the snmp_settings on this role.

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

None

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
The issue is that I forgot to include the table in the Input Variables markdown.
