### ISSUE TITLE
core_interfaces / l3_edge isn't generating EVPN config

### ISSUE THREAD

**Issue by theotherguy2175** [aristanetworks/ansible-avd#3909]
### Issue Summary

In the L3 2DC example it shows a snippet of l3_edge config that will make a bgp group of evpn-overlay-core. But when trying to apply that in my fabric config it generated the PTPs, IP, underlay and everything except those EVPN group configs. 

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
EDIT: Added link to gateway config in the example.

Correct. The intention of the l3_edge / core_interfaces is to provide a flexible underlay link. It will not interfere with the overlay in any way. It goes well hand in hand with the EVPN gateway feature like it is used in the example: https://github.com/aristanetworks/avd/blob/17b7d9cdee3a322c0c0900666aab37c247ee10bd/ansible_collections/arista/avd/examples/dual-dc-l3ls/group_vars/DC1.yml#L92-L101

If you wish to have a single EVPN domain, it can be used with just peering the route-servers of each DC with each other. (Simply set `evpn_route_servers: [<route-server-in-other-dc>, ...]` on the route-servers)

If I misunderstood your request, please elaborate.

**Comment by theotherguy2175** [comment]
No that was helpful. Basically we have our border leafs setup as the evpn route servers. And we had to do manual hostvar bgp config to make a separate peer group so borders could be bgp evpn neighbors. 

I did try adding the evpn_gateway/remote_peers and evpn_l2/l3 and all it did was add some config to the vlans bgp config:
```
vlan 10
  rd evpn domain remote 10.9.128.8:10
  route-target import export evpn domain remote 10680:753
```

basically this is the manual avd config we had to do:

```
   neighbor iBGP-INTRA-DC peer group
   neighbor iBGP-INTRA-DC remote-as 10680
   neighbor iBGP-INTRA-DC next-hop-self
   neighbor iBGP-INTRA-DC update-source loopback0
   neighbor iBGP-INTRA-DC send-community extended

   neighbor 10.9.0.8 peer group iBGP-INTRA-DC
   neighbor 10.9.0.8 description borderA1.bldc
   neighbor 10.9.0.9 peer group iBGP-INTRA-DC
   neighbor 10.9.0.9 description borderA2.bldc
   neighbor 10.9.128.9 peer group iBGP-INTRA-DC
   neighbor 10.9.128.9 description borderA2.ictc

   address-family evpn
      neighbor iBGP-INTRA-DC activate
```

Which as you can see looks very similar to the evpn-overlay-core setup in the dual DC example. So not sure if there is other config that we are using wrong. But it would be nice to get rid of all the hostvar setup.

**Comment by ClausHolbechArista** [comment]
please provide a snip of the vars you added for the `evpn_gateway` (including the context).
If you prefer, you can also email me a zip of your repo (please remove secrets). holbech < at > arista < dot > com.

**Comment by theotherguy2175** [comment]
Thanks! Email sent.
