### ISSUE TITLE
Add delimiter "!" for `custom_templates` output in eos_cli_config_gen.

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#391]
The `custom_templates` directive is really interesting.

I see all templates are simply concatenated. Would it probably make sense to add a `!` delimiter between individual configlets by default when rendering it? That would ease debugging using my visual EOS interpreter located in my brain.

_Originally posted by @c-po in https://github.com/aristanetworks/ansible-avd/issues/336#issuecomment-734377327_

**Comment by carlbuchmann** [comment]
A possible alternative would be to add the delimiter in the source custom template itself.

**Comment by c-po** [comment]
Actually it looks like that there is an `rstrip()` present as my `!` delimiters did not adhere its new line, it was actaúally placed at the end of befores template..

**Comment by ClausHolbechArista** [comment]
I will add an extra empty line in the for loop to ensure \n at the end of every custom template.
Adding extra delimiters may or may not fit the use case, so instead I would suggest adding a
```eos
! Configuration generated by my custom template - start
```
at the beginning and 
```eos
! Configuration generated by my custom template - end
```
at the end of each template instead of us forcing it in.
