### ISSUE TITLE
Feat(eos_designs): Non-existent profiles are ignored without errors

### ISSUE THREAD

**Issue by pmprado** [aristanetworks/ansible-avd#3930]
### Issue Summary

Due to typos, sometimes an endpoint may refer to a port profile that ends up being non-existent due to the typo.
This does not result in errors but it ends up generating configs that do not take the profile in consideration.

Please error out when referring to a profile that can't be found.

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
port_profiles:
  - profile: SERVER_A_PROFILE
    mode: trunk
    speed: 10g
    vlans: 2004, 2005, 2016, 2017
servers:
  - name: SERVER-A
    adapters:
      - endpoint_ports: [eth1]
        switch_ports: [Ethernet21]
        switches: [LF01-A]
        profile: SERVER-A-PROFILE
        enabled: true

(note the mixup of dashes vs underscores in the profile name)
The end result understandably does not have the configs from the port profile, but there is no error to be seen.
```

### Relevant log output

```shell
(there are no logs, that's the point :) )
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
Reclassifying it as this is historic behavior and changing it this way. For several minor releases we have been introducing this kind of behavior in other areas of AVD and this would be a good addition.

**Comment by pmprado** [comment]
> Reclassifying it as this is historic behavior and changing it this way. For several minor releases we have been introducing this kind of behavior in other areas of AVD and this would be a good addition.

Fair enough, but I am curious about the use case of referencing a non-existent profile... any examples?

**Comment by gmuloc** [comment]
no use case - AVD just did not use to be as helpful as it is now.
