### ISSUE TITLE
Add input character validation  to maximum number of character length for site /region /zone/device hostname as inputs in inventory.yaml 

### ISSUE THREAD

**Issue by mansihanda** [aristanetworks/ansible-avd#4001]
### Issue Summary

Currently there are no validation checks on inputs  (character length/type of characters/)on region zone /device hostname  via AVD . we should have that check . Also we should have an additional check that region /zone/device hostname  should same in router section (wan hierarchy )  and region to zone to site  association section in pathfinder meta studio.

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Create region/zone/site/device association in inventory.yaml  , Same names should be given as inputs on other related inputs via AVD provisioning . Also user should give inputs values to specific character length , type of characters etc for region /zone /site.
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
Thanks for opening the issue. Can you please provides what are the length and the allowed character set?

**Comment by gmuloc** [comment]
`pattern='[A-Za-z0-9_.:{}\[\]-]+'`
