### ISSUE TITLE
stun server-profile order of servers should be always the same

### ISSUE THREAD

**Issue by raghukar** [aristanetworks/ansible-avd#4065]
### Issue Summary

I see the following config mismatch reported on cvn10-tra-2
Desired
stun server-profile internet-cvn10-pf1-Ethernet1 internet-cvn10-pf2-Ethernet1
Running
stun server-profile internet-cvn10-pf2-Ethernet1 internet-cvn10-pf1-Ethernet1

All the configs are built with AVD.  So, it appears that sometimes the order "internet-cvn10-pf2-Ethernet1 internet-cvn10-pf1-Ethernet1" is reversed

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

None

### Steps to reproduce

```shell
I always use "make wan-build"
So, on cvn10-tra-1 and others I see the order is
stun server-profile internet-cvn10-pf2-Ethernet1 internet-cvn10-pf1-Ethernet1

Where as the above desired order is pf1, pf2
```

### Relevant log output

```shell
Config out of compliance
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
@raghukar - as it is not happening because of AVD I am closing this issue.
