### ISSUE TITLE
Change of site location is not resulting in finding different Zscaler end point

### ISSUE THREAD

**Issue by vinaygcArista** [aristanetworks/ansible-avd#4085]
### Issue Summary

AVD is not fetching the Zscaler end point based on the location of the site.

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
The issue is that we get old data, so when changing the location we still read the endpoints associated with the previous location.
