### ISSUE TITLE
Add TLV transmit ztp command

### ISSUE THREAD

**Issue by xaviramon** [aristanetworks/ansible-avd#4103]
### Enhancement summary

In campus, or management networks, ZTP is usually performed via a specific VLAN in a front port of the device, not using the management port. Usually, specific VLAN has to be used in order to allow the ZTP process to run.
lldp tlv transmit ztp vlan

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Networks with inband management over a specific VLAN.

### Describe the solution you would like

Allow configuration of `lldp tlv transmit ztp vlan <x>` command under a specific interface as discussed here: https://www.arista.com/en/support/toi/eos-4-27-1f/14879-campus-ztp-through-vlan-advertised-from-spine-aggregation-switch

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by Shivani-gslab** [comment]
I can see the implementation for this is already there in AVD  - https://github.com/aristanetworks/avd/blob/devel/python-avd/pyavd/_eos_cli_config_gen/j2templates/eos/ethernet-interfaces.j2#L472

Are we expecting anything else here?
@xaviramon @gmuloc

**Comment by xaviramon** [comment]
Implemented!
