### ISSUE TITLE
Use switch ID to generate the switch bgp_as number in combination with a new bgp prefix

### ISSUE THREAD

**Issue by chrisgerdener** [aristanetworks/ansible-avd#4108]
### Enhancement summary

Since we give our switches bgp_as numbers when defining them as nodes, it would be nice to automatically utilize the switch ID to generate a fitting bgp number, similar to what is done with IP addresses and loopback pools. 

Ideally you could define a bgp prefix, either for as.dot (which we use) or decimal notation and then simply add the value of the switch ID onto it. 

### Which component of AVD is impacted

eos_designs

### Use case example

As stated, making use of the ID to simplify bgp_as number assignment for nodes.

### Describe the solution you would like

There would be one new key "bgp_as_prefix" that is defined once for all switches and then a routine that adds the switch ID to the prefix. 

Today, the bgp_as number is defined for each node individually

 - name: SWITCHNAME
      id: 11
      bgp_as: "12345.00011"

For this feature request I imagine it simplified

bgp_as_prefix: "12345.00"

 - name: SWITCHNAME
      id: 11

resulting in the same bgp_as number of "12345.00011" being configured.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Hi Chris, I think we can do that already.
Try setting `bgp_as: "12345.0-65535"`. I know it won't configure the leading zeroes, but that will not be shown in EOS either, so I think this will be what you want.
Note that we do not tackle the dot-notation in `eos_designs` yet, so you will have to add that yourself to with structured config like:

```yaml
custom_structured_configuration_router_bgp:
  as_notation: asdot
```

details: https://avd.sh/en/devel/roles/eos_cli_config_gen/docs/input-variables.html?h=asdot#router-bgp

We are tracking to get asdot support in eos_designs (#3659), but it has not been picked up yet.

Please confirm if this works and close the issue if so. Please use discussions for general question.

Thanks!

**Comment by chrisgerdener** [comment]
Hi Claus,

This solution does work. Next time I will make a discussion post first. Many thanks for the help.
