### ISSUE TITLE
Add ability to provide custom metadata

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#4127]
### Enhancement summary

Right now the metadata schema is fixed and dies not allow any custom keys. It would be useful to accept a dict key "custom" that contains random data in dictionary format, that can be used by customer specific tools, in my case, a device can have a unique identifier in CMDB that I want to include in the metadata, or a particular role or feature that is. It part of the config and is specific to my organization.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Customer specific device level metadata

### Describe the solution you would like

An additional key in the metadata schema that accepts any dictionary structure of random keys.

### Describe alternatives you have considered

None

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
All schemas support custom keys starting with underscore.

**Comment by gusmb** [comment]
> All schemas support custom keys starting with underscore.

Thanks! I've tested this and works well for me. Closing.
