### ISSUE TITLE
eos_cli_config_gen: service unsupported-transceiver 

### ISSUE THREAD

**Issue by duddis1** [aristanetworks/ansible-avd#4171]
### Enhancement summary

We are implementing dot1x and some missing variables. We need to generate the following config

```
service unsupported-transceiver <removed>
```

to work around it we might have to use below config:

```
eos_cli: |
    service unsupported-transceiver <removed>
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

to work around it we might have to use below config:

```
eos_cli: |
    service unsupported-transceiver <removed>
```

### Describe the solution you would like

If model can be extended to support above that will be very useful
https://avd.arista.com/4.7/roles/eos_cli_config_gen/docs/input-variables.html?h=dot1x#__tabbed_22_2

### Describe alternatives you have considered

```
eos_cli: |
    service unsupported-transceiver <removed>
```

### Additional context

global configuration

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
This is already implemented (see test example [here](https://github.com/ClausHolbechArista/avd/blob/devel/ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/unsupported-transceiver.yml)) but kept out of the documentation for non-technical reasons. Please never expose the key. I have updated the text above to remove your key.
