### ISSUE TITLE
eos_cli_config_gen:radius_server/host/ssl_profile

### ISSUE THREAD

**Issue by thompsno** [aristanetworks/ansible-avd#4175]
### Enhancement summary

Allowing EOS device to connect to AGNI with  TLS SSL profile bound to Radius server.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Required data model
radius-server host radsec.beta.agni.arista.io vrf (x) tls ssl-profile (ssl-profile) timeout 10 retransmit 3

Current data model
radius-server host radsec.beta.agni.arista.io vrf (x) timeout 10 retransmit 3

Using
eos_cli: radius-server host radsec.beta.agni.arista.io vrf (x) tls ssl-profile (ssl-profile) timeout 10 retransmit 3

### Describe the solution you would like

To be able add a tls-ssl-profile to the host dictionary under radius server

https://avd.arista.com/4.8/roles/eos_cli_config_gen/docs/input-variables.html?h=eos+cli#radius-servers

### Describe alternatives you have considered

eos_cli: radius-server host radsec.beta.agni.arista.io vrf (x) tls ssl-profile (ssl-profile) timeout 10 retransmit 3

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by nnbruce** [comment]
We also need this for AGNI, created PR #4194.
