### ISSUE TITLE
eos_cli_config_gen: nac

### ISSUE THREAD

**Issue by duddis1** [aristanetworks/ansible-avd#4179]
### Enhancement summary

We are implementing nac config and some missing variables. We need to generate the following config

```
!
management api gnmi
 no shutdown
!
router segment-security
 no shutdown
```

to work around it it we might have to use the following config:
for management api grmi we do not have the option to shutdown.
```
eos_cli: |
!
management api gnmi
 no shutdown
!
router segment-security
 no shutdown
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

please detail your use caseto work around it it we might have to use the following config:
```
eos_cli: |
!
management api gnmi
 no shutdown
!
router segment-security
 no shutdown
```

### Describe the solution you would like

If model can be extended to support above that will be very useful
https://avd.arista.com/4.7/roles/eos_cli_config_gen/docs/input-variables.html?h=dot1x#__tabbed_22_2

### Describe alternatives you have considered

```
eos_cli: |
!
management api gnmi
 no shutdown
!
router segment-security
 no shutdown
```

### Additional context

nac configuration

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
Hello @duddis1. Thanks for opening the issue

for

```
router segment-security
 no shutdown
```

You have already: https://avd.arista.com/devel/roles/eos_cli_config_gen/docs/input-variables.html#__tabbed_148_2

```
router_segment_security:
  enabled: true
```

that will generate the config you need.

For the gnmi part, we have no key to generate the no shutdown today indeed. I have just checked on some cEOS device and a  7280 and cannot see the option:

```
host2(config-mgmt-api-gnmi)#no shutdown
% Incomplete command
host2(config-mgmt-api-gnmi)#show active
host2(config-mgmt-api-gnmi)#show cli commands
[no|default] APPEND [ COMMENT ]
[no|default] comment
do CMD
exit
[no|default] operation set persistence
[no|default] provider eos-native
show active
show active all [ detail ]
show comment
[no|default] transport grpc TRANSPORT_NAME
[no|default] transport grpc-tunnel TRANSPORT
```

can you please confirm the syntax and the platform?

**Comment by lateefwalana** [comment]
Hi @gmuloc
I agree, no shutdown option available for 750x platform either.

@duddis1 This was an error on our part, no shutdown is not an option. I will remove it from current configlet.

See switch config below.
```
!
management api gnmi
   transport grpc default
! 
```

**Comment by gmuloc** [comment]
Thanks @lateefwalana for confirmation

So @duddis1, as mentioned my previous comment, you have already: https://avd.arista.com/devel/roles/eos_cli_config_gen/docs/input-variables.html#__tabbed_148_2

```
router_segment_security:
  enabled: true
```
that will generate the config you need for router segment security 

for the config from @lateefwalana, I think this would do: https://avd.arista.com/4.9/roles/eos_cli_config_gen/docs/input-variables.html#management-api-gnmi

```
management_api_gnmi:
  transport:
    grpc:
      - name: default
```

If this does it for you then we can probably close this issue. Please let us know

**Comment by duddis1** [comment]
@gmuloc  We have to adopt new arista AVD version to test these changes, we will test and update you if any issues.

You can close this request if you want now.

**Comment by gmuloc** [comment]
Thanks @duddis1 will close for now - feel free to reopen if anything is missing!
