### ISSUE TITLE
Wrong CLI generated for radius-server dynamic-authorizaton

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#4198]
### Issue Summary

On cEOS the following config (currently present in molecule) is not accepted:
```
radius-server dynamic-authorization port 1700 tls ssl-profile SSL_PROFILE
```

instead it should look like:

```
radius-server dynamic-authorization port 1700
radius-server dynamic-authorization tls ssl-profile BLAH
```

to whomever picks this up: please double check on another device

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
copy the generated config in molecule test radius-server into an EOS CLI instance
```

### Relevant log output

```shell
edge4A(config)#radius-server dynamic-authorization port 1700 tls ssl-profile SSL_PROFILE
% Invalid input
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by nnbruce** [comment]
I can confirm that wrong CLI syntax is generated. Tested on 7280SR3 running EOS 4.31.3M and 7050SX3 running 4.29.5M.

```
leaf1(config)#radius-server dynamic-authorization port 3799 tls ssl-profile agni
% Invalid input
```
