### ISSUE TITLE
eos_designs: VARPv6 config is not generated even when "ipv6_enable: true" is specified

### ISSUE THREAD

**Issue by bjmeuer** [aristanetworks/ansible-avd#4203]
### Issue Summary

When I have "ipv6_enable: true" set I expect the ipv6_virtual_router_addresses config to work, but it does not. Reason is that in the code it is only checked if an "ipv6 address" is configured on the SVI:

Current code:

```
        # Only set VARPv6 if ipv6_address is set
        if vlan_interface_config["ipv6_address"] is not None:
            vlan_interface_config["ipv6_virtual_router_addresses"] = svi.get("ipv6_virtual_router_addresses")
            _check_virtual_router_mac_address(vlan_interface_config, ["ipv6_virtual_router_addresses"])
```

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI with AVD Runner

### Steps to reproduce

```shell
tenants:
  - name: All-Switches
    mac_vrf_vni_base: 10000

    vrfs:
      - name: HOSTING
        vrf_id: 1
        mlag_ibgp_peering_vlan: 4093
        ...
        svis:
          - id: 10
            name: hosting
            tags: ['fabric']
            description: hosting SVI
            enabled: true
            ip_address_virtual: 1.1.1.1/24
            ipv6_enable: true
            ipv6_virtual_router_addresses:
              - fe80::1
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
the current code actually points out this `# Only set VARPv6 if ipv6_address is set` I am not sure what is the reason but I would not call this a bug but an enhancement as it seems it was done on purpose

**Comment by ClausHolbechArista** [comment]
Pushing to 5.0 accepted by @bjmeuer.
