### ISSUE TITLE
Deprecate schema keys with Upper case letter

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#4244]
### Enhancement summary

Find any keys with uppercase  in eos_cli_config_gen and eos_designs schemas and deprecate in favor of lower case. 

Ex. `vxlan_interface.Vxlan1` -> `vxlan_interface.vxlan1`

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen

### Use case example

Ex. `vxlan_interface.Vxlan1` -> `vxlan_interface.vxlan1`

### Describe the solution you would like

deprecate the keys in favor of lower case. 

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by MaheshGSLAB** [comment]
There is only `Vxlan1` which need to be deprecate all others are already deprecated.
