### ISSUE TITLE
Fix(eos_cli_config_gen): Unexpected behavior of "validation_mode" setting

### ISSUE THREAD

**Issue by jmussmann** [aristanetworks/ansible-avd#4256]
### Issue Summary

eos_cli_config_gen behavior of "validation_mode" setting differs from the documentation (IMO).

Regardless of the configuration of "validation_mode", eos_cli_config_gen does not generate a config file, if the validation fails.

According to the docs I would only expect eos_cli_config_gen to fail and stop generating the config if validation_mode is set to “error”. This was the case in versions < 4.9.0.

> Validation Mode for AVD input data validation.
> Input data validation will validate the input variables according to the schema.
> During validation, messages will generated with information about the host(s) and key(s) which failed validation.
> “disabled” means that validation will not run.
> “error” will produce error messages and fail the task.
> “warning” will produce warning messages.
> “info” will produce regular log messages.
> “debug” will produce hidden debug messages viewable with -v.

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
- Add an unexpected variable to the structured config
- Run eos_cli_config_gen
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
@jmussmann can I ask you to test https://github.com/aristanetworks/avd/pull/4261 which should address this issue? Thanks.

**Comment by jmussmann** [comment]
@ClausHolbechArista Thank you for your fix. It works in my environment.
