### ISSUE TITLE
Blank Lines in eos_cli_con_gen device documentation

### ISSUE THREAD

**Issue by aphillipps** [aristanetworks/ansible-avd#428]
## Issue Type
Blank lines when features not defined

- Documentation Report

## Summary
The blank line between the different feature documentation or documentation tables should be added after the IF statement and not before otherwise there will be as many blank lines as non-defined features.

## Role or Module Name
eos_cli_config_gen

## Steps to reproduce
```jinja2
{%  if %}
...
{%   endif %}

{%   if router_bgp.vlans is defined and router_bgp.vlans is not none %}
**VLAN Based:**
...
{%   endif %}
```
In the case above if router_bgp.vlans is not defined, it will still add a blank line. If there are severals items that are not defined it will add a blank line for every item. 

### Expected results

Instead it should be:
```jinja2
{%  if %}
...
{%   endif %}
{%   if router_bgp.vlans is defined and router_bgp.vlans is not none %}

**VLAN Based:**
...
{%   endif %}
```

**Comment by titom73** [comment]
Closed as merged with PR #435
