### ISSUE TITLE
(eos_cli_config_gen) always generate hostname

### ISSUE THREAD

**Issue by mkurjanski** [aristanetworks/ansible-avd#4329]
### Enhancement summary

Hi, can we please change the `eos_cli_config_gen/templates/eos/hostnamej2` template  so it always generates the hostname? Or is it required by the CVP to remove it? Right now it can be disabled with the `generate_default_config` flag set to `false`. We use the flag to skip lines like `no enable password` and `no aaa root` which are truly default and don't show up in the running config. But the hostname always appear in the running config.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

We use the results of `eos_cli_config_gen` as a tool to generate the indented config which later we use as a basis for the running config compliance checks. It is important to all the non-default lines to be present in the config and all the default config lines to be removed. Most of the lines get correctly removed with `eos_cli_config_gen` - the only exception is the `hostname` config that we think should be always present.

### Describe the solution you would like

Remove the conditional:
```
{% if not generate_default_config is arista.avd.defined(false) %}
!
hostname {{ hostname | arista.avd.default(inventory_hostname) }}
{% endif %}
```

### Describe alternatives you have considered

Unconditionally print the hostname
```
!
hostname {{ hostname | arista.avd.default(inventory_hostname) }}
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Please check out #4361 which should address this (among many other things)

**Comment by mkurjanski** [comment]
Thanks for your response on this @ClausHolbechArista . In this case would you consider excluding the 'hostname' line from the scope of #4361 ? Or is there a good reason to have it disabled? The way I see it is that 'hostname' os not really a part of the default config as it's always present in the running config.

**Comment by ClausHolbechArista** [comment]
> Thanks for your response on this @ClausHolbechArista . In this case would you consider excluding the 'hostname' line from the scope of #4361 ? Or is there a good reason to have it disabled? The way I see it is that 'hostname' os not really a part of the default config as it's always present in the running config.

We do not want `eos_cli_config_gen` to assume that it creates a full config. Some users use multiple "configlet" each generated by `eos_cli_config_gen` to build the full config.
So if you want hostname to be set, you should add hostname in the input vars (as we do in `eos_designs`)

**Comment by mkurjanski** [comment]
It makes sense. Thanks for clarifying @ClausHolbechArista !
