### ISSUE TITLE
Feat (eos_cli_config_gen): Add support for SNMP server shape-rate

### ISSUE THREAD

**Issue by ctyrider** [aristanetworks/ansible-avd#4377]
### Enhancement summary

Add support for the following CLI syntax (at the global config level):

`snmp-server ifmib ifspeed shape-rate`

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Enable global support for SNMP ifspeed reflecting shaping rate

### Describe the solution you would like

Add support for eos_cli_config_gen along the lines of:

```
snmp_server:
  ifmib:
     ifspeed: <str; "shape-rate">

```       

### Describe alternatives you have considered

n/a

### Additional context

n/a

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ctyrider** [comment]
@gusmb - could we create a pull request for this one?

**Comment by ClausHolbechArista** [comment]
Please do:
```yaml
snmp_server:
  ifmib_ifspeed_shape_rate: <bool>
```
Thanks.
