### ISSUE TITLE
Feat (eos_cli_config_gen): Add support for BGP labeled-unicast 

### ISSUE THREAD

**Issue by colinmacgiolla** [aristanetworks/ansible-avd#4380]
### Enhancement summary

This is an extension of the existing BGP address family structures to support BGP-LU

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Configuration of BGP LU

### Describe the solution you would like

We already have `address_family_ipv4_multicast` and `address_family_ipv4_sr_te`. This solution would be to add another key, in the same structure for `address_family_ipv4_labeled_unicast`.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
`colinmacgiolla self-assigned this` Thank you!
