### ISSUE TITLE
On chassis switches add the ability to define "interface Ma0"

### ISSUE THREAD

**Issue by bingbucks** [aristanetworks/ansible-avd#44]
On chassis switches, I like to use "interface Ma0" which floats as a virtual IP address across both supervisors, which have the following physical management interfaces:

SUP #1:
interface management 1/1
interface management 1/2

SUP #2:
interface management 2/1
interface management 2/2

interface management0 floats between 1/1 and 1/2 when physically wired like this:
![image](https://user-images.githubusercontent.com/4934710/68552836-9fb62880-03e9-11ea-90ef-1c294ffc9df2.png)

Resulting in a config that looks like this:
interface Management0
   vrf forwarding MGMT
   ip address x.y.z.a/s

There are other combinations to consider, I'm sure. ;-)

**Comment by bingbucks** [comment]
Please add label "EVPN Design Guide"

**Comment by carlbuchmann** [comment]
@bingbucks is there any configuration required on the Physical interfaces? Or simply change the interface from default Management1 to Management0?

**Comment by bingbucks** [comment]
Here is a sample 7508 config:

interface Management0
   vrf forwarding MGMT
   ip address 10.10.20.15/24

That's it... And physically plug in ma1/1 and ma2/1... It might work with ma1/2 and ma2/2, but I never tried... I also have:

redundancy
   protocol sso

...but I don't think that SSO is needed... The default RTR (warm standby might be OK)... Yo no se...
