### ISSUE TITLE
Feat(eos_cli_config_gen): Set ssh authentication protocols and empty password

### ISSUE THREAD

**Issue by jmussmann** [aristanetworks/ansible-avd#4435]
### Enhancement summary

There is no option to set the ssh authentication protocols. Furthermore there is no way to set the empty-password setting.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Setting the authentication options in the management ssh section

### Describe the solution you would like

Adding authentication settings to the management_ssh schema and templates.

Example:

```
management ssh
    authentication protocol password
   ...
   authentication empty-passwords permit
   ...
   !
   vrf test
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Please update the text with a snip of the CLI you need to generate.
