### ISSUE TITLE
deploy failed when using % character in 'prompt'

### ISSUE THREAD

**Issue by PieterL75** [aristanetworks/ansible-avd#4459]
### Issue Summary

I have a config variable set to 
`prompt: "{{ '[%D{%H:%M:%S}]%s%h%R%v%P' }}"`
( I have to use the curlybrackets string to get the % signs in the group_vars. )

The intended config is nicely generated, containing `prompt [%D{%H:%M:%S}]%s%h%R%v%P`

When I run the 'deploy.yml' playbook, I get an error that `Encountered unknown tag 'H'`
It relates to the %H value in the prompt.

The deploy parser should not parse any %variables.

on a sidenote: that prompt variable is not in the structured_configs, which is odd

### Which component(s) of AVD impacted

eos_config_deploy_eapi

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Create a group_var in the fabric
prompt: "{{ '[%D{%H:%M:%S}]%s%h%R%v%P' }}"`

build the configuration
deploy the configuration
```

### Relevant log output

```shell
TASK [arista.avd.eos_config_deploy_eapi : Replace configuration with intended configuration] *************************************************************************************************************************
fatal: [cp002-sps-04]: FAILED! => {"changed": false, "msg": "template error while templating string: Encountered unknown tag 'H'.. String: !RANCID-CONTENT-TYPE: arista\n!\nprompt [%D{%H:%M:%S}]%s%h%R%v%P\n!\nvlan internal order descending range 4000 4090
<rest of the full intended config>
end\n. Encountered unknown tag 'H'."}
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
This is a limitation of the ansible connection plugins, and not something that is solvable from our side.
FYI another way of getting the {% in is by marking the var as "unsafe", stopping Ansible from trying to template it.

```yaml
prompt: !unsafe "%H__%D{%H:%M:%S}%v%P"
```

**Comment by PieterL75** [comment]
That's a nice tip. thx !
The build now works without that I have to use the "{{' trick.

The problem however is in the deploy part. there the parser still sees that {%H as a tag...

any suggestion on that ?

**Comment by ClausHolbechArista** [comment]
> That's a nice tip. thx ! The build now works without that I have to use the "{{' trick.
> 
> The problem however is in the deploy part. there the parser still sees that {%H as a tag...
> 
> any suggestion on that ?

I am not sure why the config is being thrown through Jinja on it's way out. I believe this is caused by Ansible's connection plugin for EOS.

The best way around it is to use CloudVision to push your configs :) But short of that maybe we can hack it by combining our two "solutions" above.

so 

```yaml
prompt: !unsafe "{{ '%H__%D{%H:%M:%S}%v%P' }}"
```

The `prompt` data model is an `eos_cli_config_gen` model, so it will not be picked up by `eos_designs`, hence it will not be included in the produced "structured config". You can prefix it like `custom_structured_configuration_prompt` to get it included.

**Comment by PieterL75** [comment]
crazy ! but it works :-D

That eos_config_deploy_eapi code
`prompt: !unsafe "{{ '%H__%D{%H:%M:%S}%v%P' }}"`
generates this code in the intended config:
`prompt {{ '%H__%D{%H:%M:%S}%v%P' }}`
and when deployed, it becomes
`prompt %H__%D{%H:%M:%S}%v%P`

nice workaround, much appreciated !

Pieter
