### ISSUE TITLE
Bug(eos_cli_config_gen, eos_designs): Monitor-session needs correction

### ISSUE THREAD

**Issue by laxmikantchintakindi** [aristanetworks/ansible-avd#4524]
### Issue Summary

Monitor-session needs correction. When we create assign an access-group at session level, we cant assign a different access-group to the source interfaces.

```
s1-leaf1(config)#monitor session m1 ip access-group ipv4ACL
! Access list ipv4ACL not configured. Assigning anyway.
s1-leaf1(config)#monitor session m1 source ethernet 1 ipv6 access-group abcd
! Source Ethernet1 in Session m1 is applied with access list ipv4ACL with type ip instead of access list abcd with type ipv6. Only one access list type per session is supported.
```

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

PyAVD

### Steps to reproduce

```shell
Create a monitor session and add ip access-group command.
Try adding ipv6 access-group command with source interface.
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
The statement here is not completely correct. It is the different _type_ of ACL that is conflicting. So `ip` on one and `ipv6` on the other. The last part of the error says so: `Only one access list type per session is supported.`

**Comment by laxmikantchintakindi** [comment]
> The statement here is not completely correct. It is the different _type_ of ACL that is conflicting. So `ip` on one and `ipv6` on the other. The last part of the error says so: `Only one access list type per session is supported.`

Even a different ACL of the same type is not allowed.

s1-leaf1(config)#monitor session m1 source ethernet 1 ip access-group abcd
! Source Ethernet1 in Session m1 was applied with access list abc of acl type ip, please remove this access list first before applying another access list.
s1-leaf1(config)#sh run | s monitor
monitor session m1 ip access-group abc
monitor session m1 source Ethernet1
