### ISSUE TITLE
Update supported WAN features

### ISSUE THREAD

**Issue by JulioPDX** [aristanetworks/ansible-avd#4539]
### Issue Summary

Update WAN docs to list what is supported vs still in progress. For example, peering with WAN L3 connections should be supported but still listed as [future work](https://avd.arista.com/devel/roles/eos_designs/docs/how-to/wan.html#future-work)

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
This PR was not integrated in the how-to: https://github.com/aristanetworks/avd/pull/4079

**Comment by gmuloc** [comment]
Fixed in #4543
