### ISSUE TITLE
generated vars folder restructure

### ISSUE THREAD

**Issue by bingbucks** [aristanetworks/ansible-avd#46]
It may make sense to keep "generated_vars", "intended_configs", & "documentation" in their own directory called "derived_objects" and then that way the only directories at the scope below "physical_poc" are "derived_objects", "group_vars" and "config_backup". This may assist segmenting what's really an input and what's really an output.

In addition, move "inventory.yml" into "group_vars" as that is also an input.

**Comment by carlbuchmann** [comment]
moved all auto-generated configs (structure YAML and eos config under intended/structured_configs and intended/configs for clarity.
see commit: 92426e1f38b47fae0ad426c34f5fdb28c966e18a

**Comment by carlbuchmann** [comment]
resolved with PR #68
