### ISSUE TITLE
PoE configuration is not rendered to structured config for interfaces in port-channel

### ISSUE THREAD

**Issue by nathanmusser** [aristanetworks/ansible-avd#4600]
### Issue Summary

When interfaces are in a port-channel they don't render PoE configuration (unless they're in fallback individual mode). In my use case we have an access point with a port-channel and powered by poe. We want to change the default behavior of keeping poe up while the port is admin down. 

```
interface EthernetX
   shutdown
   switchport
   channel-group Y mode active
   poe shutdown action power-off
!
interface Port-ChannelY
   no shutdown
   switchport
   switchport access vlan 100
!
```

There are a few workarounds: 

- Set the poe behavior globally - in our use case we went to tweak behavior of poe on a single port-channel, for example a certain type of poe device might need different configuration. 
- Use structured config to pass the poe values down to eos_cli_config_gen - this is our current workaround
- If fallback mode individual is appropriate a fallback profile with poe settings on it can be used to

Ultimately I marked this as a bug because it doesn't seem intuitive that poe settings and port-channel membership are mutually exclusive and I didn't see any warning messages or documentation regarding this relationship. Structured config solves the issue relatively easily for me, so maybe documenting this relationship is enough if this behavior is intentional or desired for some reason. 

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Place a connected endpoint in port-channel and try to set poe configuration.
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
Hi @nathanmusser thanks for opening the issue.
So the idea would be to move POE config to the common ethernet interface config: https://github.com/aristanetworks/avd/blob/devel/python-avd/pyavd/_eos_designs/structured_config/connected_endpoints/ethernet_interfaces.py#L153

This would mean that we don't call the adapter_poe method from the `_update_ethernet_interface_cfg` method.
This change would be breaking as this would mean that the POE config coming from the LACP fallback mandatory profile would now be ignored and would have to be moved to the adapter or the "main" profile used under the adapter. Your issue also demonstrates that the LACP fallback config we render today is impacting the non-fallback scenario which is not great.

We want to get this breaking change for 5.0.0 if that makes sense.

Let us know if you want to pick it up and we can help write the porting guide entry to explain what is breaking.

**Comment by nathanmusser** [comment]
That makes sense and lines up with my intentions after looking at the code. I'll get a PR for it put together.
