### ISSUE TITLE
Support for Interface  Profiles in port-channel interfaces

### ISSUE THREAD

**Issue by JaakkoRautanen** [aristanetworks/ansible-avd#4621]
### Enhancement summary

Port-channel interfaces in EOS support Interface Profiles just like normal Ethernet interfaces. However, AVD doesn't have that feature in [port-channel-interfaces.j2](https://github.com/aristanetworks/avd/blob/devel/python-avd/pyavd/_eos_cli_config_gen/j2templates/eos/port-channel-interfaces.j2). Let's add it.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Attach Interface Profile to port-channel interface.

### Describe the solution you would like

You should be able to refer to Interface Profiles under port-channel interface same way as with Ethernet interfaces: `profile: <str>`

Solution can be copied from [ethernet-interfaces.py](https://github.com/aristanetworks/avd/blob/b5251e9486db45ce5d4d64b8c2fc3e046f8c0ecc/python-avd/pyavd/_eos_cli_config_gen/j2templates/eos/ethernet-interfaces.j2#L11).

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by JaakkoRautanen** [comment]
I'm interested in contributing. What else shall I update than jinja2 template?

**Comment by ClausHolbechArista** [comment]
> I'm interested in contributing. What else shall I update than jinja2 template?

You would need to update the schema fragment for `port_channel_interfaces` as well and then add a test in `ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/port-channel-intefaces.yml` or similar.

Let us know if you need help.

**Comment by JaakkoRautanen** [comment]
So now I have added interface profile to j2 template as well as test to `...host_vars/port-channel-intefaces.yml` and expected cli result to `...intended/configs/port-channel-intefaces.cfg`.

Where I can find schema fragment?

**Comment by gmuloc** [comment]
Hi @JaakkoRautanen - You can find the schema you are looking for in https://github.com/aristanetworks/avd/tree/devel/python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments

**Comment by JaakkoRautanen** [comment]
I think I found schema fragment part.

What about documentation? Where should I add information about interface profile part?

**Comment by gmuloc** [comment]
documentation is auto-generated when you run pre-commit locally - so in theory you have nothing to do in this case

https://avd.arista.com/5.0/docs/contribution/development-tooling.html#pre-commit

**Comment by JaakkoRautanen** [comment]
Hey, I think I made my best and came up with draft PR. Could somebody check it?
