### ISSUE TITLE
Documentation enhancement for ip-extended-access-lists schema 

### ISSUE THREAD

**Issue by rewati-arista** [aristanetworks/ansible-avd#4642]
### Enhancement summary

The documentation for [ip-extended-access-lists](https://avd.arista.com/4.10/roles/eos_cli_config_gen/docs/input-variables.html#ip-extended-access-lists), specifically the source_ports_match and destination_ports_match fields should mention the dependency on source_ports and destination ports field respectively. 

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

In my use case I am generating these input variable schema from my model data. I then supply the input schema to [pyavd utility ](https://github.com/aristanetworks/avd/blob/devel/python-avd/pyavd/get_device_config.py)that helps me generate eos cli.

While I was implementing the mapping from my data to these structured configs I was providing all the fields that i had in my data model, eg: sequence number, action, protocol, source, destination and so forth. In this I was also providing source_ports/destination ports which were sometimes empty lists. But because I included the "source_ports" key and a respective empty value, avd while generating eos config added the source_ports_match with a default value of "eq" which is incorrect cause that results to a config like 

`80 permit udp any eq `

where eq is followed by no source ports.

I then corrected my logic to add "source_ports" key only when source ports exist so that source_ports_match does not get added by default.

### Describe the solution you would like

The documentation could explicitly mention that source_ports_match key gets added with a default value when source_ports key is found, and if you do not want that then do not add the source_ports key itself when source_ports are empty (cause technically adding empty source ports is not incorrect so users could do that and run into this issue). 

Alternatively in the logic over [here](https://github.com/aristanetworks/avd/blob/3cac535c16978abb099f159b0bd6839536a9108c/python-avd/pyavd/_eos_cli_config_gen/j2templates/eos/ip-access-lists.j2#L57) where avd adds the source_port_match by default when source_port key is found, change it to add the source_port_match when actual non none value of source port is found (instead of just depending on presence/absence of source port key).

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
I think this can be addressed easily by adding `min_length: 1` to the schema for the ports. So if set, it must be a list with at least one item.

**Comment by rewati-arista** [comment]
yep agreed, just being cautious and mentioning again that this does not mean making it a required argument but instead just that if the field is set it should be non empty.
