### ISSUE TITLE
Support for all dot1x keys under port-profiles and adapters.

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#4647]
### Issue Summary

seen on V4.10.1, validation generates messages but config renders properly.

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
port_profiles:
  - profile: endpoint_access_dot1x
    description: Endpoint access port (Dot1x enabled)
    mode: access
    dot1x:
      port_control: auto
      reauthentication: true
      pae:
        mode: authenticator
      mac_based_authentication:
        enabled: true
        host_mode_common: false
      eapol:
        disabled: false
        authentication_failure_fallback_mba:
          enabled: true
          timeout: 10
```

### Relevant log output

```shell
[WARNING]: [switch1]: 'Validation Error: port_profiles[7].dot1x': Unexpected
key(s) 'eapol' found in dict.
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
It is not really a bug, since we do not document support for the `eapol` key. I will update the schema to reflect the full eos_cli_config_gen schema, since that is also how the code relays the data.
