### ISSUE TITLE
Refactor(eos_cli_config_gen): The `type` key should be `required` under `aaa_server_groups` and need to add defined check for `servers` key

### ISSUE THREAD

**Issue by Shivani-gslab** [aristanetworks/ansible-avd#4650]
### Issue Summary

~~- [ ] The `type` key under `aaa_server_groups` should be `required` as per EOS CLI.~~
- [x] The `servers` key is not a `required` key but it has not been checked "if defined or not in the template", so it throws error if not defined. The template needs to be fixed.

```
aaa_server_groups:
    - name: TACACS
       type: tacacs+            ----------> [ this should be a required key ]
       servers:                     ----------> [ defined check should be added for this ] 
           - server: 10.10.11.157 
              vrf: mgt
```
       
### Originally posted in PR #4626 

             The `type` key should be `required` in schema.
Also, the same issue as tacacs server - `servers` key is not required but its not checked for defined in template so it throws error if not defined. (need to update j2 template)

_Originally posted by @Shivani-gslab in https://github.com/aristanetworks/avd/pull/4626#discussion_r1814931414_
            

### Steps to reproduce:

Give the following input to eos_cli_config_gen role - 

```
aaa_server_groups:
    - name: TACACS
      type: tacacs+
    - name: TACACS2
```

**Comment by ClausHolbechArista** [comment]
~In eos_cli_config_gen we try to just ignore incomplete entries. So just add if-defined checks in the templates.~ nevermind. when absolutely required for CLI I am ok with using the required in schema.

**Comment by laxmikantchintakindi** [comment]
The check for `servers` key is already present and I have modified the template instead of adding `required:true`.
