### ISSUE TITLE
Feat(eos_validate_state): Add option to exclude endpoint_ports from LLDP neighbour validation

### ISSUE THREAD

**Issue by bjmeuer** [aristanetworks/ansible-avd#4675]
### Enhancement summary

if connected_endpoints are configured and the validation role is run it complains about not finding a LLDP neighbor. But as most of the connected endpoints don't send LLDP this is expected. 

### Which component of AVD is impacted

eos_validate_state

### Use case example

In my environment I have connected_endpoints which don't talk LLDP. The validate State will show Fail for these. 

example:
['156', 'DC1-LEAF-01A', 'Connectivity', 'VerifyLLDPNeighbors', 'Verifies that the provided LLDP neighbors are connected properly.', 'Local: Ethernet8 - Remote: Server Eth1', 'FAIL', 'No LLDP neighbor(s) on port(s):\n   Ethernet8']

### Describe the solution you would like

either use the existing option `validate_state:` in the connected_endpoint model to disable LLDP checks as well or introduce a new option at the same level like `validate_lldp:`

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
I would call this a bug, that we don't honor the validate_state key on the endpoint. Thank you for reporting!

**Comment by bjmeuer** [comment]
> I would call this a bug, that we don't honor the validate_state key on the endpoint. Thank you for reporting!
@ClausHolbechArista 

this one is honored, but only for checking the state, something like up/up. This is a separate check from LLDP. For attached servers the state check is fine, but lldp might not be fine.

maybe the model can be changed in that way:

```
ethernet_interface:
  ...
  validate:
     state: <bool>
     lldp: <bool>
```

**Comment by ClausHolbechArista** [comment]
If I understand correctly, we have two things here:
1. `validate_state: false` should also disable LLDP tests
2. Ask for a new option to disable the LLDP test while keeping the remaining validate state checks.

For 2. I think we should add `validate_lldp: <bool; default=True>`.

EDIT: The description for `validate_lldp` should make it clear that `validate_state: false` will also disable LLDP. It would not make sense to validate LLDP for a host that may be down.

**Comment by gmuloc** [comment]
To whomever picks this up.

Please open two PRs, one to fix the bug (point 1) and then one for the enhancement (point 2).
Only the second PR should close the issue (and be merged after the first one)
