### ISSUE TITLE
dc-force-config.yml playbook on a chassis switch reports failure, but appears to succeed

### ISSUE THREAD

**Issue by bingbucks** [aristanetworks/ansible-avd#47]
![image](https://user-images.githubusercontent.com/4934710/68638944-1843e480-04d1-11ea-88d1-322bc8467bbd.png)

**Comment by carlbuchmann** [comment]
This is more of a control node-specific issue and can be resolved:
 - increasing timeout values in ansible.cfg
 - or by leveraging httpapi (eAPI) instead network_cli (ssh), which provide better overall performance.
