### ISSUE TITLE
Refactor Python util `get_all`

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#4726]
- we could avoid splitting and rejoining the path by using an inner function to do the recursion

- get_all is only used in 6 places so we can refactor the path to be a list if we want to.

_Originally posted by @ClausHolbechArista in https://github.com/aristanetworks/avd/pull/4603#discussion_r1842318309_

**Comment by gmuloc** [comment]
Done in #4757
