### ISSUE TITLE
Bug: Invalid command for lldp management-addres <ip address> render

### ISSUE THREAD

**Issue by MaheshGSLAB** [aristanetworks/ansible-avd#4779]
Invalid command for lldp management-addres <ip address> render. The command is not supported on EOS 4.32.2F.

_Originally posted by @MaheshGSLAB in https://github.com/aristanetworks/avd/pull/4722#discussion_r1868871589_

**Comment by gmuloc** [comment]
the issue is in the input - it should not be an IP address but an interface 
```
site3-wan1(config)#show run se lldp
lldp management-address Ethernet3
```

lets jsut change the molecule test and maybe add some comment in the description

**Comment by MaheshGSLAB** [comment]
> the issue is in the input - it should not be an IP address but an interface
> 
> ```
> site3-wan1(config)#show run se lldp
> lldp management-address Ethernet3
> ```
> 
> lets jsut change the molecule test and maybe add some comment in the description

yes i miss understood by key name as address is mentioned in key name(management_address). Will update the description in one of PR. Closing this issue.
Thanks
