### ISSUE TITLE
ENHANCEMENT: UPLINK is not really an uplink, but a downlink

### ISSUE THREAD

**Issue by bingbucks** [aristanetworks/ansible-avd#48]
interface Ethernet3/1/1
   description P2P_**UPLINK**_TO_LEAF-1_Ethernet53/1

Perhaps when the description is relative to a Spine's perspective down to a leaf, maybe "DOWNLINK" or "LINK" is cleaner.

**Comment by carlbuchmann** [comment]
will standardize all P2P descriptions to LINK for leafs and spines
