### ISSUE TITLE
Redistribute Routes wont merge for VRF

### ISSUE THREAD

**Issue by theotherguy2175** [aristanetworks/ansible-avd#4800]
### Issue Summary

When testing the new redistribute_routes change everything works if I use a bogus name for a VRF that doesn't exist in AVD. However when updating the name to a VRF that does exist I get the error:

ERROR! [borderA1.ictc]: The input data model 'router_bgp.vrfs[1].redistribute_routes' is deprecated and cannot be used in conjunction with the new data model 'router_bgp.vrfs[1].redistribute'. This usually happens when a data model has been updated and custom structured configuration still uses the old model. See the porting guide on https://avd.arista.com for details.

### How do you run AVD ?

Ansible CLI with AVD Runner

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
`redistribute_routes` is the _old_ model, which should not be used any longer. At least not in conjuction with the new model which `eos_designs` produces. This is what the error message is saying.

If you look at the structured config for the device, you can see `redistribute:` being set under the VRF. This comes from `eos_designs`. You should be using this same model if you are adding custom structured configuration to the same VRF.

**Comment by theotherguy2175** [comment]
That worked thank you
