### ISSUE TITLE
Add OSPF for port channels interfaces

### ISSUE THREAD

**Issue by ksator** [aristanetworks/ansible-avd#492]
**Issue Type**

- Template enhancement
- Role enhancement

**Is your feature request related to a problem? Please describe.**
No. 
eos_cli_config_gen role currently supports OSPF for Ethernet interfaces but not yet for Port Channels interfaces.  

**Describe the solution you'd like**
Add OSPF for port channels interfaces

**Comment by ksator** [comment]
There is currently no port channel support for uplinks.  
Should I work using eos_cli_config_gen role to add ospf on port channels on non uplinks ports?

**Comment by ClausHolbechArista** [comment]
Resolved by PR #783
