### ISSUE TITLE
Filter tags for VRF

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#504]
**Issue Type**

- Template enhancement
- Role enhancement
- Documentatin enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

If there is scale in question for any tenant called under the node-group we will create all the VRFs associated to the tenant. This will create problems with scaled setups, because even though we don't have any SVI, ports in that node-group we will create the all the VRFs.

**Describe the solution you'd like**

To have a knob that allows us to filter and tag the VRFs only that we have the SVIs for that we want in a node group, instead of enabling all VRFs.

```
{# Leaf tenant vrfs #}
{% for tenant in tenants | arista.avd.natural_sort if ( tenant in leaf.filter_tenants or "all" in leaf.filter_tenants ) and leaf.evpn_services_l2_only == false %}
{%     if tenants[tenant].vrfs is defined %}
{%         for vrf in tenants[tenant].vrfs | arista.avd.natural_sort if vrf in leaf.vrfs %}
{%             if loop.first %}
## {{ tenant }} ##
{%             endif %}
  {{ vrf }}:
    tenant: {{ tenant }}
    ip_routing: true
{%         endfor %}
{%     endif %}
{% endfor %}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by ksator** [comment]
Hello I was about to assign myself this issue. 

But I would like first to discuss with you about the use case.  
What do we want to achieve with this additional tag (vrf_tag)? 

We already support filters: 
- for tenants (a tenant has several vrfs. each vrf has several svi) 
- and based on tags (svi and vlans).  

**So maybe there is no need to add filters per VRF ...**

Indeed, in the current code (see below) the vrf + svi + vlan are added based on the same conditions. 
I mean: 
- if we filter a tenant, we wont have any vrf/svi/vlan from the excluded tenants.   
- if we filter using existing tags (svi), a vrf is going to be created only if: 
  - the parent tenant is not filter
  - at least one svi of the vrf is not filter. and in that case, vrf + svi + vlan will be created.   
  
so, using existing filtering capabilities (tenants and tags) we control which vrf to create/skip. 

The only use case I see is to filter based vrfs and to deploy all svi of the allowed vrfs.
But in that case we can simply add the vrf name in the svi tags list. There is no need to add an new filter.  

```
{% set leaf.vrfs = []  %}
{% set leaf.svis = []  %}
{% set leaf.vlans = []  %}
{% for tenant in tenants | arista.avd.natural_sort if tenant in leaf.filter_tenants or "all" in leaf.filter_tenants %}
{%     if tenants[tenant].vrfs is defined %}
{%         for vrf in tenants[tenant].vrfs | arista.avd.natural_sort %}
{%             for svi in tenants[tenant].vrfs[vrf].svis | arista.avd.natural_sort %}
{%                 for svi_tag in tenants[tenant].vrfs[vrf].svis[svi].tags %}
{%                     if svi_tag in leaf.filter_tags or svi_tag == leaf.group or "all" in leaf.filter_tags %}
{%                         do leaf.vrfs.append( vrf ) %}
{%                         do leaf.svis.append( svi | int) %}
{%                         do leaf.vlans.append( svi | int) %}
{%                         break %}
{%                     endif %}
{%                 endfor %}
{%             endfor %}
{%         endfor %}
{%     endif %}
{%     if tenants[tenant].l2vlans is defined %}
{%         for l2vlan in tenants[tenant].l2vlans | arista.avd.natural_sort %}
{%             for vlan_tag in tenants[tenant].l2vlans[l2vlan].tags %}
{%                 if vlan_tag in leaf.filter_tags or vlan_tag == leaf.group or "all" in leaf.filter_tags %}
{%                     do leaf.vlans.append( l2vlan | int) %}
{%                     break %}
{%                 endif %}
{%             endfor %}
{%         endfor %}
{%     endif %}
{% endfor %}
{% set leaf.vrfs = leaf.vrfs | unique  %}
```

**Comment by carlbuchmann** [comment]
This is required for certain DCI use cases, where only VRFs need to be created and no associated SVIs or routed interfaces.
