### ISSUE TITLE
Additional Tenant VRF settings (BGP/Static)

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#510]
**Issue Type**

- Template enhancement
- Role enhancement
- Documentatin enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

There are a couple of more things we can do to allow more flexibility for deploying various scenarios/services.

1. Static routes in tenant VRF and under the BGP vrf tenant support for redistribute static
2. BGP peering inside tenant VRF to the external routers or firewalls for dynamic routing

**Describe the solution you'd like**

1. Solution for static
```
interface Vlan {{ VLAN_ID }}
   vrf {{ VRF_ID }}
   ip address virtual {{ SVI_IPV4_ADDRESS }} / {{ SUBNET_MASK }}
!
ip routing vrf {{ VRF_ID }}
ip route vrf {{ VRF_ID }} {{ IP_PREFIX }} / {{SUBNET_MASK }} {{ PREFIX_GATEWAY }}
!
router bgp {{ ASN }}
   vrf {{ VRF_ID }}
      redistribute connected
      redistribute static
```

2. BGP

```
!
interface Vlan {{ VLAN_ID }}
   vrf {{ VRF_ID }}
   ip address {{ SVI_IPV4_ADDRESS }} / {{ SUBNET_MASK }}
   ip virtual-router address {{ VARP_IPV4_ADDRESS }}
!
ip routing vrf {{ VRF_ID }}
!
router bgp {{ LEAF_ASN }}
   vrf {{ VRF_ID }}
      neighbor {{ NODE_A_IPV4_ADDRESS }} remote-as {{ REMOTE_AS }}
      neighbor {{ NODE_A_IPV4_ADDRESS }} next-hop-self
      neighbor {{ NODE_A_IPV4_ADDRESS }} send-community standard
      redistribute connected
      !
      address-family ipv4
         neighbor {{ NODE_A_IPV4_ADDRESS }} activate
```

**Describe alternatives you've considered**

**Additional context**

**Comment by titom73** [comment]
Work in progress by @emilotep
