### ISSUE TITLE
Add IS-IS interface level knobs to port-channels

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#524]
## Issue Type

- Bug Report
- Documentation Issue Report
- EOS Configuration error

## Summary

Missing from port-channels documentation and templates

```
    isis_enable: < ISIS Instance >
    isis_passive: < boolean >
    isis_metric: < integer >
    isis_network_point_to_point: < boolean >
```

### OS / Environment

__EOS Version__

__Cloudvision version__ (optional)

__OS running Ansible__

## Steps to reproduce

```yaml

```

### Expected results

```shell
$
```

### Actual results

```shell

```

**Comment by ksator** [comment]
There is currently no port channel support for uplinks.  
Should I work using eos_cli_config_gen role to add isis on port channels on non uplinks ports?

**Comment by onurgashi** [comment]
Opened just for tracking, yes you are right it is like that. However in case anyone wants to use cli_config_gen better to have it everywhere. So this is an optional / non-critical issue.

Thanks,
Onur
