### ISSUE TITLE
CVP - configure -cvsourceip in daemon TerminAttr EVPN design guide enhancement

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#53]
Implementing `-cvsourceip` in __TerminAttr__ daemon allows to support two use cases:

- Registration of the device using [provision.py](https://github.com/brokenpackets/CVP_Provisioning/blob/master/provision.py) script
- Device connected to CVP via a loopback or an SVI

Configuration example for __TerminAttr__ < `1.7`
```
daemon TerminAttr
   exec /usr/bin/TerminAttr -ingestgrpcurl=10.83.12.79:9910 -cvcompression=gzip -taillogs -ingestauth=key,xxx \
-smashexcludes=ale,flexCounter,hardware,kni,pulse,strata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent \
-ingestvrf=default -cvsourceip=<Device_Source_IP>
   no shutdown
```

Configuration example for __TerminAttr__ >= `1.7`
```
daemon TerminAttr
   exec /usr/bin/TerminAttr -ingestgrpcurl=10.83.12.79:9910 -cvcompression=gzip -taillogs -cvauth=key,xxx \
-smashexcludes=ale,flexCounter,hardware,kni,pulse,strata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent \
-ingestvrf=default -cvsourceip=<Device_Source_IP> -cvvrf=default 
   no shutdown
```

**Comment by carlbuchmann** [comment]
@titom73 should we make the default TerminAttr < 1.7 ?

**Comment by titom73** [comment]
We should keep __TerminAttr__ < 1.7 the default one as 1.6.1 is minimum version supported by __CVP2019.1.x__. Maybe an option to select TerminAttr version might be useful to generate correct configuration in the future.

This `-cvsourceip` is useful when you are using external ZTP server for security requirements. Indeed, once device is streaming to CVP, you have to register it to get it part of provisioning section.

This registration can be done manually or by using a script like [this one](https://github.com/brokenpackets/CVP_Provisioning/blob/master/provision.py) from @brokenpackets which needs to have `-cvsourceip` configured.

**Comment by carlbuchmann** [comment]
@titom73 just wanted to confirm the default cv source ip should be the mgmt interface ip?

**Comment by titom73** [comment]
Hi @carlbuchmann 
Recommended design is to use Management interface for CV communication. All our design use this approach.
