### ISSUE TITLE
Knob to disable dual-primary for MLAG in L3LS

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#532]
**Issue Type**

- Template enhancement
- Role enhancement
- Documentatin enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

In some cases there are no management links and we should consider this scenario when forming MLAG and rely on the port-channel instead.

**Describe the solution you'd like**

```
mlag configuration
   domain-id DC1_POD2_LEAF1
   local-interface Vlan4094
   peer-address 10.254.252.1
  ---   peer-address heartbeat 192.169.0.13 vrf MGMT
   peer-link Port-Channel1
  --- dual-primary detection delay 5 action errdisable all-interfaces
```
We would need to create a knob so it allows us to enable/disable dual-primary over management.

mlag:
   dual-primary: < true (default) | false >

**Describe alternatives you've considered**

**Additional context**

**Comment by ksator** [comment]
@onurgashi @titom73 
I am adding a var `dual_primary_detection` (default is true) to l3leaf/defaults and l3leaf/node_groups/group and l2leaf/defaults and l2leaf/node_groups/group. 
already done for l3leaf  
This var will be consumed by l3ls role to generate structured conf that will be consumed by cli_config_gen role.  
No need to set this var at fabric level as we can set it at  l3leaf/defaults  and l2leaf/defaults ?

**Comment by onurgashi** [comment]
Exactly, so we can specify this globally, and also per device if we want to
make changes.

**Comment by ksator** [comment]
done. will add molecule tests and will update doc later on. meanwhile I am submitting a draft PR so this can be reviewed
