### ISSUE TITLE
Update BGP max-paths and ecmp for Super Spine and OverlayC in l3ls_evpn

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#537]
## Issue Type

- Bug Report
- Documentation Issue Report
- EOS Configuration error

## Summary

It covers the rest of the devices, but testing it on super spine and overlay controller device types, it doesn't make any changes.

```
# BGP multi-path
# If not defined these values will be equal by default to the number of spines in the fabric
# If defined the values defined will both be applied to leaf and spine switches
# Note: these values are only relevant for an eBGP scenario
bgp_maximum_paths: <number_of_max_paths>
bgp_ecmp: <number_of_ecmp_paths>
```

## Role or Module Name
eos_l3ls_evpn

### OS / Environment

__EOS Version__

__Cloudvision version__ (optional)

__OS running Ansible__

## Steps to reproduce

```yaml

```

### Expected results

```shell
$
```

### Actual results

```shell

```

**Comment by carlbuchmann** [comment]
@Onur @ClausHolbechArista - can you produce test artifacts here: https://github.com/ClausHolbechArista/claus-l3ls-dev
