### ISSUE TITLE
IP Helper in l3ls_evpn template issues

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#539]
## Issue Type

- Bug Report
- Documentation Issue Report
- EOS Configuration error

## Summary

We need to update the template to consider the following:
- Not every time we define any ip helpers we need source_interface (it should be optional)
- When we define source_interface we should not append any vrf to it
- VRF should be optional
- If we define source interface or we only use helper-address don't append the local vrf by default

If we don't specify source_interface code fails.

```
svi_profiles:
  profile_1:
    mtu: 9000
    enabled: true
    ip_helpers:
      10.1.1.1:
        source_interface:
```

Mistake
```
interface Vlan12
   description Tenant_A_OP_Zone_Test
   mtu 9000
   vrf Tenant_A_OP_Zone
   ip helper-address 10.1.1.1 vrf Tenant_A_OP_Zone
```

```
svi_profiles:
  profile_1:
    mtu: 9000
    enabled: true
    ip_helpers:
      10.1.1.1:
        source_interface: Loopback1
```

Mistake

```
interface Vlan12
   description Tenant_A_OP_Zone_Test
   mtu 9000
   vrf Tenant_A_OP_Zone
   ip helper-address 10.1.1.1 vrf Tenant_A_OP_Zone  source-interface Loopback1
```

And so on

## Role or Module Name
eos_l3ls_evpn template leaf-tenant-vlan-interfaces.j2

We should consider this for profile, vlan interface, vrf options and include conditionals to do so.
We should update the documentaiton to reflect the same.

```
{#                 Apply IP helper configuration from SVI interface #}
{%                 if tenants[tenant].vrfs[vrf].svis[svi].ip_helpers is defined and tenants[tenant].vrfs[vrf].svis[svi].ip_helpers is not none %}
    ip_helpers:
{%                     for helper_ip in tenants[tenant].vrfs[vrf].svis[svi].ip_helpers %}
      {{ helper_ip }}:
        source_interface: {{ tenants[tenant].vrfs[vrf].svis[svi].ip_helpers[helper_ip].source_interface }}
{%                          if tenants[tenant].vrfs[vrf].svis[svi].ip_helpers[helper_ip].source_vrf is defined and tenants[tenant].vrfs[vrf].svis[svi].ip_helpers[helper_ip].source_vrf is not none %}
        vrf: {{ tenants[tenant].vrfs[vrf].svis[svi].ip_helpers[helper_ip].source_vrf }}
{%                          else %}
        vrf: {{ vrf }}
{%                          endif %}
{%                     endfor %}
{#                 Apply IP helper configuration from VRF configuration #}
{%                 elif tenants[tenant].vrfs[vrf].ip_helpers is defined and tenants[tenant].vrfs[vrf].ip_helpers is not none %}
    ip_helpers:
{%                     for helper_ip in tenants[tenant].vrfs[vrf].ip_helpers %}
      {{ helper_ip }}:
        source_interface: {{ tenants[tenant].vrfs[vrf].ip_helpers[helper_ip].source_interface }}
{%                          if tenants[tenant].vrfs[vrf].ip_helpers[helper_ip].source_vrf is defined and tenants[tenant].vrfs[vrf].ip_helpers[helper_ip].source_vrf is not none %}
        vrf: {{ tenants[tenant].vrfs[vrf].ip_helpers[helper_ip].source_vrf }}
{%                          else %}
        vrf: {{ vrf }}
{%                          endif %}
{%                     endfor %}
{#                 Apply IP helper configuration from SVI profile #}
{%                 elif profile.values.ip_helpers is defined and profile.values.ip_helpers is not none %}
    ip_helpers:
{%                     for helper_ip in profile.values.ip_helpers %}
      {{ helper_ip }}:
        source_interface: {{ profile.values.ip_helpers[helper_ip].source_interface }}
{%                          if profile.values.ip_helpers[helper_ip].source_vrf is defined and profile.values.ip_helpers[helper_ip].source_vrf is not none %}
        vrf: {{ profile.values.ip_helpers[helper_ip].source_vrf }}
{%                          else %}
        vrf: {{ vrf }}
{%                          endif %}
{%                     endfor %}
{%                 endif %}
```

### OS / Environment

__EOS Version__

__Cloudvision version__ (optional)

__OS running Ansible__

## Steps to reproduce

```yaml

```

### Expected results

```shell
interface Vlan10
   vrf test
   ip address 1.1.1.1/24
   ip helper-address 2.2.2.2
```
```
(config-if-Vl10)#ip helper-address 1.1.1.1 ?
  source-address    Specify the source address to communicate with the DHCP server
  source-interface  Specify the source interface to communicate with the DHCP server
  vrf               Specify VRF of the DHCP server
  <cr>
```

### Actual results

```shell

```

**Comment by onurgashi** [comment]
Just some updates after tests run with @ClausHolbechArista 

- We have a mandatory requirement for source_interface, and this is not required by EOS so using `source_interface: null` to workaround it
- Regarding the obligatory VRF print (if none defined use the SVIs VRF) this is not required by EOS, and the EOS ignores it, but this should be optional if configured using vars
- Only case where we would need `source_vrf` is when we have DHCP relay across VRFs
- The ip_helper address in the same VRF should not be configured on an interface where the Helper is located. i.e vlan502 with 10.10.2.254/24 as IP, should not configure ip helper 10.10.2.10 on the SVI. It should be only configured anything but the local SVI where DHCP server is located.
- https://github.com/aristanetworks/ansible-avd/issues/639 Is really helpful with scoping the DHCP replies, should be considered to be added

**Comment by ClausHolbechArista** [comment]
Fix inbound in https://github.com/ClausHolbechArista/ansible-avd/tree/fix-issue539-dhcp-helper
Setting for 3.0 since it would change config outputs if no VRF is supplied.
