### ISSUE TITLE
L2 interfaces and channel-group bug in cli_config_gen

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#542]
## Issue Type

- Bug Report
- Documentation Issue Report
- EOS Configuration error

## Summary
When we configure channel-group under a port-channel it overrides anything else.
That is desirable to remove redundant configuration, but it should take into account qos, macsec etc) which are configured on physical interface rather than the port-channel level.

```
{%         if ethernet_interfaces[ethernet_interface].channel_group is defined and ethernet_interfaces[ethernet_interface].channel_group is not none %}
   channel-group {{ ethernet_interfaces[ethernet_interface].channel_group.id }} mode {{ ethernet_interfaces[ethernet_interface].channel_group.mode }}
{%         else %}
{%             if ethernet_interfaces[ethernet_interface].mtu is defined and ethernet_interfaces[ethernet_interface].mtu != 1500 %}
   mtu {{ ethernet_interfaces[ethernet_interface].mtu }}
{%             endif %}
```

## Role or Module Name
eos_cli_config_gen

### OS / Environment

__EOS Version__

__Cloudvision version__ (optional)

__OS running Ansible__

## Steps to reproduce

```yaml

```

### Expected results

```shell
$
```

### Actual results

```shell

```

**Comment by ClausHolbechArista** [comment]
I believe QOS is based on port-channel config and not member config. I don't know about the rest of the parameters, so we should probably investigate them one-by-one.
One point though is with port-channel fallback where we use the configuration on the interface during fallback.

**Comment by onurgashi** [comment]
LACP fallback is required, so we need to resolve this.
