### ISSUE TITLE
eos_l3ls_evpn support for gnmi 

### ISSUE THREAD

**Issue by ksator** [aristanetworks/ansible-avd#597]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Role enhancement (eos_l3ls_evpn)

gnmi is currently supported by the role `eos_cli_config_gen` but not yet by the role `eos_l3ls_evpn` 

**Describe the solution you'd like**

`eos_l3ls_evpn` input can be: 

```
gnmi_enable: true
# Optional fields
gnmi_hosts:
  - < host1>
gnmi_port: xxxx
```
it should output the input required by thw role  `eos_cli_config_gen` for gnmi

**Comment by carlbuchmann** [comment]
@ksator closing issue, as there is no longer a need to replicate data model in eos_design (eos_l3ls_evpn) - you can use native syntax or `custom_structured_configuration`.
