### ISSUE TITLE
Role description is missing

### ISSUE THREAD

**Issue by ankudinov** [aristanetworks/ansible-avd#63]
[Role description](https://github.com/aristanetworks/ansible-avd/blob/feature-avd-documentation/ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md#role-name) is missing.

**Comment by ankudinov** [comment]
[arista.avd.eos_config_deploy_eapi description](https://github.com/aristanetworks/ansible-avd/blob/feature-avd-documentation/ansible_collections/arista/avd/roles/eos_config_deploy_eapi/README.md) is missing as well. Creating for tracking.

**Comment by carlbuchmann** [comment]
Initial documentation has been committed
