### ISSUE TITLE
Interface level documentation for ptp, macsec, qos in eos_cli_config_gen

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#631]
**Issue Type**

- [ ] Template enhancement
- [ ] Role enhancement
- [x] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**
We should add documentation under ethernet interfaces and port-channels as separate section in optional format.
This should follow the same data model as we have for L2, L3 and so on.

**Describe the solution you'd like**

```
Section L2

Section L3

Section PTP (if feature enabled)

Section MACsec (if feature enabled)

Section QOS (if feature enabled)
```

**Describe alternatives you've considered**

**Additional context**

**Comment by carlbuchmann** [comment]
@onurgashi I see you reference PR #632, can this issue be closed or is there still some outstanding items?
