### ISSUE TITLE
DHCP relay suppression over VXLAN

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#639]
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Since 4.25.1 we have support for DHCP relay suppression for tunnelled requests when DHCP relay is configured on more than one VTEP for the same VLAN.

We can enable on L3 VTEPs.

```
dhcp relay
    tunnel requests disabled
```

We should integrate this into eos_cli_config_gen and eos_l3ls_evpn. As it will be useful for duplicates over VXLAN.

**Describe the solution you'd like**

cli_config_gen

```
dhcp_relay:
  tunnel_requests_disabled: < true | false >
```

l3ls_evpn probably as a global knob under tenants

```
dhcp_relay_suppress_tunneled_requests: < true | false - default >
```

Happy to hear any better var suggestions?

This should be implemented on L3 VTEPs, or VTEPs with VVTEP configuration in Centralised GW scenarios.

**Describe alternatives you've considered**

Has to go statically for each leaf.

**Additional context**

**Comment by ClausHolbechArista** [comment]
Add feature now. 
In eos_design, default disabled. Add item to 4.0 project to enable this by default. Add upgrade role coverage to disable when upgrading from 3.x to 4.0.
Make sure to add a remark that this should be disabled if any leaf has `evpn_services_l2_only:true` and DHCP clients behind it.

**Comment by c-po** [comment]
Is there any work done on this for the 3.x version? We are hitting this problem and currently use the ugly `eos_cli:` key for it but it get's cluttered really fast.
