### ISSUE TITLE
Is this README required?

### ISSUE THREAD

**Issue by ankudinov** [aristanetworks/ansible-avd#64]
Is [this README](https://github.com/aristanetworks/ansible-avd/blob/feature-avd-documentation/ansible_collections/arista/avd/README.md) required? If yes, make a reference to the main one.

**Comment by carlbuchmann** [comment]
new landing page with pointer see commit: 12435857a8ac97f588ee252f97b132db6cf0c879

**Comment by carlbuchmann** [comment]
@ankudinov - I split up what should on a landing page with a pointer to arista.avd detailed installation README.md Let me know if I can close.
