### ISSUE TITLE
Move "ip ospf" commands to "router ospf" scope

### ISSUE THREAD

**Issue by bingbucks** [aristanetworks/ansible-avd#66]
Move "ip ospf" commands to "router ospf" scope instead of under, say, "Interface EthernetX" scope. I think this makes it easier to debug the derive configs by putting all relevant info into less areas of the running-config.

**Comment by carlbuchmann** [comment]
@bingbucks, thanks for submitting an issue! This is a matter of preference. In the router OSPF scope, interfaces are enabled with a network statement, I'm not sure if that makes it any easier to identify which interface can participate in OSPF. What about we augment the generated documentation section and include a summary of OSPF enabled interfaces?

**Comment by bingbucks** [comment]
Sometimes it's apparent in the Interface scope with an "ip ospf point-to-point", assuming it's a point-to-point link.

I like your idea. Perhaps we could also add a comment in the "router" scope that says something like:

_!! Interfaces participating in OSPF: e1, e22, e48/2, etc_

Or vice versa, in the "Interface" scope (depending on the config approach taken):

_!! I'm participating in OSPF_

Can all be done with the "comment" CLI command

**Comment by carlbuchmann** [comment]
Solved by augmenting OSPF device documentation output from eoc_cli_config_gen PR #468
