### ISSUE TITLE
Super Spines to support OSPF for underlay

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#666]
## Issue Type

- [x] Bug Report
- [ ] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary

After all the changes we should adapt the underlay OSPF to work with 5-Stage CLOS.

## Component Name
eos_l3ls_evpn role

## Steps to reproduce

```yaml

```

### Expected results

```shell
$
```

### Actual results

```shell

```

**Comment by carlbuchmann** [comment]
This is supported as of 3.0.0rc1, documentation needs to be updated.
