### ISSUE TITLE
CI mkdocs test case often fails

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#671]
## Issue Type

- [X] Bug Report

## Summary

CI test "mkdocs" often fail during automated testing. Rerunning usually works. Sometimes it needs repeated attempts.

## Component Name

ansible-avd CI

## Steps to reproduce

Commit to an open PR and wait for CI to run.

### Expected results

mkdocs to work as long as I don't have typos.

### Actual results

mkdocs fail after the 30-second delay.

**Comment by titom73** [comment]
2 different failures have been identified:

- Unable to docker pull curl image

```bash
Unable to find image 'appropriate/curl:latest' locally
latest: Pulling from appropriate/curl
ff3a5c916c92: Pulling fs layer
...
58ae3cb4aac4: Pull complete
Digest: sha256:c8bf5bbec6397465a247c2bb3e589bb77e4f62ff88a027175ecb2d9e4f12c9d7
Status: Downloaded newer image for appropriate/curl:latest
Error: Process completed with exit code 7.
```

- Timeout to reach always the same destination: seems to be related to Actions infrastructure

```bash
http://127.0.0.1:8000/roles/eos_l3ls_evpn
	timeout	tools.ietf.org/html/rfc7432#section-8.3.1
```

__Related file:__ https://github.com/aristanetworks/ansible-avd/blob/devel/.github/workflows/documentation-check.yml

**Comment by titom73** [comment]
Still happening with a dedicated image.
Investigation for a workaround in progress

**Comment by titom73** [comment]
- MKDOC image has been updated with cURL to run test within the container
- Following target will be added to Makefile to replace current implementation

```bash
ci-check-links-avd: ## CI workflow to test HTTP link
	@echo "--------------------------"
	@echo "Starting docker stack for testing"
	@echo "--------------------------"
	cp development/docker-compose.yml . \
	&& sed -i 's/ansible-avd\///g' docker-compose.yml \
	&& docker-compose -f docker-compose.yml up -d webdoc_avd \
	&& docker-compose -f docker-compose.yml ps
	@echo ""
	@echo "--------------------------"
	@echo "Checking if web server is started"
	@echo "--------------------------"
	until docker exec webdoc_avd curl -s -I http://localhost:8000/ ; do sleep 2; done
	@echo ""
	@echo "--------------------------"
	@echo "Check HTTP link"
	@echo "--------------------------"
	docker run --network container:webdoc_avd raviqqe/muffet:1.5.7 http://127.0.0.1:8000/ -e ".*fonts.gstatic.com.*" -e ".*tools.ietf.org.*" -e ".*edit.*" -f --limit-redirections=3 --timeout=30
	@echo ""
	@echo "--------------------------"
	@echo "Shutting down docker stack"
	@echo "--------------------------"
	docker-compose -f docker-compose.yml down
```

It allows us to remove pulling of a third image. If error moves to pull of a docker-compose image, it will mean we are facing issue with hub permission or GH actions limitation.
