### ISSUE TITLE
blank "mgmt_ip" in fabric.yml leads to the ansible error during Generate EVPN fabric documentation in Markdown Format

### ISSUE THREAD

**Issue by lermilov** [aristanetworks/ansible-avd#682]
## Issue Type

- [ ] Bug Report
- [ ] EOS Configuration rendering error
- [x] Documentation Issue Report

## Summary

blank "mgmt_ip" in fabric.yml leads to the ansible error during Generate EVPN fabric documentation in Markdown Format:
TASK [eos_l3ls_evpn : Generate EVPN fabric documentation in Markdown Format.] ****************************************************************************************
fatal: [co-dmz-leaf-01A -> localhost]: FAILED! => changed=false 
  msg: |-
    AnsibleError: Unexpected templating type error occurred on ({% set fabric_switches = [] %}
    {% set topology_links = [] %}
    {% set underlay_p2p_network_summaries = [] %}
...
    ): object of type 'bool' has no len()

## Component Name
eos_l3ls_evpn documentation

## Steps to reproduce

l2leaf:
  node_groups:
    co-dmz-leaf-01:
      parent_l3leafs: [ co-dmz-leaf-l3-1A, co-dmz-leaf-l3-1B ]
      filter:
        tenants: [ TENANT_DMZ ]
        tags: [ dmz ]
      nodes:
        co-dmz-leaf-01A:
          id: 1
          mgmt_ip: ""   <==== blank MGMT IP
          l3leaf_interfaces: [ Ethernet21, Ethernet21 ]

```yaml

```

### Expected results

```shell
$
```

### Actual results

```shell

```

**Comment by ClausHolbechArista** [comment]
@lermilov if this is still relevant, you can test PR #941.
