### ISSUE TITLE
Support to have multiple parallel links between Leaf and Spine pair

### ISSUE THREAD

**Issue by lermilov** [aristanetworks/ansible-avd#692]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**
I have a use-case where 2x100GE is used between same Leaf and Spine devices

from eos_l3ls_evpn role I see that number of spines should correlate with number of uplinks_to_spines:
{# Leaf P2P interfaces #}
{% for uplink_to_spine_interface in leaf.uplink_to_spine_interfaces %}
  {{ uplink_to_spine_interface }}:
    peer: {{ leaf.spines[loop.index0] }}
...

**Describe the solution you'd like**
Additional knob to instruct ansible role to consider parallel links to the same spine.
For example:
    xx-leaf-01:
      bgp_as: 65101
      parallel_links_to_spine: 2
      uplink_to_spine_interfaces: ['Ethernet51/1', 'Ethernet52/1','Ethernet53/1', 'Ethernet54/1']
      nodes:
        xx-leaf-01A:
          id: 7
          mgmt_ip: x.x.x.x/24
          spine_interfaces:
          - Ethernet1/1
          - Ethernet2/1
          - Ethernet1/1
          - Ethernet22/1

**Describe alternatives you've considered**

**Additional context**

**Comment by ClausHolbechArista** [comment]
@lermilov 
This will be solved with PR #932.

I tested with this data and it worked as intended. So it will now be possible to mix different number of uplinks per device:
```l3leaf:
  defaults:
    # virtual router mac for VNIs assigned to Leaf switches
    # format: xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:dc:01
    platform: vEOS-LAB
    #bgp_as: 65100
    spines: [DC1-POD1-SPINE1, DC1-POD1-SPINE2]
    uplink_to_spine_interfaces: [Ethernet2, Ethernet3]
    mlag_interfaces: [Ethernet1, Ethernet6]
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    evpn_route_servers: ['DC1-RS1', 'DC1-RS2']
  node_groups:
    DC1_POD1_LEAF1:
      bgp_as: 65101
      filter:
        tenants:
          - Tenant_A
      spines: [DC1-POD1-SPINE1, DC1-POD1-SPINE2, DC1-POD1-SPINE1, DC1-POD1-SPINE2]
      uplink_to_spine_interfaces: [Ethernet2, Ethernet3, Ethernet12, Ethernet13]
      nodes:
        DC1-POD1-LEAF1A:
          id: 1
          mgmt_ip: 192.168.0.12/24
          spine_interfaces: [Ethernet2, Ethernet2, Ethernet12, Ethernet12]
        DC1-POD1-LEAF1B:
          id: 2
          mgmt_ip: 192.168.0.13/24
          spine_interfaces: [Ethernet3, Ethernet3, Ethernet13, Ethernet13]
    DC1_POD1_LEAF2:
      bgp_as: 65102
      evpn_services_l2_only: true
      nodes:
        DC1-POD1-LEAF2A:
          id: 3
          mgmt_ip: 192.168.0.14/24
          spine_interfaces: [Ethernet4, Ethernet4]
        DC1-POD1-LEAF2B:
          id: 4
          mgmt_ip: 192.168.0.15/24
          spine_interfaces: [Ethernet5, Ethernet5]
```
