### ISSUE TITLE
EVPN A/A to use loopback0 as vxlan source

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#704]
## Issue Type

- [x] Bug Report
- [ ] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary

In cases where A/A is implemented, we most likely will run unique ASN per leaf, and no peer-link between.
This pushes the config to:
- Use unique ASN per leaf
- Use unique IP for loopback as source for VXLAN

In such cases we should not define loopback1 as there is no common loopback needed, and live with loopback0 that can be used as source.

We should define a knob that by default is true, but can be false so it won't create loopback1 and will change vxlan source interface in case of A/A.

`vxlan_source_interface_lo1: false`

## Component Name
eos_designs.eos_l3ls_evpn

## Steps to reproduce

```yaml

```

### Expected results

```shell
Vxlan1 to use Lo0 as source.
```

### Actual results

```shell

```

**Comment by lermilov** [comment]
Possible fix:
1. Within /base/fabric/interfaces/leaf-vtep-vxlan-tunnel-loopback.j2:
```
{# Leaf VTEP vxlan tunnel loopback source interface #}
{% if vxlan_source_interface_lo1 is defined and vxlan_source_interface_lo1 == true %}}
  Loopback1:
    description: VTEP_VXLAN_Tunnel_Source
    shutdown: false
...
{% endif %}
```
2. Within base/tenant_evpn_vxlan/leaf_vxlan_vtep_interface:
```
{# vxlan-vtep interface #}
  Vxlan1:
    description: {{ inventory_hostname }}_VTEP
{% if vxlan_source_interface_lo1 is defined and vxlan_source_interface_lo1 == false %}
    source_interface: Loopback0
{% else %}
    source_interface: Loopback1
{% endif %}
...
```

3. Add `vxlan_source_interface_lo1: true` to eos_l3ls_evpn defaults variables
