### ISSUE TITLE
eos_cli_config_gen router bgp send-community

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#706]
**Issue Type**

- [x] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Currently, "send-community" feature is not implemented consistently within router bgp global and vrf definition sections.
Also send-community knob should not allow empty or None/null value.

TO DO - Documented the desired data model.

**Comment by ClausHolbechArista** [comment]
Resolved by PR #812
