### ISSUE TITLE
load-interval default not rendered by eos_l3ls_evpn role

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#715]
## Issue Type

- [x] Bug Report

## Summary

load-interval default is not rendered by eos_l3ls_evpn role because of syntax missmatch with eos_cli_config_gen role.
We could pass it through to eos_cli_config_gen role.

eos_l3ls_evpn:
{% if load_interval_default is defined %}
  default: {{ load_interval_default }}
{% endif %}

versus eos_cli_config_gen
{% if load_interval is defined and load_interval is not none %}
!
load-interval default {{ load_interval.default }}
{% endif %}

## Component Name
eos_l3_evpn

## Steps to reproduce

```yaml
load_interval:
  default: 60
```

### Expected results

```shell
$
load-interval default 60
```

### Actual results

```shell
structured_config:
load_interval: null

not showing up in cli config
```

**Comment by kmueller68** [comment]
Suggestion for solution:
/ansible-avd/ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/base/load-interval.j2

**current:**
{% if load_interval_default is defined %}
  default: {{ load_interval_default }}
{% endif %}

**new:**
{% if load_interval is defined %}
load_interval:
  default: {{ load_interval.default }}
{% endif %}

**Comment by titom73** [comment]
Hello @kmueller68 

While we look at this, you might try using the `eos_cli_config_gen` directly through `eos_l3ls_evpn` to the structured configuration using `custom_structured_configuration_load_interval`, this will give you the expected result.

Kind Regards,

**Comment by tgodaA** [comment]
Actually you can try this in group_vars or host_vars:

load_interval_default: 60

This worked for me.

This needs to be documented in eos_designs to clear the misunderstanding.
