### ISSUE TITLE
Support of spanning-tree bpduguard in eos_l3ls_evpn port profiles in SERVERS.yml

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#716]
**Issue Type**

- [x] Template enhancement

**Describe the solution you'd like**
Support of spanning-tree bpduguard enabled to fabric edge ports to enable a kind of loop detection.
This should be available via port-profiles and/or individual server definitions in the DC_SERVERS.yml file.
Feature should be available on individual ethernet interfaces and port-channels.

spanning_tree_bpduguard: < true | false > 
should render "spanning-tree bpduguard enabled"

port_profiles:
  < port_profile_1 >:
    "snip"
    spanning_tree_portfast: < edge | network >
    spanning_tree_bpdufilter: < true | false >
    **spanning_tree_bpduguard: < true | false >** 

**Describe alternatives you've considered**
I might enable it globally for all interfaces via the eos_cli_config_gen template
spanning_tree:
  edge_port:
    bpduguard_default: < true | false >

and disable it manually individually on (edge) ports, to which addtional switches are connected to.

**Comment by onurgashi** [comment]
+1
