### ISSUE TITLE
Management API GNMI needs to be rewritten

### ISSUE THREAD

**Issue by xaviramon** [aristanetworks/ansible-avd#733]
## Issue Type

- [x] Bug Report
- [x] EOS Configuration rendering error
- [x] Documentation Issue Report

## Summary

Management API GNMI under eos_cli_config_gen can generate an invalid EOS config and no ACL can be attached under VRF default.
Also, on EOS 4.23 only one VRF is supported.

Reference: https://github.com/aristanetworks/ansible-avd/pull/712/files/f1395d2a3c1c39dd21e7ffdcb0e9dddc2ac0d88a#diff-e80046d9f2062fa3acd99391802e9919ae5c9ad759f433ebb4103c9370266942

## Component Name
eos_cli_config_gen

## Steps to reproduce

```yaml

```

### Expected results

```shell
$
```

### Actual results

```shell

```

**Comment by ClausHolbechArista** [comment]
Talked to Xavier and this is no longer needed.
