### ISSUE TITLE
Changing amount of spines will renumber all leafs

### ISSUE THREAD

**Issue by sebastianw** [aristanetworks/ansible-avd#744]
## Issue Type

- [X] Bug Report
- [ ] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary

When the number of Spines changes, all Leafs will renumber their loopback IPs (and router-ids, etc.). It seems that Leaf Loopback-IP is just `sum(Spines)+<Leaf id>`.

Maybe using an offset (Leaf Loopbacks / Router-IDs start at `<offset>` IPs after Spine IPs instead of directly after spine IPs) would help.

## Steps to reproduce

* Build config for fabric with 4 Spines
* Add two additional Spines
* See that all Leaf loopbacks got renumbered

### Expected results

Leafs would keep their loopback IP.

### Actual results

Leafs get renumbered, chaos and destruction follows.

**Comment by titom73** [comment]
Hello @sebastianw 

Indeed, it is currently available only on super-spine devices and we will work on an implementation for spine devices.

**Comment by titom73** [comment]
cc @mpergament

**Comment by onurgashi** [comment]
As a workaround at least until this gets resolved we would recommend to factor in the max numbers of Spines planned with scalability taken into account. That will reserve the IP space so it will not cause problems in the future.
