### ISSUE TITLE
Verify FANs airflow direction with validate_state

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#767]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [x] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

In new deployments it makes sense to understand the airflow direction of a switch in large setups, if something was racked wrong.

**Describe the solution you'd like**

Read out if the switch is F/R and direction of airflow

show inventory
show env

**Describe alternatives you've considered**

**Additional context**

**Comment by xaviramon** [comment]
We need more information or think how we want to report that. Since there is no "PASS/NOPASS" real answer without user input

**Comment by onurgashi** [comment]
Fair point. We'll have to take this separately into snapshot or something. Appreciate you looking into this @xaviramon
