### ISSUE TITLE
role eos_cli_config_gen fails without key "management_eapi.enable_http" explicitly set

### ISSUE THREAD

**Issue by kornoa** [aristanetworks/ansible-avd#785]
<!---
## Issue Type

- [x] Bug Report

## Summary

We use role eos_designs.
Without having explicitly set the key management_eapi.enable_http to true or false causes the role eos_cli_config afterwards fails.
Error Message for each host in inventory:
fatal: [my_hostname_1 -> localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'enable_http'"}

## Component Name
role eos_cli_config

## Current Workaround

We added the rquired to fabric group_vars.
```yaml
management_eapi:
  enable_http: false
```

**Comment by carlbuchmann** [comment]
@kornoa thanks for opening an issue.

I believe it has been fixed with this PR: https://github.com/aristanetworks/ansible-avd/pull/782.

Can you confirm what branch/commit you are working from?

**Comment by kornoa** [comment]
We're working on commit bb5ed49c1bbc75814d4dd538c5c346d789cb266a.

**Comment by kornoa** [comment]
I can confirm that commit 10d35d1adb4358950d2ec7c6664d8a1387513c40 fixes issue. Sorry, for creating the issue without using the newest commit.
