### ISSUE TITLE
Add support for STP super root feature

### ISSUE THREAD

**Issue by mpergament** [aristanetworks/ansible-avd#789]
**Issue Type**

- [x] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Add "spanning-tree root super"

**Describe alternatives you've considered**

**Additional context**

**Comment by ClausHolbechArista** [comment]
Solved by #790
