### ISSUE TITLE
BGP peer group names are different in FABRIC.yaml compared to template

### ISSUE THREAD

**Issue by jalmargyyk** [aristanetworks/ansible-avd#792]
## Issue Type

- [x] Bug Report

## Summary
BGP peer group names are defined with underscores (e.g. IPv4_UNDERLAY_PEERS) in FABRIC.yaml. In the actual [template](ansible_collections/arista/avd/roles/eos_designs/templates/designs/l3ls-evpn/fabric/bgp_base/leaf-router-bgp-peer-groups.j2) the groups are defined with dashes (e.g. IPv4-UNDERLAY-PEERS). This causes confusion if you are generating the bgp group passwords based on the FABRIC.yaml definition since the encrypted password is different.

This could be mentioned in FABRIC.yaml comment if the group names can't be changed in FABRIC.yaml

## Steps to reproduce

router(config-router-bgp)#neighbor IPv4_UNDERLAY_PEERS peer group
router(config-router-bgp)#neighbor IPv4_UNDERLAY_PEERS password foobar
router(config-router-bgp)#neighbor IPv4-UNDERLAY-PEERS peer group
router(config-router-bgp)#neighbor IPv4-UNDERLAY-PEERS password foobar
router(config-router-bgp)#show ac
<--clip-->
   neighbor IPv4-UNDERLAY-PEERS peer group
   neighbor IPv4-UNDERLAY-PEERS password 7 jXgAYv3MSAORMJ0AUff3HQ==
   neighbor IPv4_UNDERLAY_PEERS peer group
   neighbor IPv4_UNDERLAY_PEERS password 7 5ADpxg1cWfp2LSdERBpzFQ==
<--clap-->

**Comment by carlbuchmann** [comment]
@jalmargyyk thank you for the feedback, I will update the documentation accordingly for the next release.

Do you believe there is also value in providing a knob to change the bgp peer group name?

**Comment by jalmargyyk** [comment]
@carlbuchmann Yes, I believe many organizations have their own naming schemes, so the knob would make it more comfortable to use this collection.

**Comment by carlbuchmann** [comment]
@jalmargyyk thanks for there feedback, and will work on a knob for a future release, this will be tracked in issue #798.

**Comment by carlbuchmann** [comment]
resolved by #798
