### ISSUE TITLE
Generate documentation for fabrics if two or more

### ISSUE THREAD

**Issue by melkypie** [aristanetworks/ansible-avd#801]
**Issue Type**

- [ ] Template enhancement
- [X] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Currently documentation will only be generated for only 1 fabric when there are 2 or more fabrics defined. This seems to be due to documentation being only ran once rather than ran per fabric.

**Describe the solution you'd like**

For documentation to be generated for each fabric not just the first fabric.

**Describe alternatives you've considered**

Using multiple branches to seperate each fabric. This is not ideal because I have to maintain 2 AVD_LAB.yml files for common variables that may span across Fabrics/DCs

**Additional context**

**Comment by carlbuchmann** [comment]
@melkypie I see you closed the issue before we had a chance to respond. I assumed you resolved it, by having a unique "fabric_name" and different "dc_name" / "pod_name"?

I'm re-opening the issue, so we can add documentation to make this more clear, specifically in this section:

- on GitHub: https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_designs/doc/l3ls-evpn.md
- on avd.sh: https://avd.sh/en/latest/roles/eos_designs/doc/l3ls-evpn/

**Comment by melkypie** [comment]
Yea I looked at the topology image in the main README.md and then noticed it. Maybe would be best to mention how something like group_vars could look like with multiple dcs/pods, since currently everything is mostly single dc/pod focused.

**Comment by carlbuchmann** [comment]
@melkypie PR #810 will address this. I apologize in advance that it may cause some merge conflicts in your incoming PRs. I'm happy to update them accordingly!

**Comment by carlbuchmann** [comment]
Resolved by #810
