### ISSUE TITLE
Support ESI AA port-channel to connect L2LEAF uplinks

### ISSUE THREAD

**Issue by lermilov** [aristanetworks/ansible-avd#807]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**
Currently, eos_designs role assumes that L2LEAFs are connected to L3LEAF MLAG pair.
This feature request is to add configuration knob to choose which type of multihoming to use for L2LEAF.

**Describe the solution you'd like**
Currently, eos_designs role assumes that L2LEAFs are connected to L3LEAF MLAG pair.
"short_esi" value for L2LEAF should have some default values based on the Port-Channel number and pair id.

**Describe alternatives you've considered**

define exact "short_esi" per L2LEAF node_group

**Additional context**

**Comment by titom73** [comment]
Also required for FR-PROJET-03
