### ISSUE TITLE
l3_only support for l3leaf in eos_designs

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#821]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

There will be leaf switches that will act either as Border Leaf or L3 Gateway. The role of the switch is simply to perform interworking between EVPN < - > VPNv4, or just simply Leaf with VRFs only and nothing connected to it.

**Describe the solution you'd like**

Today we have a nice feature for L2 Border Leaf or L2 Gateway that is l2_only, we would like to have something similar for l3_only, where from tenants structure we just create the VRFs, L3VNI and with no VLAN, SVI, L2VNI

l3_only can be implemented in the l3leaf structure where we define a leaf as L3 only, thus we create only the VRF and L3 VNI for it.

**Describe alternatives you've considered**

**Additional context**

**Comment by ClausHolbechArista** [comment]
In PR #825 I opted for a slightly different approach, to not limit the user from configuring VLANs if they like, but simply to force VRFs to be configured.
