### ISSUE TITLE
Use mac_vrf_vni_base while generating RTs for vlan-aware-bundles

### ISSUE THREAD

**Issue by mpergament** [aristanetworks/ansible-avd#827]
**Issue Type**

- [x] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

As of now mac_vrf_vni_base only used while generating RTs fro vlan-based services. 
Same value should be used while generating RTs for vlan-aware-bundles.

**Describe the solution you'd like**

Use mac_vrf_vni_base while generating RTs for vlan-aware-bundles

**Comment by ClausHolbechArista** [comment]
To avoid breaking existing deployments, I would suggest introducing an extra knob like `vlan_aware_bundle_vni_base`
Edit: I misunderstood the problem. The RT for vlan-aware-bundles is based on VRF VNI number, so it would not be consistent if we also offset the VRF VNI with the same number. So I would still propose to have a separate knob for this.
