### ISSUE TITLE
Add single-connection knob for tacacs server

### ISSUE THREAD

**Issue by slackwei** [aristanetworks/ansible-avd#837]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**
With cisco ISE and command authorization enabled, ISE complained about too many tcp sessions even though they were closed.

**Describe the solution you'd like**
To add single-connection knob to tacacs server,

**Describe alternatives you've considered**
tacacs-server host a.b.c.d single-connection vrf MGMT key 7 xxxxxx

**Additional context**

**Comment by ryanmerolle** [comment]
I was just about to raise an issue for this.  Should be an easy template update.  I am happy to assist if you want, if you did not prirotize this @ClausHolbechArista

**Comment by ClausHolbechArista** [comment]
> I was just about to raise an issue for this.  Should be an easy template update.  I am happy to assist if you want, if you did not prirotize this @ClausHolbechArista 

Please go ahead. Thanks.

**Comment by ryanmerolle** [comment]
@ClausHolbechArista PR submitted for review
