### ISSUE TITLE
Add event-handler to clear EVPN blacklisted MAC-address

### ISSUE THREAD

**Issue by lermilov** [aristanetworks/ansible-avd#84]
Due to absence of recovery timer for EVPN blacklist MAC-addresses possible workaround would be following event-handler:

event-handler evpn-blacklist-recovery
  action bash FastCli -p 15 -c “clear bgp evpn host-flap”
  delay 300
  !
  trigger on-logging
    regex EVPN-3-BLACKLISTED_DUPLICATE_MAC

**Comment by carlbuchmann** [comment]
fixed in PR #121, thanks for the suggestion @lermilov and @titom73 for the new templates :)
