### ISSUE TITLE
p2p_link_interface_speed is not set on spines

### ISSUE THREAD

**Issue by mpergament** [aristanetworks/ansible-avd#850]
## Issue Type

- [ ] Bug Report
- [ ] EOS Configuration rendering error
- [x] Documentation Issue Report

## Summary
According to documentation: # Point-to-Point interface speed - will apply to L3 Leaf **and Spine** switches | Optional.
However, additional setting is required for config to be applied on the spine:
```
l3leaf:
  defaults:
      spine_interface_speed: true

**Comment by ClausHolbechArista** [comment]
This is a template bug for defaults key. Please correct the `elif` to look for the correct key name and it should work.
