### ISSUE TITLE
Allow management interface in default / global routing table

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#87]
Allow management interface in default/global routing table

Updates to the following templates/data model will be required:
https://github.com/aristanetworks/ansible-avd/blob/master/ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/base/mgmt-interface.j2

https://github.com/aristanetworks/ansible-avd/blob/master/ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/base/mgmt-vrf.j2

**Comment by ankudinov** [comment]
Q: Using VRF name "default" will cover that automatically, do I miss anything in the templates?

**Comment by titom73** [comment]
Closed since code has been merged back in March 2020
