### ISSUE TITLE
Collections eos help please.

### ISSUE THREAD

**Issue by soulkiller27** [aristanetworks/ansible-avd#90]
Hi All, 

I know this is not the place to post this question but the eos thread does not have an option to ask for support. I'm still really new to using Ansible as I have only just got Ansible roles to work i.e. the old way, and after seeing the demo video about arista.avd collections I would really like to get arista-eos  up and running without the cloudvision part but after trying to read the doc's about the eos collections I have no idea how this works. Before i could just do the following to push configuration.

- host file including groups, or children groups
- A playbook calling roles, host, and stating the connection type
- all file in the group_vars directory to push to all hosts 
- host vars in the host_vars directory to push to individual hosts including the vault stored username and password.

Could someone please let me know how I should be setting up the Ansible layout in order for this new format of arista-eos collection to work. I'm really at my wits end after not being able to find a demo complete inventory, playbook, group_vars, host_vars example.

Thanks in advanced Shaun

**Comment by carlbuchmann** [comment]
@soulkiller27 a full example of how to leverage ansible-avd, ansible-cvp and ansible-eos can be found here: https://github.com/aristanetworks/netdevops-examples/tree/master/ansible/avd-evpn-l3ls-1
Alternatively, you can also ask us questions on the arista channel on ansiblenetwork.slack.com
