### ISSUE TITLE
Support for EVPN host-flap detection

### ISSUE THREAD

**Issue by Shinz0n** [aristanetworks/ansible-avd#914]
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

I would like to change the EVPN host-flap detection default behavior which is currently set to window 180.0 and threshold 5.

**Describe the solution you'd like**

Make it possible to change EVPN host-flap detection within the eos_designs role.

**Describe alternatives you've considered**

It is possible to use the eos_cli_config_gen role for BGP configuration with address_family_evpn support. However host-flap detection is also not supported there nor I'm not sure I could stitch both roles (eos_designs + eos_cli_config_gen) together.

**Comment by carlbuchmann** [comment]
@Shinz0n had a discussion with @mpergament and @ClausHolbechArista - we suggest implementing this as a global var, as we would want this to be consistent on all L3 leaves:

```yaml
evpn_hostflap_detection:
  window: <timeout>
  threshold: <threshold>
```
