### ISSUE TITLE
eos_designs support for non-tenant networks

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#967]
**Issue Type**

- [X] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Not always will users of EVPN employ it for its tenancy/vrf functionality but instead for the desire to manage flood lists dynamically using the EVPN control plane.  In the current Network Services model, network services can only be defined in the realm of tenants.  We should be able to leverage all the same templates for tenants.  Right now, that is not possible.

**Describe the solution you'd like**

Adjust tenant templates to allow for networks to be defined outside of the tenancy model.

**Describe alternatives you've considered**

Set no tenant networks with the current model and develop an abstraction of my own by using custom

**Additional context**

**VXLAN**: Updating the model to allow for these templates to be used either for tenancy or not would not break the current model.  To be clear VNIs and everything VXLAN should still be definable in this non-tenancy model.

**Non VXLAN**: Furthermore, there is no way to define non-vxlan networks across various leaf groups.  This function is a nice to have and can be address by doing something like https://gitlab.com/ryanmerolle/avd-demo/-/blob/ryan-v2/group_vars/CAMPUS_LEAFS.yml and https://gitlab.com/ryanmerolle/avd-demo/-/blob/ryan-v2/group_vars/CAMPUS_L3LEAFS.yml

**Comment by ClausHolbechArista** [comment]
For **Non VXLAN** we will implement this with a knob per `svi`/`l2vlan`. Also requested in #1022. This will be implemented as part of PR #1000.

For using the `default` VRF for network services, I think we should still use EVPN control-plane for advertising L3 information. We will have to detect the vrf name and ensure a route-map is associated to the vrf. This is required in EOS to advertise subnets via EVPN in `default` VRF. This will be a great addition, and we can use it in other use cases as well.

Alternatively we could append the services to the `redistribute connected` route-map.

For both cases we could also optionally inject host-routes (`attached-hosts`).
