### ISSUE TITLE
Make name of Top level container in CVP configurable

### ISSUE THREAD

**Issue by lermilov** [aristanetworks/ansible-avd#990]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Current implementation of module "inventory_to_container.py" uses hardcoded value "Tenant"  for Top-level container.
This is causing an issue for CVP instances which has non-"Tenant" name of top-level container, because module can't find root containet to build ordered container list.

**Describe the solution you'd like**
collection variable to define top-level container name

**Describe alternatives you've considered**

**Additional context**

**Comment by xaviramon** [comment]
Required in ES-PROJECT-01

**Comment by ClausHolbechArista** [comment]
- The container hierarchy is going away in favor of tags.
- Changing the top level container name on cloudvision is strongly discouraged by CV devs.
- No interest since 2021.

Because of this we will close this feature request.
