### ISSUE TITLE
Feat(eos_designs): Leverage trunk groups for L3LS-EVPN L2Leaf Uplinks

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#993]
**Issue Type**

- [X] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Unlike trunks on port-channels between mlag peers, similar trunk/uplinks between L2Leafs and L3Leafs use allowed vlans instead of trunk groups.

This creates a lack of uniformity when configuring switch to switch trunks/uplinks.

**Describe the solution you'd like**

Create a trunk group just for L2 Leaf uplinks instead of using the old method of trunk allowed vlans.  This would be inline with the AVD opinionated model documented on your website.

This also allows users to append additional VLANs to an L2 and/or L2 Leaf and putting in the proper trunk group so that the uplink interfaces do not need to be updated with new allowed vlans.

**Describe alternatives you've considered**

Current approach which is disjointed from recommended model and does not allow for easy appending of additional VLANs on L2 Leafs without more substantial appending of config.

**Additional context**

**Comment by ClausHolbechArista** [comment]
Good idea! We can work on this for AVD 3.0.
