### ISSUE TITLE
Add grpcaddr option to Terminattr

### ISSUE THREAD

**Issue by melkypie** [aristanetworks/ansible-avd#999]
**Issue Type**

- [ ] Template enhancement
- [X] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Sometimes a library needs the gNMI socket of TerminAttr through a VRF which requires the -grpcaddr option to be configurable

**Describe the solution you'd like**

```yaml
daemon_terminattr:
  grpcaddr: MGMT/0.0.0.0:6042

```

**Describe alternatives you've considered**

Adding the option to eos_cli_config_gen locally.

**Additional context**

**Comment by ClausHolbechArista** [comment]
Covered by issue #505 which @noredistribution is working on.

**Comment by ClausHolbechArista** [comment]
Fixed by #1064
